// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"database/sql"
)

type Queries struct {
	db *sql.DB
}

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	return User{}, nil
}
