// Code generated by go-enum DO NOT EDIT.

package status

import (
	"fmt"
)

type Status int

const (
	StatusUnknown Status = iota
	StatusPending
	StatusActive
	StatusInactive
)

var AllStatus = []Status{
	StatusUnknown,
	StatusPending,
	StatusActive,
	StatusInactive,
}

func (s Status) String() string {
	switch s {
	case StatusUnknown:
		return "Unknown"
	case StatusPending:
		return "Pending"
	case StatusActive:
		return "Active"
	case StatusInactive:
		return "Inactive"
	default:
		return fmt.Sprintf("Status(%d)", s)
	}
}
