version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: deps(go)
    labels:
      - dependencies
      - go
    open-pull-requests-limit: 3
    auto-rebase:
      enabled: true

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: deps(npm)
    labels:
      - dependencies
      - website
    open-pull-requests-limit: 3
    auto-rebase:
      enabled: true

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: ci
    labels:
      - dependencies
      - ci
    open-pull-requests-limit: 3
    auto-rebase:
      enabled: true
