// gendocs generates documentation artifacts from the gogenfilter detectors table.
//
// Outputs:
//   - website/src/data/generators.json       — consumed by Astro components
//   - README.md sections                     — between gendocs marker comments
//   - website/src/content/docs/generators.mdx — detection table + count sections
//   - website/src/content/docs/api/detection.mdx — per-generator function table
//   - doc.go                                 — package comment generator list
//
// Usage: go run ./cmd/gendocs
//
// CI enforcement: run `go generate ./... && git diff --exit-code` to fail
// when generated docs are stale.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/LarsArtmann/gogenfilter/v3"
)

const (
	logoGeneric        = "/logos/generic.svg"
	displayContent     = "content only"
	readmeReadmePath   = "README.md"
	docGoPath          = "doc.go"
	generatorsJSONPath = "website/src/data/generators.json"
	generatorsMDXPath  = "website/src/content/docs/generators.mdx"
	detectionMDXPath   = "website/src/content/docs/api/detection.mdx"

	mdxNameWidth       = 20
	mdxFilenameWidth   = 65
	detectionFuncWidth = 26
	filePerm           = 0o600

	generatorsStartMarker = "<!-- gendocs:generators:start -->"
	generatorsEndMarker   = "<!-- gendocs:generators:end -->"
	filterOptsStartMarker = "<!-- gendocs:filter-options:start -->"
	filterOptsEndMarker   = "<!-- gendocs:filter-options:end -->"
	mdxTableStartMarker   = "{/* gendocs:detection-table:start */}"
	mdxTableEndMarker     = "{/* gendocs:detection-table:end */}"
	mdxCountStartMarker   = "{/* gendocs:count:start */}"
	mdxCountEndMarker     = "{/* gendocs:count:end */}"
	mdxPerGenStartMarker  = "{/* gendocs:per-generator:start */}"
	mdxPerGenEndMarker    = "{/* gendocs:per-generator:end */}"
	docGoListStartMarker  = "// gendocs:generator-list:start"
	docGoListEndMarker    = "// gendocs:generator-list:end"

	genericSuffix = "and any tool using the standard \"Code generated by\" comment convention"
)

// ErrMissingMetadata is returned when a detector lacks website presentation data.
var ErrMissingMetadata = errors.New("detector missing from websiteMetadata")

// websiteMeta holds website-specific presentation data not derivable from Go source.
type websiteMeta struct {
	logo        string
	displayFile string
}

// websiteMetadata maps FilterOption string values to website presentation metadata.
// If a detector exists without an entry here, gendocs exits with an error,
// ensuring new detectors get website data before they can drift.
//
//nolint:gochecknoglobals,goconst // immutable lookup table; generator names are keys, not constants
var websiteMetadata = map[string]websiteMeta{
	"sqlc":          {logo: "/logos/sqlc.png", displayFile: "*.sql.go"},
	"templ":         {logo: "/logos/templ.svg", displayFile: "_templ.go"},
	"go-enum":       {logo: "/logos/go-enum.svg", displayFile: "_enum.go"},
	"protobuf":      {logo: "/logos/protobuf.svg", displayFile: ".pb.go"},
	"oapi-codegen":  {logo: "/logos/oapi-codegen.svg", displayFile: ".gen.go"},
	"deepcopy-gen":  {logo: "/logos/deepcopy-gen.svg", displayFile: "zz_generated.*"},
	"wire":          {logo: "/logos/wire.svg", displayFile: "wire_gen.go"},
	"moq":           {logo: "/logos/moq.png", displayFile: "_moq.go"},
	"mockgen":       {logo: "/logos/mockgen.svg", displayFile: "_mock.go"},
	"stringer":      {logo: "/logos/stringer.svg", displayFile: displayContent},
	"mockery":       {logo: logoGeneric, displayFile: "mock_"},
	"ent":           {logo: logoGeneric, displayFile: displayContent},
	"gqlgen":        {logo: logoGeneric, displayFile: displayContent},
	"easyjson":      {logo: logoGeneric, displayFile: "_easyjson.go"},
	"msgp":          {logo: logoGeneric, displayFile: displayContent},
	"counterfeiter": {logo: logoGeneric, displayFile: "fake_"},
	"go-swagger":    {logo: logoGeneric, displayFile: displayContent},
	"generic":       {logo: logoGeneric, displayFile: "Code generated by"},
}

// generatorJSON is the JSON shape consumed by Astro's Generator interface.
type generatorJSON struct {
	Name string `json:"name"`
	File string `json:"file"`
	URL  string `json:"url"`
	Logo string `json:"logo"`
}

func main() {
	docs := gogenfilter.AllDetectorDocs()

	err := validateMetadata(docs)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
		os.Exit(1)
	}

	err = generateJSON(docs)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: generate JSON: %v\n", err)
		os.Exit(1)
	}

	err = generateReadme(docs)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: generate README: %v\n", err)
		os.Exit(1)
	}

	err = generateGeneratorsMDX(docs)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: generate generators.mdx: %v\n", err)
		os.Exit(1)
	}

	err = generateDetectionMDX(docs)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: generate detection.mdx: %v\n", err)
		os.Exit(1)
	}

	err = generateDocGo(docs)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: generate doc.go: %v\n", err)
		os.Exit(1)
	}

	msg := "gendocs: generated generators.json, README tables, generators.mdx, detection.mdx, doc.go"
	_, _ = fmt.Fprintln(os.Stdout, msg)
}

// validateMetadata ensures every detector has website metadata.
func validateMetadata(docs []gogenfilter.DetectorDoc) error {
	for _, doc := range docs {
		_, ok := websiteMetadata[string(doc.Option)]
		if !ok {
			return fmt.Errorf(
				"%w: %q (option %s) in cmd/gendocs/main.go",
				ErrMissingMetadata, doc.Reason, doc.Option,
			)
		}
	}

	return nil
}

// generateJSON writes the generators.json file consumed by Astro.
func generateJSON(docs []gogenfilter.DetectorDoc) error {
	generators := make([]generatorJSON, 0, len(docs))

	for _, doc := range docs {
		meta := websiteMetadata[string(doc.Option)]
		generators = append(generators, generatorJSON{
			Name: string(doc.Reason),
			File: meta.displayFile,
			URL:  doc.URL,
			Logo: meta.logo,
		})
	}

	data, err := json.MarshalIndent(generators, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal JSON: %w", err)
	}

	data = append(data, '\n')

	return writeFile(generatorsJSONPath, data)
}

// generateReadme updates the generator and filter option tables in README.md
// between gendocs marker comments.
func generateReadme(docs []gogenfilter.DetectorDoc) error {
	content, err := os.ReadFile(readmeReadmePath)
	if err != nil {
		return fmt.Errorf("read README.md: %w", err)
	}

	generatorsTable := generateReadmeGeneratorsTable(docs)
	filterOptionsTable := generateReadmeFilterOptionsTable(docs)

	updated := replaceSection(
		string(content),
		generatorsStartMarker, generatorsEndMarker,
		generatorsTable,
	)
	updated = replaceSection(
		updated,
		filterOptsStartMarker, filterOptsEndMarker,
		filterOptionsTable,
	)

	return writeFile(readmeReadmePath, []byte(updated))
}

// generateReadmeGeneratorsTable produces the "Supported Generators" table.
func generateReadmeGeneratorsTable(docs []gogenfilter.DetectorDoc) string {
	var builder strings.Builder

	builder.WriteString("| Tool | Detection |\n")
	builder.WriteString(
		"| --------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |\n",
	)

	for _, doc := range docs {
		name := displayName(string(doc.Reason))
		detection := readmeDetection(doc)

		if doc.URL != "" {
			fmt.Fprintf(&builder, "| [%s](%s) | %s |\n", name, doc.URL, detection)
		} else {
			fmt.Fprintf(&builder, "| **%s** | %s |\n", name, detection)
		}
	}

	return builder.String()
}

// generateReadmeFilterOptionsTable produces the "Filter Options" table.
func generateReadmeFilterOptionsTable(docs []gogenfilter.DetectorDoc) string {
	var builder strings.Builder

	builder.WriteString("| Option | Detection |\n")
	builder.WriteString(
		"| ---------------- | -------------------------------------------------------------------- |\n",
	)

	for _, doc := range docs {
		optionConst := optionToConstName(string(doc.Option))
		detection := readmeDetection(doc)
		fmt.Fprintf(&builder, "| `%s` | %s |\n", optionConst, detection)
	}

	builder.WriteString("| `FilterAll` | Enables all of the above |\n")

	return builder.String()
}

// generateGeneratorsMDX updates the detection table and tool count in generators.mdx
// between gendocs marker comments. MDX uses {/* */} comment syntax.
func generateGeneratorsMDX(docs []gogenfilter.DetectorDoc) error {
	content, err := os.ReadFile(generatorsMDXPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", generatorsMDXPath, err)
	}

	table := generateMDXTable(docs)
	count := strconv.Itoa(len(docs))

	updated := replaceSection(string(content), mdxTableStartMarker, mdxTableEndMarker, table)
	updated = replaceSectionInline(updated, mdxCountStartMarker, mdxCountEndMarker, count)

	return writeFile(generatorsMDXPath, []byte(updated))
}

// generateDetectionMDX updates the per-generator function table in detection.mdx
// between gendocs marker comments.
func generateDetectionMDX(docs []gogenfilter.DetectorDoc) error {
	content, err := os.ReadFile(detectionMDXPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", detectionMDXPath, err)
	}

	table := generatePerGeneratorTable(docs)
	updated := replaceSection(string(content), mdxPerGenStartMarker, mdxPerGenEndMarker, table)

	return writeFile(detectionMDXPath, []byte(updated))
}

// generatePerGeneratorTable produces the | Function | Checks | table for detection.mdx.
func generatePerGeneratorTable(docs []gogenfilter.DetectorDoc) string {
	var builder strings.Builder

	builder.WriteString(
		"| Function                     | Checks                                              |\n",
	)
	builder.WriteString(
		"| ---------------------------- | --------------------------------------------------- |\n",
	)

	for _, doc := range docs {
		funcName := "`" + doc.IsFuncName + "`"
		checks := perGeneratorChecks(doc)
		padFunc := padRight(funcName, detectionFuncWidth)
		fmt.Fprintf(&builder, "| %s | %s |\n", padFunc, checks)
	}

	return builder.String()
}

// perGeneratorChecks produces a human-readable description of what each
// Is*Generated function checks, based on filename and content phase flags.
func perGeneratorChecks(doc gogenfilter.DetectorDoc) string {
	if doc.Option == gogenfilter.FilterGeneric {
		return "Any `Code generated by` comment"
	}

	if doc.HasFilenamePhase && doc.HasContentPhase {
		return doc.FilenameDetection + " + content"
	}

	if doc.HasContentPhase {
		return "Content marker (" + string(doc.Reason) + ")"
	}

	return doc.FilenameDetection
}

// generateDocGo updates the generator list in doc.go between gendocs marker comments.
// Each line must be prefixed with "// " to remain valid Go comment syntax.
func generateDocGo(docs []gogenfilter.DetectorDoc) error {
	content, err := os.ReadFile(docGoPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", docGoPath, err)
	}

	list := generateDocGoList(docs)
	updated := replaceSection(string(content), docGoListStartMarker, docGoListEndMarker, list)

	return writeFile(docGoPath, []byte(updated))
}

// generateDocGoList produces the comma-separated generator list for doc.go.
// The generic detector is listed as "any tool using the standard 'Code generated by' comment convention".
func generateDocGoList(docs []gogenfilter.DetectorDoc) string {
	names := make([]string, 0, len(docs))

	for _, doc := range docs {
		if doc.Option == gogenfilter.FilterGeneric {
			names = append(names, genericSuffix)
		} else {
			names = append(names, string(doc.Reason))
		}
	}

	list := strings.Join(names, ", ")

	return "// " + list + "\n"
}

// generateMDXTable produces the full detection table for generators.mdx.
func generateMDXTable(docs []gogenfilter.DetectorDoc) string {
	var builder strings.Builder

	builder.WriteString(
		"| Tool                 | Filename Detection                                                | Content Detection                                             |\n",
	)
	builder.WriteString(
		"| -------------------- | ----------------------------------------------------------------- | ------------------------------------------------------------- |\n",
	)

	for _, doc := range docs {
		name := displayName(string(doc.Reason))
		boldName := "**" + name + "**"
		padName := padRight(boldName, mdxNameWidth)
		padFilename := padRight(doc.FilenameDetection, mdxFilenameWidth)
		fmt.Fprintf(&builder, "| %s | %s | %s |\n", padName, padFilename, doc.ContentDetection)
	}

	return builder.String()
}

// readmeDetection produces a short human-readable detection description for README tables.
// The Generic detector gets special treatment because its description is not derivable
// from the filename/content phase flags alone.
func readmeDetection(doc gogenfilter.DetectorDoc) string {
	if doc.Option == gogenfilter.FilterGeneric {
		return "Any `// Code generated by` comment"
	}

	if doc.HasFilenamePhase && doc.HasContentPhase {
		return doc.FilenameDetection + " + content"
	}

	if doc.HasContentPhase {
		return "Content marker"
	}

	return doc.FilenameDetection
}

// displayName converts a reason string to a display name for the README.
// "generic" becomes "Generic fallback".
func displayName(reason string) string {
	if reason == "generic" {
		return "Generic fallback"
	}

	return reason
}

// optionToConstName converts a FilterOption value to its constant name.
// e.g., "sqlc" -> "FilterSQLC", "go-enum" -> "FilterGoEnum".
func optionToConstName(option string) string {
	special := map[string]string{
		"sqlc":         "FilterSQLC",
		"oapi-codegen": "FilterOapi",
		"deepcopy-gen": "FilterDeepcopy",
		"go-enum":      "FilterGoEnum",
		"go-swagger":   "FilterGoSwagger",
	}

	name, ok := special[option]
	if ok {
		return name
	}

	parts := strings.Split(option, "-")
	for i, part := range parts {
		if part != "" {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}

	return "Filter" + strings.Join(parts, "")
}

// padRight pads a string to the given width with spaces.
func padRight(text string, width int) string {
	if len(text) >= width {
		return text
	}

	return text + strings.Repeat(" ", width-len(text))
}

// replaceSection replaces content between marker comments in a file.
// startMarker and endMarker are the exact strings to search for.
// If markers don't exist, returns the original content unchanged.
// Adds a newline after the start marker and before the replacement.
func replaceSection(content, startMarker, endMarker, replacement string) string {
	startIdx := strings.Index(content, startMarker)
	if startIdx == -1 {
		return content
	}

	endIdx := strings.Index(content, endMarker)
	if endIdx == -1 {
		return content
	}

	if endIdx < startIdx {
		return content
	}

	before := content[:startIdx+len(startMarker)]
	after := content[endIdx:]

	return before + "\n" + replacement + after
}

// replaceSectionInline replaces content between markers without adding newlines.
// Used for inline markers that appear mid-line (e.g., the tool count in generators.mdx).
func replaceSectionInline(content, startMarker, endMarker, replacement string) string {
	startIdx := strings.Index(content, startMarker)
	if startIdx == -1 {
		return content
	}

	endIdx := strings.Index(content, endMarker)
	if endIdx == -1 {
		return content
	}

	if endIdx < startIdx {
		return content
	}

	before := content[:startIdx+len(startMarker)]
	after := content[endIdx:]

	return before + replacement + after
}

// writeFile is a wrapper around os.WriteFile for consistent error wrapping.
func writeFile(path string, data []byte) error {
	err := os.WriteFile(path, data, filePerm) //nolint:gosec // build-time tool writes known paths
	if err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	return nil
}
