package main

import (
	"strings"
	"testing"

	"github.com/LarsArtmann/gogenfilter/v3"
)

func TestValidateMetadataAllPresent(t *testing.T) {
	t.Parallel()

	docs := gogenfilter.AllDetectorDocs()

	err := validateMetadata(docs)
	if err != nil {
		t.Fatalf("validateMetadata() failed for all detectors: %v", err)
	}
}

func TestValidateMetadataMissingEntry(t *testing.T) {
	t.Parallel()

	docs := gogenfilter.AllDetectorDocs()
	docs = append(docs, gogenfilter.DetectorDoc{ //nolint:exhaustruct
		Option:     "nonexistent",
		Reason:     "nonexistent",
		IsFuncName: "IsNonexistentGenerated",
	})

	err := validateMetadata(docs)
	if err == nil {
		t.Fatal("validateMetadata() should fail for missing website metadata")
	}

	if !strings.Contains(err.Error(), "nonexistent") {
		t.Errorf("validateMetadata() error should mention the missing detector, got: %v", err)
	}
}

func TestGenerateReadmeGeneratorsTable(t *testing.T) {
	t.Parallel()

	docs := gogenfilter.AllDetectorDocs()

	table := generateReadmeGeneratorsTable(docs)

	if !strings.Contains(table, "sqlc") {
		t.Error("generateReadmeGeneratorsTable() should contain 'sqlc'")
	}

	if !strings.Contains(table, "Generic fallback") {
		t.Error("generateReadmeGeneratorsTable() should contain 'Generic fallback'")
	}

	lines := strings.Split(strings.TrimSpace(table), "\n")
	expectedRows := len(docs) + 2 // header + separator + data rows

	if len(lines) != expectedRows {
		t.Errorf(
			"generateReadmeGeneratorsTable() should have %d lines, got %d",
			expectedRows, len(lines),
		)
	}
}

func TestGenerateReadmeFilterOptionsTable(t *testing.T) {
	t.Parallel()

	docs := gogenfilter.AllDetectorDocs()

	table := generateReadmeFilterOptionsTable(docs)

	if !strings.Contains(table, "FilterAll") {
		t.Error("generateReadmeFilterOptionsTable() should contain 'FilterAll'")
	}

	if !strings.Contains(table, "FilterSQLC") {
		t.Error("generateReadmeFilterOptionsTable() should contain 'FilterSQLC'")
	}

	lines := strings.Split(strings.TrimSpace(table), "\n")
	expectedRows := len(docs) + 3 // header + separator + data rows + FilterAll row

	if len(lines) != expectedRows {
		t.Errorf(
			"generateReadmeFilterOptionsTable() should have %d lines, got %d",
			expectedRows, len(lines),
		)
	}
}

func TestGenerateMDXTable(t *testing.T) {
	t.Parallel()

	docs := gogenfilter.AllDetectorDocs()

	table := generateMDXTable(docs)

	if !strings.Contains(table, "**sqlc**") {
		t.Error("generateMDXTable() should contain '**sqlc**'")
	}

	if !strings.Contains(table, "**Generic fallback**") {
		t.Error("generateMDXTable() should contain '**Generic fallback**'")
	}

	lines := strings.Split(strings.TrimSpace(table), "\n")
	expectedRows := len(docs) + 2 // header + separator + data rows

	if len(lines) != expectedRows {
		t.Errorf(
			"generateMDXTable() should have %d lines, got %d",
			expectedRows, len(lines),
		)
	}
}

func TestGeneratePerGeneratorTable(t *testing.T) {
	t.Parallel()

	docs := gogenfilter.AllDetectorDocs()

	table := generatePerGeneratorTable(docs)

	if !strings.Contains(table, "`IsSQLCGenerated`") {
		t.Error("generatePerGeneratorTable() should contain IsSQLCGenerated")
	}

	if !strings.Contains(table, "`IsGenericGenerated`") {
		t.Error("generatePerGeneratorTable() should contain IsGenericGenerated")
	}

	lines := strings.Split(strings.TrimSpace(table), "\n")
	expectedRows := len(docs) + 2 // header + separator + data rows

	if len(lines) != expectedRows {
		t.Errorf(
			"generatePerGeneratorTable() should have %d lines, got %d",
			expectedRows, len(lines),
		)
	}
}

func TestPerGeneratorChecksGeneric(t *testing.T) {
	t.Parallel()

	doc := gogenfilter.DetectorDoc{ //nolint:exhaustruct // test only needs Option + HasContentPhase
		Option:          gogenfilter.FilterGeneric,
		HasContentPhase: true,
	}

	got := perGeneratorChecks(doc)
	expected := "Any `Code generated by` comment"

	if got != expected {
		t.Errorf("perGeneratorChecks() for Generic = %q, want %q", got, expected)
	}
}

func TestPerGeneratorChecksFilenameAndContent(t *testing.T) {
	t.Parallel()

	doc := gogenfilter.DetectorDoc{ //nolint:exhaustruct // test only needs relevant fields
		Option:            gogenfilter.FilterSQLC,
		Reason:            gogenfilter.ReasonSQLC,
		FilenameDetection: "`*.sql.go` suffix",
		HasFilenamePhase:  true,
		HasContentPhase:   true,
	}

	got := perGeneratorChecks(doc)
	expected := "`*.sql.go` suffix + content"

	if got != expected {
		t.Errorf("perGeneratorChecks() for SQLC = %q, want %q", got, expected)
	}
}

func TestPerGeneratorChecksContentOnly(t *testing.T) {
	t.Parallel()

	doc := gogenfilter.DetectorDoc{ //nolint:exhaustruct // test only needs relevant fields
		Option:          gogenfilter.FilterOapi,
		Reason:          gogenfilter.ReasonOapi,
		HasContentPhase: true,
	}

	got := perGeneratorChecks(doc)
	expected := "Content marker (oapi-codegen)"

	if got != expected {
		t.Errorf("perGeneratorChecks() for Oapi = %q, want %q", got, expected)
	}
}

func TestGenerateDocGoList(t *testing.T) {
	t.Parallel()

	docs := gogenfilter.AllDetectorDocs()

	list := generateDocGoList(docs)

	if !strings.HasPrefix(list, "// ") {
		t.Error("generateDocGoList() should start with '// '")
	}

	if !strings.Contains(list, "sqlc") {
		t.Error("generateDocGoList() should contain 'sqlc'")
	}

	if !strings.Contains(list, "standard \"Code generated by\" comment convention") {
		t.Error("generateDocGoList() should contain the generic suffix text")
	}

	if !strings.HasSuffix(list, "\n") {
		t.Error("generateDocGoList() should end with newline")
	}
}

func TestReplaceSection(t *testing.T) {
	t.Parallel()

	content := "before\n<!-- start -->\nold content\n<!-- end -->\nafter"

	got := replaceSection(content, "<!-- start -->", "<!-- end -->", "new content")

	expected := "before\n<!-- start -->\nnew content<!-- end -->\nafter"

	if got != expected {
		t.Errorf("replaceSection() = %q, want %q", got, expected)
	}
}

func TestReplaceSectionNoMarkers(t *testing.T) {
	t.Parallel()

	content := "no markers here"

	got := replaceSection(content, "<!-- start -->", "<!-- end -->", "new content")

	if got != content {
		t.Error("replaceSection() should return original when markers are missing")
	}
}

func TestReplaceSectionInline(t *testing.T) {
	t.Parallel()

	content := "text {/* start */}old{/* end */} more text"

	got := replaceSectionInline(content, "{/* start */}", "{/* end */}", "42")

	expected := "text {/* start */}42{/* end */} more text"

	if got != expected {
		t.Errorf("replaceSectionInline() = %q, want %q", got, expected)
	}
}

func TestReplaceSectionInlineNoMarkers(t *testing.T) {
	t.Parallel()

	content := "no markers here"

	got := replaceSectionInline(content, "{/* start */}", "{/* end */}", "42")

	if got != content {
		t.Error("replaceSectionInline() should return original when markers are missing")
	}
}

func TestOptionToConstName(t *testing.T) {
	t.Parallel()

	//nolint:goconst // test data, not production constants
	tests := []struct {
		option string
		want   string
	}{
		{"sqlc", "FilterSQLC"},
		{"oapi-codegen", "FilterOapi"},
		{"deepcopy-gen", "FilterDeepcopy"},
		{"go-enum", "FilterGoEnum"},
		{"go-swagger", "FilterGoSwagger"},
		{"templ", "FilterTempl"},
		{"wire", "FilterWire"},
		{"generic", "FilterGeneric"},
	}

	for _, testCase := range tests {
		t.Run(testCase.option, func(t *testing.T) {
			t.Parallel()

			got := optionToConstName(testCase.option)
			if got != testCase.want {
				t.Errorf("optionToConstName(%q) = %q, want %q", testCase.option, got, testCase.want)
			}
		})
	}
}

func TestDisplayName(t *testing.T) {
	t.Parallel()

	if got := displayName("generic"); got != "Generic fallback" {
		t.Errorf("displayName(\"generic\") = %q, want \"Generic fallback\"", got)
	}

	if got := displayName("sqlc"); got != "sqlc" {
		t.Errorf("displayName(\"sqlc\") = %q, want \"sqlc\"", got)
	}
}

func TestPadRight(t *testing.T) {
	t.Parallel()

	if got := padRight("ab", 5); got != "ab   " {
		t.Errorf("padRight(\"ab\", 5) = %q, want \"ab   \"", got)
	}

	if got := padRight("abcdef", 3); got != "abcdef" {
		t.Errorf("padRight(\"abcdef\", 3) = %q, want \"abcdef\"", got)
	}
}
