version: "2"

linters:
  default: none

  enable:
    - depguard
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - gochecknoinits
    - paralleltest
    - tparallel
    - varnamelen
    - funlen
    - exhaustruct
    - gochecknoglobals
    - noinlineerr

linters-settings:
  depguard:
    rules:
      Main:
        allow:
          - $gostd
          - $gopkg
          - golang.org
          - github.com/LarsArtmann/gogenfilter/pkg/errors
          - github.com/go-faster/yaml
  funlen:
    lines: 80
    statements: 60
  varnamelen:
    min-name-length: 2
    ignore-type-asserts: true
    ignore-map-index: true
    ignore-names:
      - f
      - t
      - i
      - j
      - k
      - e
      - fn
      - tt
      - tc
      - id
      - db
      - mx
      - my
  exhaustruct:
    exclude:
      - exfiltrated
  revive:
    rules:
      - name: var-naming
        disabled: true
  gochecknoglobals:
    check: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - funlen
        - gochecknoglobals
        - exhaustruct
        - varnamelen
