package gogenfilter_test

import (
	"errors"
	"fmt"
	"io"
	"testing"

	"github.com/LarsArtmann/gogenfilter"
	ginkgo "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

func TestGogenfilterBDD(t *testing.T) {
	t.Parallel()
	ginkgo.RegisterFailHandler(ginkgo.Fail)
	ginkgo.RunSpecs(t, "gogenfilter BDD Suite")
}

var _ = ginkgo.Describe("gogenfilter", func() {
	ginkgo.Describe("Filter creation", func() {
		ginkgo.When("created with Enabled and FilterAll", func() {
			var filter *gogenfilter.Filter

			ginkgo.BeforeEach(func() {
				filter = gogenfilter.NewFilter(
					gogenfilter.Enabled(),
					gogenfilter.WithFilterOptions(gogenfilter.FilterAll),
				)
			})

			ginkgo.It("is enabled", func() {
				Expect(filter.IsEnabled()).To(BeTrue())
			})

			ginkgo.It("returns all filter reasons", func() {
				reasons := filter.FilterReasons()
				Expect(reasons).To(HaveLen(11))
			})
		})

		ginkgo.When("created with Disabled", func() {
			var filter *gogenfilter.Filter

			ginkgo.BeforeEach(func() {
				filter = gogenfilter.NewFilter(gogenfilter.Disabled())
			})

			ginkgo.It("is not enabled", func() {
				Expect(filter.IsEnabled()).To(BeFalse())
			})

			ginkgo.It("never filters any file", func() {
				filtered, err := filter.ShouldFilter("db/models.go")
				Expect(err).NotTo(HaveOccurred())
				Expect(filtered).To(BeFalse())
			})
		})

		ginkgo.When("created with selective generators", func() {
			var filter *gogenfilter.Filter

			ginkgo.BeforeEach(func() {
				filter = gogenfilter.NewFilter(
					gogenfilter.Enabled(),
					gogenfilter.WithFilterOptions(
						gogenfilter.FilterSQLC,
						gogenfilter.FilterTempl,
					),
				)
			})

			ginkgo.It("returns only selected reasons", func() {
				reasons := filter.FilterReasons()
				Expect(reasons).To(HaveLen(2))
			})
		})

		ginkgo.When("given an invalid FilterOption", func() {
			ginkgo.It("panics", func() {
				Expect(func() {
					gogenfilter.NewFilter(
						gogenfilter.Enabled(),
						gogenfilter.WithFilterOptions(gogenfilter.FilterOption("nonexistent")),
					)
				}).To(Panic())
			})
		})
	})

	ginkgo.Describe("Detecting generated code", func() {
		ginkgo.DescribeTable("detects each generator by content",
			func(path, content string, expectedReason gogenfilter.FilterReason) {
				reason := gogenfilter.DetectReason(path, content, gogenfilter.FilterAll)
				Expect(reason).To(Equal(expectedReason))
			},
			ginkgo.Entry("sqlc", "db/models.go",
				"// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
				gogenfilter.ReasonSQLC),
			ginkgo.Entry(
				"templ",
				"page_templ.go",
				"package components\nimport \"github.com/a-h/templ\"\nfunc Page() templ.Component { return nil }\n",
				gogenfilter.ReasonTempl,
			),
			ginkgo.Entry("go-enum", "status_enum.go",
				"// Code generated by go-enum DO NOT EDIT.\npackage enums\n",
				gogenfilter.ReasonGoEnum),
			ginkgo.Entry("protobuf", "user.pb.go",
				"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
				gogenfilter.ReasonProtobuf),
			ginkgo.Entry("mockgen", "service_mock.go",
				"// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n",
				gogenfilter.ReasonMockgen),
			ginkgo.Entry("stringer", "status_string.go",
				"// Code generated by \"stringer\". DO NOT EDIT.\npackage enums\n",
				gogenfilter.ReasonStringer),
			ginkgo.Entry("generic fallback", "custom_gen.go",
				"// Code generated by my-tool. DO NOT EDIT.\npackage main\n",
				gogenfilter.ReasonGeneric),
		)

		ginkgo.When("content has no generated markers", func() {
			ginkgo.It("returns ReasonNotFiltered", func() {
				reason := gogenfilter.DetectReason(
					"main.go",
					"package main\n",
					gogenfilter.FilterAll,
				)
				Expect(reason).To(Equal(gogenfilter.ReasonNotFiltered))
			})
		})

		ginkgo.When("specific detector is enabled but generic is not", func() {
			ginkgo.It("only detects that specific generator", func() {
				reason := gogenfilter.DetectReason(
					"db/models.go",
					"// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
					gogenfilter.FilterSQLC,
				)
				Expect(reason).To(Equal(gogenfilter.ReasonSQLC))
			})

			ginkgo.It("does not detect other generators", func() {
				reason := gogenfilter.DetectReason(
					"custom_gen.go",
					"// Code generated by my-tool. DO NOT EDIT.\npackage main\n",
					gogenfilter.FilterSQLC,
				)
				Expect(reason).To(Equal(gogenfilter.ReasonNotFiltered))
			})
		})

		ginkgo.When("a file matches multiple detectors", func() {
			ginkgo.It("specific detector takes priority over generic", func() {
				reason := gogenfilter.DetectReason(
					"db/models.go",
					"// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
					gogenfilter.FilterAll,
				)
				Expect(reason).To(Equal(gogenfilter.ReasonSQLC))
			})
		})
	})

	ginkgo.Describe("Detecting from io.Reader", func() {
		ginkgo.When("reader contains generated content", func() {
			ginkgo.It("detects the reason", func() {
				content := "// Code generated by sqlc. DO NOT EDIT.\npackage db\n"
				reason, err := gogenfilter.DetectReasonReader(
					"db/models.go",
					stringReader(content),
					gogenfilter.FilterAll,
				)
				Expect(err).NotTo(HaveOccurred())
				Expect(reason).To(Equal(gogenfilter.ReasonSQLC))
			})
		})

		ginkgo.When("reader fails", func() {
			ginkgo.It("propagates the error", func() {
				_, err := gogenfilter.DetectReasonReader(
					"file.go",
					&errorReader{},
					gogenfilter.FilterAll,
				)
				Expect(err).To(HaveOccurred())
			})
		})
	})

	ginkgo.Describe("Pattern matching", func() {
		ginkgo.DescribeTable("matches patterns correctly",
			func(path, pattern string, expected bool) {
				Expect(gogenfilter.MatchPattern(path, pattern)).To(Equal(expected))
			},
			ginkgo.Entry("exact match", "file.go", "file.go", true),
			ginkgo.Entry("wildcard match", "test.go", "*.go", true),
			ginkgo.Entry("wildcard no match", "test.txt", "*.go", false),
			ginkgo.Entry("doublestar matches any depth", "a/b/c/file.go", "**/*.go", true),
			ginkgo.Entry("doublestar prefix", "any/path/file.go", "**/file.go", true),
			ginkgo.Entry("no match", "other/file.go", "vendor/*.go", false),
		)
	})

	ginkgo.Describe("Filter with include patterns", func() {
		ginkgo.When("a file matches include pattern and is generated", func() {
			ginkgo.It("still filters it as generated", func() {
				filter := gogenfilter.NewFilter(
					gogenfilter.Enabled(),
					gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC),
					gogenfilter.WithIncludePatterns("models.go"),
				)
				filtered, err := filter.ShouldFilter("models.go")
				Expect(err).NotTo(HaveOccurred())
				Expect(filtered).To(BeTrue())
			})
		})

		ginkgo.When("a file does not match any include pattern", func() {
			ginkgo.It("filters it with include-pattern reason", func() {
				filter := gogenfilter.NewFilter(
					gogenfilter.Enabled(),
					gogenfilter.WithIncludePatterns("pkg/*.go"),
				)
				filtered, err := filter.ShouldFilter("other/file.go")
				Expect(err).NotTo(HaveOccurred())
				Expect(filtered).To(BeTrue())

				stats := filter.GetStats()
				Expect(stats.FilteredBy(gogenfilter.ReasonIncludePattern)).To(Equal(1))
			})
		})
	})

	ginkgo.Describe("Metrics", func() {
		ginkgo.When("multiple files are checked", func() {
			ginkgo.It("tracks counts per reason", func() {
				filter := gogenfilter.NewFilter(
					gogenfilter.Enabled(),
					gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC, gogenfilter.FilterTempl),
				)
				_, _ = filter.ShouldFilter("db/models.go")
				_, _ = filter.ShouldFilter("page_templ.go")
				_, _ = filter.ShouldFilter("main.go")

				stats := filter.GetStats()
				Expect(stats.TotalFilesChecked).To(BeNumerically(">=", 1))
			})
		})

		ginkgo.When("filter is disabled", func() {
			ginkgo.It("returns zero stats", func() {
				filter := gogenfilter.NewFilter(gogenfilter.Disabled())
				stats := filter.GetStats()
				Expect(stats.TotalFilesChecked).To(Equal(gogenfilter.TotalFilesChecked(0)))
				Expect(stats.TotalFiltered()).To(Equal(0))
			})
		})
	})

	ginkgo.Describe("Type validation", func() {
		ginkgo.DescribeTable("FilterOption validity",
			func(opt gogenfilter.FilterOption, valid bool) {
				Expect(opt.IsValid()).To(Equal(valid))
			},
			ginkgo.Entry("sqlc is valid", gogenfilter.FilterSQLC, true),
			ginkgo.Entry("all is valid", gogenfilter.FilterAll, true),
			ginkgo.Entry("empty is invalid", gogenfilter.FilterOption(""), false),
			ginkgo.Entry("unknown is invalid", gogenfilter.FilterOption("unknown"), false),
		)

		ginkgo.DescribeTable("FilterReason validity",
			func(reason gogenfilter.FilterReason, valid bool) {
				Expect(reason.IsValid()).To(Equal(valid))
			},
			ginkgo.Entry("sqlc reason is valid", gogenfilter.ReasonSQLC, true),
			ginkgo.Entry("not-filtered is valid", gogenfilter.ReasonNotFiltered, true),
			ginkgo.Entry("unknown is invalid", gogenfilter.FilterReason("unknown"), false),
		)
	})

	ginkgo.Describe("Error system", func() {
		ginkgo.When("project root is not found", func() {
			ginkgo.It("returns a ProjectRootError with branded prefix", func() {
				_, err := gogenfilter.FindProjectRoot(
					gogenfilter.StartPath("/nonexistent/path/12345"),
					[]string{"go.mod"},
				)
				Expect(err).To(HaveOccurred())
				Expect(err.Error()).To(ContainSubstring("[gogenfilter:"))
				Expect(err.Code).To(Equal(gogenfilter.CodeProjectRootNotFound))
			})
		})

		ginkgo.When("all error codes are enumerated", func() {
			ginkgo.It("has non-empty help text for each", func() {
				for _, code := range gogenfilter.AllErrorCodes() {
					help := gogenfilter.CodeHelp(code)
					Expect(help).NotTo(BeEmpty(), "CodeHelp(%q) should not be empty", code)
				}
			})
		})
	})
})

type stringReaderImpl struct {
	content string
	offset  int
}

func stringReader(s string) *stringReaderImpl {
	return &stringReaderImpl{content: s, offset: 0}
}

func (r *stringReaderImpl) Read(p []byte) (int, error) {
	if r.offset >= len(r.content) {
		return 0, io.EOF
	}

	n := copy(p, r.content[r.offset:])
	r.offset += n

	return n, nil
}

var errReadFailed = errors.New("read failed")

type errorReader struct{}

func (r *errorReader) Read(_ []byte) (int, error) {
	return 0, fmt.Errorf("%w: read failed", errReadFailed)
}
