package gogenfilter_test

import (
	"errors"
	"io/fs"
	"os"
	"testing/fstest"

	"github.com/LarsArtmann/gogenfilter/v3"
	ginkgo "github.com/onsi/ginkgo/v2"
	gomega "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("gogenfilter extended", func() {
	ginkgo.Describe("Nil config safety", func() {
		ginkgo.It("NewFilter skips nil FilterConfig values", func() {
			filter, err := gogenfilter.NewFilter(nil, nil)
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			gomega.Expect(filter.IsEnabled()).To(gomega.BeFalse())
		})

		ginkgo.It("NewFilter still applies valid configs after nils", func() {
			cfg, err := gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC)
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			filter, err := gogenfilter.NewFilter(nil, cfg, nil)
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			gomega.Expect(filter.IsEnabled()).To(gomega.BeTrue())
		})
	})

	ginkgo.Describe("Detector priority and specificity", func() {
		ginkgo.When("sqlc filename matches but content is not sqlc", func() {
			ginkgo.It("returns ReasonSQLC from filename-based detection", func() {
				reason := gogenfilter.DetectReason(
					"db/models.go",
					"package db\n",
					gogenfilter.FilterAll,
				)
				gomega.Expect(reason).To(gomega.Equal(gogenfilter.ReasonSQLC))
			})
		})

		ginkgo.When("only content-based detector is enabled", func() {
			ginkgo.It("skips filename-only detectors", func() {
				reason := gogenfilter.DetectReason(
					"db/models.go",
					"package db\n",
					gogenfilter.FilterOapi,
				)
				gomega.Expect(reason).To(gomega.Equal(gogenfilter.ReasonNotFiltered))
			})
		})

		ginkgo.When("no detectors match", func() {
			ginkgo.It("returns ReasonNotFiltered", func() {
				reason := gogenfilter.DetectReason(
					"vendor/lib.go",
					"package lib\n// just a regular file\n",
					gogenfilter.FilterAll,
				)
				gomega.Expect(reason).To(gomega.Equal(gogenfilter.ReasonNotFiltered))
			})
		})

		ginkgo.When("multiple detectors enabled but none match", func() {
			ginkgo.It("returns ReasonNotFiltered", func() {
				reason := gogenfilter.DetectReason(
					"utils.go",
					"package utils\n",
					gogenfilter.FilterSQLC,
					gogenfilter.FilterTempl,
					gogenfilter.FilterWire,
				)
				gomega.Expect(reason).To(gomega.Equal(gogenfilter.ReasonNotFiltered))
			})
		})
	})

	ginkgo.Describe("Individual detector behavior", func() {
		ginkgo.DescribeTable("templ requires both filename AND content",
			func(path, content string, expected gogenfilter.FilterReason) {
				reason := gogenfilter.DetectReason(path, content, gogenfilter.FilterAll)
				gomega.Expect(reason).To(gomega.Equal(expected))
			},
			ginkgo.Entry("_templ.go + templ.Component",
				"page_templ.go",
				"package templ\nfunc Page() templ.Component { return nil }\n",
				gogenfilter.ReasonTempl),
			ginkgo.Entry(
				"_templ.go + Render signature",
				"page_templ.go",
				"package templ\nfunc Render(ctx context.Context, w io.Writer) error { return nil }\n",
				gogenfilter.ReasonTempl,
			),
			ginkgo.Entry("_templ.go but no templ content",
				"page_templ.go",
				"package main\n// not templ content\n",
				gogenfilter.ReasonTempl),
			ginkgo.Entry("go-enum: _enum.go + marker",
				"status_enum.go",
				"// Code generated by go-enum DO NOT EDIT.\npackage enums\n",
				gogenfilter.ReasonGoEnum),
			ginkgo.Entry("go-enum: _enum.go but no marker (filename match wins)",
				"status_enum.go",
				"package enums\n",
				gogenfilter.ReasonGoEnum),
			ginkgo.Entry("wire: wire_gen.go + marker",
				"wire_gen.go",
				"// Code generated by Wire. DO NOT EDIT.\npackage main\n",
				gogenfilter.ReasonWire),
			ginkgo.Entry("wire: wire_gen.go but no marker (filename match wins)",
				"wire_gen.go",
				"package main\n",
				gogenfilter.ReasonWire),
			ginkgo.Entry("moq: _moq.go + marker",
				"repo_moq.go",
				"// Code generated by moq; DO NOT EDIT.\npackage mocks\n",
				gogenfilter.ReasonMoq),
			ginkgo.Entry("moq: _moq.go but no marker (filename match wins)",
				"repo_moq.go",
				"package mocks\n",
				gogenfilter.ReasonMoq),
			ginkgo.Entry("mockgen: mock_ prefix + marker",
				"mock_user.go",
				"// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n",
				gogenfilter.ReasonMockgen),
			ginkgo.Entry("mockgen: _mock.go + marker",
				"user_mock.go",
				"// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n",
				gogenfilter.ReasonMockgen),
			ginkgo.Entry("mockgen: _mock.go but no marker (filename match wins)",
				"user_mock.go",
				"package mocks\n",
				gogenfilter.ReasonMockgen),
			ginkgo.Entry("protobuf: .pb.go without code-gen prefix (filename match wins)",
				"user.pb.go",
				"package pb\n// no code gen comment\n",
				gogenfilter.ReasonProtobuf),
			ginkgo.Entry("deepcopy: zz_ prefix + marker",
				"zz_generated.deepcopy.go",
				"// Code generated by deepcopy-gen. DO NOT EDIT.\npackage v1\n",
				gogenfilter.ReasonDeepcopy),
			ginkgo.Entry("deepcopy: zz_ prefix but no marker (filename match wins)",
				"zz_generated.deepcopy.go",
				"package v1\n",
				gogenfilter.ReasonDeepcopy),
			ginkgo.Entry("oapi: content only, no filename",
				"gen_types.go",
				"// Package api Code generated by oapi-codegen; DO NOT EDIT.\npackage api\n",
				gogenfilter.ReasonOapi),
			ginkgo.Entry("stringer: content only, no filename",
				"color_gen.go",
				"// Code generated by \"stringer\" - DO NOT EDIT.\npackage paint\n",
				gogenfilter.ReasonStringer),
		)
	})

	ginkgo.Describe("FindProjectRoot", func() {
		ginkgo.When("called from within a project", func() {
			ginkgo.It("finds the root by walking up", func() {
				root, err := gogenfilter.FindProjectRoot(
					gogenfilter.StartPath("."),
					[]string{"go.mod"},
				)
				gomega.Expect(err).NotTo(gomega.HaveOccurred())
				gomega.Expect(root).NotTo(gomega.BeEmpty())
			})
		})

		ginkgo.When("called from a nonexistent path", func() {
			ginkgo.It("returns ProjectRootError with not-found code", func() {
				_, err := gogenfilter.FindProjectRoot(
					gogenfilter.StartPath("/this/does/not/exist"),
					[]string{"nonexistent_marker_file.txt"},
				)
				gomega.Expect(err).To(gomega.HaveOccurred())
				gomega.Expect(err.Code).To(gomega.Equal(gogenfilter.CodeProjectRootNotFound))
				gomega.Expect(err.ErrorCode()).To(gomega.Equal(gogenfilter.CodeProjectRootNotFound))
			})
		})

		ginkgo.When("ProjectRootError is created", func() {
			ginkgo.It("has branded prefix in Error()", func() {
				_, err := gogenfilter.FindProjectRoot(
					gogenfilter.StartPath("/nonexistent/path"),
					[]string{"marker.txt"},
				)
				gomega.Expect(err).To(gomega.HaveOccurred())
				gomega.Expect(err.Error()).To(gomega.ContainSubstring("[gogenfilter:"))
				gomega.Expect(err.Error()).To(gomega.ContainSubstring("project root not found"))
			})

			ginkgo.It("provides Help() text via Helper interface", func() {
				_, err := gogenfilter.FindProjectRoot(
					gogenfilter.StartPath("/nonexistent/path"),
					[]string{"marker.txt"},
				)
				gomega.Expect(err).To(gomega.HaveOccurred())
				gomega.Expect(err.Help()).NotTo(gomega.BeEmpty())
			})
		})
	})

	ginkgo.Describe("FilterConfigError detail", func() {
		ginkgo.It("formats branded error message without cause", func() {
			err := &gogenfilter.FilterConfigError{ //nolint:exhaustruct
				Code:   gogenfilter.CodeInvalidFilterOption,
				Option: gogenfilter.FilterSQLC,
			}
			gomega.Expect(err.Error()).To(gomega.ContainSubstring("[gogenfilter:"))
			gomega.Expect(err.Error()).To(gomega.ContainSubstring("invalid_filter_option"))
		})

		ginkgo.It("formats with cause", func() {
			err := &gogenfilter.FilterConfigError{
				Code:   gogenfilter.CodeInvalidFilterOption,
				Option: gogenfilter.FilterSQLC,
				Err:    os.ErrInvalid,
			}
			gomega.Expect(err.Error()).To(gomega.ContainSubstring("invalid argument"))
		})

		ginkgo.It("Is matches same error code", func() {
			err := &gogenfilter.FilterConfigError{ //nolint:exhaustruct
				Code: gogenfilter.CodeInvalidFilterOption,
			}
			target := &gogenfilter.FilterConfigError{ //nolint:exhaustruct
				Code: gogenfilter.CodeInvalidFilterOption,
			}
			gomega.Expect(errors.Is(err, target)).To(gomega.BeTrue())
		})

		ginkgo.It("Is does not match different error code", func() {
			err := &gogenfilter.FilterConfigError{ //nolint:exhaustruct
				Code: gogenfilter.CodeInvalidFilterOption,
			}
			target := &gogenfilter.FilterConfigError{ //nolint:exhaustruct
				Code: gogenfilter.CodeSQLCConfigRead,
			}
			gomega.Expect(errors.Is(err, target)).To(gomega.BeFalse())
		})
	})

	ginkgo.Describe("SQLCConfigError detail", func() {
		ginkgo.It("formats with config path and cause", func() {
			err := &gogenfilter.SQLCConfigError{
				Code:       gogenfilter.CodeSQLCConfigParse,
				ConfigPath: gogenfilter.ConfigPath("sqlc.yaml"),
				Operation:  gogenfilter.Operation("parse"),
				Message:    gogenfilter.ErrorMessage("invalid YAML"),
				Err:        os.ErrInvalid,
			}
			gomega.Expect(err.Error()).To(gomega.ContainSubstring("sqlc.yaml"))
			gomega.Expect(err.Error()).To(gomega.ContainSubstring("invalid YAML"))
		})

		ginkgo.It("formats with operation and message only (no path)", func() {
			err := &gogenfilter.SQLCConfigError{ //nolint:exhaustruct
				Code:      gogenfilter.CodeSQLCConfigRead,
				Operation: gogenfilter.Operation("read"),
				Message:   gogenfilter.ErrorMessage("file missing"),
			}
			gomega.Expect(err.Error()).To(gomega.ContainSubstring("sqlc_config_read"))
			gomega.Expect(err.Error()).To(gomega.ContainSubstring("file missing"))
		})

		ginkgo.It("formats with cause (no path)", func() {
			err := &gogenfilter.SQLCConfigError{ //nolint:exhaustruct
				Code:      gogenfilter.CodeSQLCConfigParse,
				Operation: gogenfilter.Operation("parse"),
				Message:   gogenfilter.ErrorMessage("bad yaml"),
				Err:       os.ErrInvalid,
			}
			gomega.Expect(err.Error()).To(gomega.ContainSubstring("bad yaml"))
		})
	})

	ginkgo.Describe("CodeEqual", func() {
		ginkgo.It("returns true for matching error codes", func() {
			errSame1 := &gogenfilter.FilterConfigError{ //nolint:exhaustruct
				Code: gogenfilter.CodeInvalidFilterOption,
			}
			errSame2 := &gogenfilter.FilterConfigError{ //nolint:exhaustruct
				Code: gogenfilter.CodeInvalidFilterOption,
			}
			gomega.Expect(gogenfilter.CodeEqual(errSame1, errSame2)).To(gomega.BeTrue())
		})

		ginkgo.It("returns false for different error codes", func() {
			errDiff1 := &gogenfilter.FilterConfigError{ //nolint:exhaustruct
				Code: gogenfilter.CodeInvalidFilterOption,
			}
			errDiff2 := &gogenfilter.FilterConfigError{ //nolint:exhaustruct
				Code: gogenfilter.CodeSQLCConfigRead,
			}
			gomega.Expect(gogenfilter.CodeEqual(errDiff1, errDiff2)).To(gomega.BeFalse())
		})
	})

	ginkgo.Describe("Pattern matching edge cases", func() {
		ginkgo.DescribeTable("absolute paths with relative patterns",
			func(path, pattern string, expected bool) {
				gomega.Expect(gogenfilter.MatchPattern(path, pattern)).To(gomega.Equal(expected))
			},
			ginkgo.Entry("absolute path with relative pattern",
				"/home/user/project/file.go", "file.go", true),
			ginkgo.Entry("absolute path with doublestar",
				"/home/user/project/src/file.go", "**/file.go", true),
			ginkgo.Entry("absolute path with directory pattern",
				"/home/user/project/src/file.go", "src/*.go", true),
		)
	})

	ginkgo.Describe("Filter string and statistics detail", func() {
		ginkgo.When("enabled with multiple options and excludes", func() {
			ginkgo.It("String shows options and excludes", func() {
				cfg1, err := gogenfilter.WithFilterOptions(
					gogenfilter.FilterSQLC,
					gogenfilter.FilterTempl,
				)
				gomega.Expect(err).NotTo(gomega.HaveOccurred())

				cfg2 := gogenfilter.WithExcludePatterns("vendor/**")
				filter, err := gogenfilter.NewFilter(cfg1, cfg2)
				gomega.Expect(err).NotTo(gomega.HaveOccurred())

				s := filter.String()
				gomega.Expect(s).To(gomega.ContainSubstring("options="))
				gomega.Expect(s).To(gomega.ContainSubstring("excludes="))
			})
		})

		ginkgo.When("disabled", func() {
			ginkgo.It("String returns Filter(disabled)", func() {
				filter, err := gogenfilter.NewFilter()
				gomega.Expect(err).NotTo(gomega.HaveOccurred())
				gomega.Expect(filter.String()).To(gomega.Equal("Filter(disabled)"))
			})
		})
	})

	ginkgo.Describe("Combined include and exclude patterns", func() {
		ginkgo.When("include matches", func() {
			ginkgo.It("proceeds to detection", func() {
				opts, err := gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC)
				gomega.Expect(err).NotTo(gomega.HaveOccurred())
				filter, err := gogenfilter.NewFilter(
					opts,
					gogenfilter.WithIncludePatterns("**/*.go"),
					gogenfilter.WithExcludePatterns("**/test_*.go"),
				)
				gomega.Expect(err).NotTo(gomega.HaveOccurred())
				filtered, err := filter.Filter("testdata/sqlc/models.go")
				gomega.Expect(err).NotTo(gomega.HaveOccurred())
				gomega.Expect(filtered).To(gomega.BeTrue())
			})
		})

		ginkgo.When("file matches neither", func() {
			ginkgo.It("gets outside-scope", func() {
				filter, err := gogenfilter.NewFilter(
					gogenfilter.WithIncludePatterns("src/**/*.go"),
				)
				gomega.Expect(err).NotTo(gomega.HaveOccurred())
				filtered, err := filter.Filter("lib/util.go")
				gomega.Expect(err).NotTo(gomega.HaveOccurred())
				gomega.Expect(filtered).To(gomega.BeTrue())
			})
		})
	})

	ginkgo.Describe("Multiple exclude patterns", func() {
		ginkgo.It("any matching exclude pattern filters the file", func() {
			opts, err := gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC)
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			filter, err := gogenfilter.NewFilter(
				opts,
				gogenfilter.WithExcludePatterns("**/vendor/**", "**/testdata/**"),
			)
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			filtered, err := filter.Filter("vendor/pkg/file.go")
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			gomega.Expect(filtered).To(gomega.BeTrue())
		})
	})

	ginkgo.Describe("DetectReason with no options", func() {
		ginkgo.It("always returns ReasonNotFiltered", func() {
			reason := gogenfilter.DetectReason(
				"db/models.go",
				"// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
			)
			gomega.Expect(reason).To(gomega.Equal(gogenfilter.ReasonNotFiltered))
		})
	})

	ginkgo.Describe("Options and reasons enumeration", func() {
		ginkgo.It("AllFilterOptions includes all known options", func() {
			opts := gogenfilter.AllFilterOptions()
			gomega.Expect(opts).To(gomega.ContainElement(gogenfilter.FilterAll))
			gomega.Expect(opts).To(gomega.ContainElement(gogenfilter.FilterGeneric))
			gomega.Expect(opts).To(gomega.ContainElement(gogenfilter.FilterSQLC))
			gomega.Expect(len(opts)).To(gomega.BeNumerically(">=", 12))
		})

		ginkgo.It("AllFilterReasons includes all known reasons", func() {
			reasons := gogenfilter.AllFilterReasons()
			gomega.Expect(reasons).To(gomega.ContainElement(gogenfilter.ReasonNotFiltered))
			gomega.Expect(reasons).To(gomega.ContainElement(gogenfilter.ReasonOutsideScope))
			gomega.Expect(reasons).To(gomega.ContainElement(gogenfilter.ReasonExcludePattern))
			gomega.Expect(len(reasons)).To(gomega.BeNumerically(">=", 14))
		})

		ginkgo.It("FilterOption.Reason() maps to matching FilterReason", func() {
			reason, found := gogenfilter.FilterGoEnum.Reason()
			gomega.Expect(found).To(gomega.BeTrue())
			gomega.Expect(reason).To(gomega.Equal(gogenfilter.ReasonGoEnum))

			reason, found = gogenfilter.FilterWire.Reason()
			gomega.Expect(found).To(gomega.BeTrue())
			gomega.Expect(reason).To(gomega.Equal(gogenfilter.ReasonWire))

			reason, found = gogenfilter.FilterMoq.Reason()
			gomega.Expect(found).To(gomega.BeTrue())
			gomega.Expect(reason).To(gomega.Equal(gogenfilter.ReasonMoq))

			reason, found = gogenfilter.FilterMockgen.Reason()
			gomega.Expect(found).To(gomega.BeTrue())
			gomega.Expect(reason).To(gomega.Equal(gogenfilter.ReasonMockgen))

			reason, found = gogenfilter.FilterDeepcopy.Reason()
			gomega.Expect(found).To(gomega.BeTrue())
			gomega.Expect(reason).To(gomega.Equal(gogenfilter.ReasonDeepcopy))

			reason, found = gogenfilter.FilterOapi.Reason()
			gomega.Expect(found).To(gomega.BeTrue())
			gomega.Expect(reason).To(gomega.Equal(gogenfilter.ReasonOapi))
		})
	})

	ginkgo.Describe("Custom filesystem comprehensive", func() {
		var (
			fsys   fs.FS
			filter *gogenfilter.Filter
		)

		ginkgo.BeforeEach(func() {
			fsys = fstest.MapFS{
				"db/models.go": {
					Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
				},
				"db/querier.go": {
					Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
				},
				"page_templ.go": {
					Data: []byte(
						"package templ\nimport \"github.com/a-h/templ\"\nfunc Page() templ.Component { return nil }\n",
					),
				},
				"main.go":         {Data: []byte("package main\nfunc main() {}\n")},
				"types.go":        {Data: []byte("package models\ntype User struct{}\n")},
				"vendor/pkg/f.go": {Data: []byte("package pkg\n")},
			}
			cfg, err := gogenfilter.WithFilterOptions(gogenfilter.FilterAll)
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			filter, err = gogenfilter.NewFilter(cfg, gogenfilter.WithFS(fsys))
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
		})

		ginkgo.It("detects sqlc file in custom FS", func() {
			filtered, err := filter.Filter("db/models.go")
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			gomega.Expect(filtered).To(gomega.BeTrue())
		})

		ginkgo.It("detects templ file in custom FS", func() {
			filtered, err := filter.Filter("page_templ.go")
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			gomega.Expect(filtered).To(gomega.BeTrue())
		})

		ginkgo.It("does not filter handwritten files", func() {
			filtered, err := filter.Filter("main.go")
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			gomega.Expect(filtered).To(gomega.BeFalse())
		})

		ginkgo.It("does not filter types.go", func() {
			filtered, err := filter.Filter("types.go")
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			gomega.Expect(filtered).To(gomega.BeFalse())
		})

		ginkgo.It("returns error for nonexistent file", func() {
			_, err := filter.Filter("nonexistent.go")
			gomega.Expect(err).To(gomega.HaveOccurred())
		})
	})

	ginkgo.Describe("SQLC content detection", func() {
		ginkgo.DescribeTable("detects sqlc by various content markers",
			func(path, content string, expected gogenfilter.FilterReason) {
				reason := gogenfilter.DetectReason(path, content, gogenfilter.FilterSQLC)
				gomega.Expect(reason).To(gomega.Equal(expected))
			},
			ginkgo.Entry("standard sqlc header",
				"models.go",
				"// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
				gogenfilter.ReasonSQLC),
			ginkgo.Entry("sqlc.Arg pattern",
				"query.sql.go",
				"package db\nfunc GetUsers(arg sqlc.Arg) {}\n",
				gogenfilter.ReasonSQLC),
			ginkgo.Entry("sqlc.NamedArg pattern",
				"query.sql.go",
				"package db\nfunc GetUsers(arg sqlc.NamedArg) {}\n",
				gogenfilter.ReasonSQLC),
			ginkgo.Entry("query.sql.go suffix",
				"users.sql.go",
				"package db\nfunc GetUsers() {}\n",
				gogenfilter.ReasonSQLC),
			ginkgo.Entry("batch.go filename",
				"batch.go",
				"package db\n// sqlc batch\n",
				gogenfilter.ReasonSQLC),
			ginkgo.Entry("non-sqlc content on sqlc filename (filename match wins)",
				"models.go",
				"package db\n// regular file\n",
				gogenfilter.ReasonSQLC),
		)
	})

	ginkgo.Describe("Enabled state derivation", func() {
		ginkgo.It("include patterns alone enable the filter", func() {
			filter, err := gogenfilter.NewFilter(
				gogenfilter.WithIncludePatterns("**/*.go"),
			)
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			gomega.Expect(filter.IsEnabled()).To(gomega.BeTrue())
		})

		ginkgo.It("exclude patterns alone enable the filter", func() {
			filter, err := gogenfilter.NewFilter(
				gogenfilter.WithExcludePatterns("**/vendor/**"),
			)
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			gomega.Expect(filter.IsEnabled()).To(gomega.BeTrue())
		})

		ginkgo.It("filter options alone enable the filter", func() {
			cfg, err := gogenfilter.WithFilterOptions(gogenfilter.FilterGeneric)
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			filter, err := gogenfilter.NewFilter(cfg)
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			gomega.Expect(filter.IsEnabled()).To(gomega.BeTrue())
		})

		ginkgo.It("no config means disabled", func() {
			filter, err := gogenfilter.NewFilter()
			gomega.Expect(err).NotTo(gomega.HaveOccurred())
			gomega.Expect(filter.IsEnabled()).To(gomega.BeFalse())
		})
	})
})
