package gogenfilter

import (
	"os"
	"path/filepath"
	"strings"
)

// IsSQLCGenerated checks if a file is generated by sqlc.dev.
func IsSQLCGenerated(filePath, content string) bool {
	if !MatchesSQLCFilename(filePath) {
		return false
	}

	return HasSQLCContent(content)
}

// MatchesSQLCFilename checks if filename matches sqlc.dev naming patterns.
func MatchesSQLCFilename(filePath string) bool {
	filename := filepath.Base(filePath)

	for _, pattern := range sqlcFilePatterns {
		if strings.Contains(filename, pattern) {
			return true
		}
	}

	return strings.HasSuffix(filename, ".sql.go")
}

// HasSQLCContent checks if content contains sqlc.dev specific markers.
func HasSQLCContent(content string) bool {
	if strings.Contains(content, "// Code generated by sqlc. DO NOT EDIT.") {
		return true
	}

	if strings.Contains(content, "sqlc ") && strings.Contains(content, "versions:") {
		return true
	}

	return HasSQLCCodePatterns(content)
}

// HasSQLCCodePatterns checks for sqlc-specific code patterns in content.
func HasSQLCCodePatterns(content string) bool {
	patterns := []string{
		"sqlc.Arg",
		"sqlc.NamedArg",
		"sqlc.Literal",
		"sqlc.SliceArg",
		"sqlc.Narg",
		".query(ctx",
	}

	for _, pattern := range patterns {
		if strings.Contains(content, pattern) {
			return true
		}
	}

	return false
}

// IsTemplGenerated checks if a file is generated by templ.guide.
func IsTemplGenerated(filePath, content string) bool {
	filename := filepath.Base(filePath)

	if !strings.HasSuffix(filename, "_templ.go") {
		return false
	}

	if strings.Contains(content, "templ.Component") {
		return true
	}

	if strings.Contains(content, "Render(ctx context.Context, w io.Writer) error") {
		return true
	}

	return false
}

// IsGoEnumGenerated checks if a file is generated by go-enum.
func IsGoEnumGenerated(filePath, content string) bool {
	filename := filepath.Base(filePath)

	if !strings.HasSuffix(filename, "_enum.go") {
		return false
	}

	if strings.Contains(content, "// Code generated by go-enum") {
		return true
	}

	return false
}

// DetectGenerated checks if a file is auto-generated based on filename and optional content.
// If content is empty, it reads the file from disk.
// It returns the reason for filtering, or ReasonNotFiltered if the file is not generated.
func DetectGenerated(filePath string, options map[FilterOption]bool) FilterReason {
	return detectGeneratedReason(filePath, options)
}

// detectGeneratedReason determines if and why a file is auto-generated.
// Two-phase detection: filename-based first (zero I/O), then content-based (reads file).
func detectGeneratedReason(filePath string, options map[FilterOption]bool) FilterReason {
	if reason := getFilenameBasedReason(filePath, options); reason != ReasonNotFiltered {
		return reason
	}

	content, err := os.ReadFile(filePath) //nolint:gosec // filePath is from controlled source
	if err != nil {
		return ReasonNotFiltered
	}

	contentStr := string(content)

	if options[FilterSQLC] && IsSQLCGenerated(filePath, contentStr) {
		return ReasonSQLC
	}

	if options[FilterTempl] && IsTemplGenerated(filePath, contentStr) {
		return ReasonTempl
	}

	if options[FilterGoEnum] && IsGoEnumGenerated(filePath, contentStr) {
		return ReasonGoEnum
	}

	return ReasonNotFiltered
}

// getFilenameBasedReason determines the filter reason based on filename only.
func getFilenameBasedReason(filePath string, options map[FilterOption]bool) FilterReason {
	filename := filepath.Base(filePath)

	if options[FilterSQLC] {
		for _, pattern := range sqlcFilePatterns {
			if strings.Contains(filename, pattern) {
				return ReasonSQLC
			}
		}

		if strings.HasSuffix(filename, ".sql.go") {
			return ReasonSQLC
		}
	}

	if options[FilterTempl] && strings.HasSuffix(filename, "_templ.go") {
		return ReasonTempl
	}

	if options[FilterGoEnum] && strings.HasSuffix(filename, "_enum.go") {
		return ReasonGoEnum
	}

	return ReasonNotFiltered
}
