package gogenfilter //nolint:testpackage // needs access to unexported detectors, optionsMap

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func testDetectReasonNotFiltered(
	t *testing.T,
	filename, content string,
	filterOpts ...FilterOption,
) {
	t.Helper()

	reason := DetectReason(filename, content, filterOpts...)

	if reason != ReasonNotFiltered {
		t.Errorf("Expected %v, got %v", ReasonNotFiltered, reason)
	}
}

func TestIsGenerated(t *testing.T) {
	t.Parallel()

	for _, gen := range generatedTestCases {
		t.Run(gen.name, func(t *testing.T) {
			t.Parallel()

			runGeneratedFileTest(t, gen.tests, gen.fn, "Is"+gen.name+"Generated")
		})
	}
}

func TestNeedsContentCheck(t *testing.T) {
	t.Parallel()

	tests := []boolTestCase[map[FilterOption]struct{}]{
		{
			name:     "empty options",
			input:    map[FilterOption]struct{}{},
			expected: false,
		},
		{
			name:     "only content-based filter",
			input:    map[FilterOption]struct{}{FilterGeneric: {}},
			expected: true,
		},
		{
			name:     "sqlc filter requires content",
			input:    map[FilterOption]struct{}{FilterSQLC: {}},
			expected: true,
		},
	}

	runBoolTableTest(t, tests, needsContentCheck, "needsContentCheck")
}

func TestDetectGenerated(t *testing.T) {
	t.Parallel()

	for _, testCase := range detectGeneratedTestCases() {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			reason := getFilenameBasedReason(testCase.filename, testCase.options)

			if reason != testCase.expected {
				t.Errorf("Expected %v, got %v", testCase.expected, reason)
			}
		})
	}
}

func TestDetectReason(t *testing.T) {
	t.Parallel()

	t.Run("detects generated file from disk", func(t *testing.T) {
		t.Parallel()

		//nolint:goconst // test fixture string, not a production constant
		content := "// Code generated by sqlc. DO NOT EDIT.\npackage db\ntype User struct{}\n"
		tmpFile := createTempFile(t, "models.go", content)

		reason, err := detectReasonFS(
			os.DirFS(filepath.Dir(tmpFile)),
			filepath.Base(tmpFile),
			optionsMap(FilterSQLC),
		)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonSQLC {
			t.Errorf("Expected %v, got %v", ReasonSQLC, reason)
		}
	})

	t.Run("returns not filtered for non-existent file", func(t *testing.T) {
		t.Parallel()

		reason, err := detectReasonFS(
			os.DirFS("."),
			"nonexistent/file.go",
			optionsMap(FilterSQLC),
		)
		if err == nil {
			t.Fatal("expected error for nonexistent file")
		}

		if reason != ReasonNotFiltered {
			t.Errorf("Expected %v, got %v", ReasonNotFiltered, reason)
		}
	})

	t.Run("returns not filtered when no options enabled", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by sqlc. DO NOT EDIT.\npackage db\n"
		tmpFile := createTempFile(t, "models.go", content)

		reason, err := detectReasonFS(
			os.DirFS(filepath.Dir(tmpFile)),
			filepath.Base(tmpFile),
			optionsMap(),
		)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonNotFiltered {
			t.Errorf("Expected %v, got %v", ReasonNotFiltered, reason)
		}
	})
}

func testDetectReason(
	t *testing.T,
	filename, content string,
	expectedReason FilterReason,
	filterOpts ...FilterOption,
) {
	t.Helper()

	reason := DetectReason(filename, content, filterOpts...)

	if reason != expectedReason {
		t.Errorf("Expected %v, got %v", expectedReason, reason)
	}
}

func TestDetectReasonNoIO(t *testing.T) {
	t.Parallel()

	t.Run("detects sqlc from content without I/O", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by sqlc. DO NOT EDIT.\npackage db\ntype User struct{}\n"
		testDetectReason(
			t,
			"models.go",
			content,
			ReasonSQLC,
			FilterSQLC,
		)
	})

	t.Run("detects generic from content without I/O", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by foobar. DO NOT EDIT.\npackage main\n"
		testDetectReason(
			t,
			"foo.go",
			content,
			ReasonGeneric,
			FilterGeneric,
		)
	})

	t.Run("returns not filtered for non-matching content", func(t *testing.T) {
		t.Parallel()
		testDetectReasonNotFiltered(
			t,
			"file.go",
			"package main",
			FilterGeneric,
		)
	})
}

func TestDetectReasonReader(t *testing.T) {
	t.Parallel()

	t.Run("detects sqlc from reader", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by sqlc. DO NOT EDIT.\npackage db\ntype User struct{}\n"

		reason, err := DetectReasonReader("models.go", strings.NewReader(content), FilterAll)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonSQLC {
			t.Errorf("Expected %v, got %v", ReasonSQLC, reason)
		}
	})

	t.Run("returns not filtered for non-generated", func(t *testing.T) {
		t.Parallel()

		reason, err := DetectReasonReader("main.go", strings.NewReader("package main\n"), FilterAll)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonNotFiltered {
			t.Errorf("Expected %v, got %v", ReasonNotFiltered, reason)
		}
	})

	t.Run("propagates reader error", func(t *testing.T) {
		t.Parallel()

		r := &errorReader{}

		_, err := DetectReasonReader("file.go", r, FilterAll)
		if err == nil {
			t.Fatal("Expected error from reader")
		}
	})
}

type errorReader struct{}

func (r *errorReader) Read(_ []byte) (int, error) { return 0, os.ErrNotExist }

type detectorPriorityTest struct {
	name     string
	path     string
	content  string
	expected FilterReason
}

func detectorPriorityTests() []detectorPriorityTest {
	return []detectorPriorityTest{
		{
			name:     "stringer beats generic",
			path:     "status_string.go",
			content:  "// Code generated by \"stringer\". DO NOT EDIT.\npackage enums\n",
			expected: ReasonStringer,
		},
		{
			name:     "sqlc beats generic",
			path:     "db/models.go",
			content:  "// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
			expected: ReasonSQLC,
		},
		{
			name:     "mockgen beats generic",
			path:     "service_mock.go",
			content:  "// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n",
			expected: ReasonMockgen,
		},
		{
			name:     "generic catches unknown tool",
			path:     "custom_gen.go",
			content:  "// Code generated by my-tool. DO NOT EDIT.\npackage main\n",
			expected: ReasonGeneric,
		},
		{
			name:     "go-enum beats generic",
			path:     "status_enum.go",
			content:  "// Code generated by go-enum DO NOT EDIT.\npackage enums\n",
			expected: ReasonGoEnum,
		},
		{
			name:     "protobuf beats generic",
			path:     "user.pb.go",
			content:  "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
			expected: ReasonProtobuf,
		},
	}
}

func TestDetectorPriorityWithFilterAll(t *testing.T) {
	t.Parallel()

	for _, testCase := range detectorPriorityTests() {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			reason := DetectReason(testCase.path, testCase.content, FilterAll)

			assertCallResult(t, "DetectReason", testCase.path, reason, testCase.expected)
		})
	}
}

func TestDetectorOptionReasonConsistency(t *testing.T) {
	t.Parallel()

	for _, det := range detectors {
		if !det.option.IsValid() {
			t.Errorf("detector option %q is not a valid FilterOption", det.option)
		}

		if !det.reason.IsValid() {
			t.Errorf("detector reason %q is not a valid FilterReason", det.reason)
		}

		if det.option.Reason() != det.reason {
			t.Errorf("detector{option=%q}.Reason() = %q, want %q",
				det.option, det.option.Reason(), det.reason)
		}
	}
}

func TestDetectReasonFilenameOnlyNoContentCheck(t *testing.T) {
	t.Parallel()
	testDetectReasonNotFiltered(t, "regular.go", "", FilterTempl)
}

func TestEmptyContent(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		fn   func(string, string) bool
	}{
		{"IsSQLCGenerated", IsSQLCGenerated},
		{"IsTemplGenerated", IsTemplGenerated},
		{"IsGoEnumGenerated", IsGoEnumGenerated},
		{"IsProtobufGenerated", IsProtobufGenerated},
		{"IsMockgenGenerated", IsMockgenGenerated},
		{"IsOapiGenerated", IsOapiGenerated},
		{"IsDeepcopyGenerated", IsDeepcopyGenerated},
		{"IsWireGenerated", IsWireGenerated},
		{"IsMoqGenerated", IsMoqGenerated},
		{"IsStringerGenerated", IsStringerGenerated},
		{"IsGenericGenerated", IsGenericGenerated},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			if tt.fn("file.go", "") {
				t.Errorf("%s with empty content should return false", tt.name)
			}
		})
	}
}

func TestMatchesSQLCFilenameFalsePositives(t *testing.T) {
	t.Parallel()

	tests := []sqlcFilenameTestCase{
		{name: "user_models.go is not sqlc", path: "db/user_models.go", expected: false},
		{name: "myquerier.go is not sqlc", path: "db/myquerier.go", expected: false},
		{name: "batch_processor.go is not sqlc", path: "db/batch_processor.go", expected: false},
	}

	runSQLCFilenameTests(t, tests)
}

func TestMatchesSQLCFilename(t *testing.T) {
	t.Parallel()

	tests := []sqlcFilenameTestCase{
		{name: "models.go", path: "db/models.go", expected: true},
		{name: "querier.go", path: "db/querier.go", expected: true},
		{name: "query.sql.go", path: "db/query.sql.go", expected: true},
		{name: "batch.go", path: "db/batch.go", expected: true},
		{name: "users.sql.go", path: "db/users.sql.go", expected: true},
		{name: "regular file", path: "db/main.go", expected: false},
	}

	runSQLCFilenameTests(t, tests)
}

func sqlcPatternAndContentTests() ([]boolTestCase[string], []boolTestCase[string]) {
	codePatternTests := make([]boolTestCase[string], 0, 4)
	codePatternTests = addBoolTestCase(addBoolTestCase(addBoolTestCase(addBoolTestCase(
		codePatternTests,
		"sqlc.Arg",
		"id := sqlc.Arg(\"user_id\")",
		true,
	), "sqlc.Narg", "id := sqlc.Narg(\"user_id\")", true), "query method", "row := q.query(ctx, sql)", true), "no pattern", "package main\nfunc main() {}", false)

	contentTests := make([]boolTestCase[string], 0, 4)
	contentTests = addBoolTestCase(addBoolTestCase(addBoolTestCase(addBoolTestCase(
		contentTests,
		"code generated comment",
		"// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
		true,
	), "sqlc versions block", "// Code generated by sqlc v1.25.0\n// versions:\npackage db\n", true), "code pattern only", "package db\nid := sqlc.Arg(\"id\")\n", true), "no sqlc markers", "package main\nfunc main() {}\n", false)

	return codePatternTests, contentTests
}

func runSQLCSubTest(t *testing.T, name string, tests []boolTestCase[string], fn func(string) bool) {
	t.Helper()
	t.Run(name, func(t *testing.T) {
		t.Parallel()
		runBoolTableTest(t, tests, fn, name)
	})
}

func TestSQLCDetection(t *testing.T) {
	t.Parallel()

	codePatternTests, contentTests := sqlcPatternAndContentTests()

	runSQLCSubTest(t, "HasSQLCCodePatterns", codePatternTests, HasSQLCCodePatterns)
	runSQLCSubTest(t, "HasSQLCContent", contentTests, HasSQLCContent)
}

func TestOapiDetection(t *testing.T) {
	t.Parallel()

	runGeneratedFileTest(t, []generatedFileTest{
		{
			name:     "oapi-codegen gen.go file",
			filePath: "petstore.gen.go",
			content:  "// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.\npackage petstore\n",
			expected: true,
		},
		{
			name:     "gen.go without oapi marker",
			filePath: "types.gen.go",
			content:  "// Code generated by other-tool. DO NOT EDIT.\npackage main\n",
			expected: false,
		},
	}, IsOapiGenerated, "IsOapiGenerated")
}

func TestDeepcopyDetection(t *testing.T) {
	t.Parallel()

	runGeneratedFileTest(t, []generatedFileTest{
		{
			name:     "deepcopy-gen file",
			filePath: "zz_generated.deepcopy.go",
			content:  "// Code generated by deepcopy-gen. DO NOT EDIT.\npackage v1\n",
			expected: true,
		},
		{
			name:     "zz_generated without deepcopy marker",
			filePath: "zz_generated.other.go",
			content:  "package v1\n",
			expected: false,
		},
	}, IsDeepcopyGenerated, "IsDeepcopyGenerated")
}

func TestWireDetection(t *testing.T) {
	t.Parallel()

	runGeneratedFileTest(t, []generatedFileTest{
		{
			name:     "wire_gen.go file",
			filePath: "wire_gen.go",
			content:  "// Code generated by Wire. DO NOT EDIT.\npackage main\n",
			expected: true,
		},
		{
			name:     "regular file with Wire comment",
			filePath: "main.go",
			content:  "// Code generated by Wire. DO NOT EDIT.\npackage main\n",
			expected: true,
		},
		{
			name:     "wire_gen.go without Wire comment",
			filePath: "wire_gen.go",
			content:  "package main\n",
			expected: false,
		},
	}, IsWireGenerated, "IsWireGenerated")
}

func TestMoqDetection(t *testing.T) {
	t.Parallel()

	runGeneratedFileTest(t, []generatedFileTest{
		{
			name:     "moq file",
			filePath: "service_moq.go",
			content:  "// Code generated by moq; DO NOT EDIT.\npackage service\n",
			expected: true,
		},
		{
			name:     "moq test file",
			filePath: "service_moq_test.go",
			content:  "// Code generated by moq; DO NOT EDIT.\npackage service\n",
			expected: true,
		},
		{
			name:     "regular file with moq comment but wrong suffix",
			filePath: "service.go",
			content:  "// Code generated by moq; DO NOT EDIT.\npackage service\n",
			expected: true,
		},
		{
			name:     "moq file without moq comment",
			filePath: "service_moq.go",
			content:  "package service\n",
			expected: false,
		},
	}, IsMoqGenerated, "IsMoqGenerated")
}
