package gogenfilter

import (
	"os"
	"path/filepath"
	"testing"
	"testing/fstest"
)

func TestDetectReasonFile(t *testing.T) {
	t.Parallel()

	t.Run("filename-only detection skips file read", func(t *testing.T) {
		t.Parallel()

		content := "package main\nfunc main() {}\n"
		tmpFile := createTempFile(t, pageTemplGo, content)

		reason, err := DetectReasonFile(tmpFile, FilterTempl)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonTempl {
			t.Errorf("expected %v, got %v", ReasonTempl, reason)
		}
	})

	t.Run("content-based detection reads file when filename misses", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by \"stringer\". DO NOT EDIT.\npackage enums\n"
		tmpFile := createTempFile(t, "priority.go", content)

		reason, err := DetectReasonFile(tmpFile, FilterStringer)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonStringer {
			t.Errorf("expected %v, got %v", ReasonStringer, reason)
		}
	})

	t.Run("FilterAll expands and detects via content", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by sqlc. DO NOT EDIT.\npackage db\n"
		tmpFile := createTempFile(t, "models.go", content)

		reason, err := DetectReasonFile(tmpFile, FilterAll)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonSQLC {
			t.Errorf("expected %v, got %v", ReasonSQLC, reason)
		}
	})

	t.Run("returns not filtered for regular file", func(t *testing.T) {
		t.Parallel()

		tmpFile := createTempFile(t, mainGo, packageMainFunc)

		reason, err := DetectReasonFile(tmpFile, FilterAll)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonNotFiltered {
			t.Errorf("expected %v, got %v", ReasonNotFiltered, reason)
		}
	})

	t.Run("returns error for nonexistent file", func(t *testing.T) {
		t.Parallel()

		_, err := DetectReasonFile("/nonexistent/path/file.go", FilterAll)
		if err == nil {
			t.Fatal("expected error for nonexistent file")
		}
	})

	t.Run("returns not filtered when no options enabled", func(t *testing.T) {
		t.Parallel()

		content := sqlcGeneratedContentTest
		tmpFile := createTempFile(t, "models.go", content)

		reason, err := DetectReasonFile(tmpFile)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonNotFiltered {
			t.Errorf("expected %v, got %v", ReasonNotFiltered, reason)
		}
	})
}

func TestDetectReasonFileFS(t *testing.T) {
	t.Parallel()

	t.Run("filename-only detection with MapFS", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			pageTemplGo: &fstest.MapFile{
				Data: []byte("package main\nfunc main() {}\n"),
			},
		}

		reason, err := DetectReasonFileFS(fsys, pageTemplGo, FilterTempl)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonTempl {
			t.Errorf("expected %v, got %v", ReasonTempl, reason)
		}
	})

	t.Run("content-based detection with MapFS", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by \"stringer\". DO NOT EDIT.\npackage enums\n"
		fsys := fstest.MapFS{
			"priority.go": &fstest.MapFile{Data: []byte(content)},
		}

		reason, err := DetectReasonFileFS(fsys, "priority.go", FilterStringer)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonStringer {
			t.Errorf("expected %v, got %v", ReasonStringer, reason)
		}
	})

	t.Run("returns not filtered for regular file", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			mainGo: &fstest.MapFile{Data: []byte(packageMainFunc)},
		}

		reason, err := DetectReasonFileFS(fsys, mainGo, FilterAll)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonNotFiltered {
			t.Errorf("expected %v, got %v", ReasonNotFiltered, reason)
		}
	})

	t.Run("returns error for nonexistent file in MapFS", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{}

		_, err := DetectReasonFileFS(fsys, "nonexistent.go", FilterAll)
		if err == nil {
			t.Fatal("expected error for nonexistent file")
		}
	})

	t.Run("detects protobuf via filename with os.DirFS", func(t *testing.T) {
		t.Parallel()

		tmpDir := t.TempDir()
		pbFile := filepath.Join(tmpDir, "user.pb.go")

		err := os.WriteFile(
			pbFile,
			[]byte("// Code generated by protoc. DO NOT EDIT.\npackage pb\n"),
			0o600,
		)
		if err != nil {
			t.Fatalf("failed to create temp file: %v", err)
		}

		reason, err := DetectReasonFileFS(os.DirFS(tmpDir), "user.pb.go", FilterProtobuf)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonProtobuf {
			t.Errorf("expected %v, got %v", ReasonProtobuf, reason)
		}
	})

	t.Run("detects generic via content with MapFS", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by my-custom-tool. DO NOT EDIT.\npackage main\n"
		fsys := fstest.MapFS{
			"custom.go": &fstest.MapFile{Data: []byte(content)},
		}

		reason, err := DetectReasonFileFS(fsys, "custom.go", FilterGeneric)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if reason != ReasonGeneric {
			t.Errorf("expected %v, got %v", ReasonGeneric, reason)
		}
	})
}
