package gogenfilter

import (
	"os"
	"path/filepath"
	"testing"
)

func testDetectReasonNotFiltered(t *testing.T, filename, content string, filterOpts map[FilterOption]bool) {
	reason := DetectReason(filename, content, filterOpts)

	if reason != ReasonNotFiltered {
		t.Errorf("Expected %v, got %v", ReasonNotFiltered, reason)
	}
}

func TestIsGenerated(t *testing.T) {
	t.Parallel()

	for _, gen := range generatedTestCases {
		t.Run(gen.name, func(t *testing.T) {
			t.Parallel()

			runGeneratedFileTest(t, gen.tests, gen.fn, "Is"+gen.name+"Generated")
		})
	}
}

func TestNeedsContentCheck(t *testing.T) {
	t.Parallel()

	tests := []boolTestCase[map[FilterOption]bool]{
		{
			name:     "empty options",
			input:    map[FilterOption]bool{},
			expected: false,
		},
		{
			name:     "only content-based filter",
			input:    map[FilterOption]bool{FilterGeneric: true},
			expected: true,
		},
		{
			name:     "sqlc filter requires content",
			input:    map[FilterOption]bool{FilterSQLC: true},
			expected: true,
		},
		{
			name:     "no filters enabled",
			input:    map[FilterOption]bool{FilterSQLC: false, FilterGeneric: false},
			expected: false,
		},
	}

	runBoolTableTest(t, tests, needsContentCheck, "needsContentCheck")
}

func TestDetectGenerated(t *testing.T) {
	t.Parallel()

	for _, tc := range detectGeneratedTestCases() {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			reason := getFilenameBasedReason(tc.filename, tc.options)

			if reason != tc.expected {
				t.Errorf("Expected %v, got %v", tc.expected, reason)
			}
		})
	}
}

func TestDetectReason(t *testing.T) {
	t.Parallel()

	t.Run("detects generated file from disk", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by sqlc. DO NOT EDIT.\npackage db\ntype User struct{}\n"
		tmpFile := createTempFile(t, "models.go", content)

		reason := detectReason(
			os.DirFS(filepath.Dir(tmpFile)),
			filepath.Base(tmpFile),
			map[FilterOption]bool{FilterSQLC: true},
		)

		if reason != ReasonSQLC {
			t.Errorf("Expected %v, got %v", ReasonSQLC, reason)
		}
	})

	t.Run("returns not filtered for non-existent file", func(t *testing.T) {
		t.Parallel()

		reason := detectReason(
			os.DirFS("."),
			"nonexistent/file.go",
			map[FilterOption]bool{FilterSQLC: true},
		)

		if reason != ReasonNotFiltered {
			t.Errorf("Expected %v, got %v", ReasonNotFiltered, reason)
		}
	})

	t.Run("returns not filtered when no options enabled", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by sqlc. DO NOT EDIT.\npackage db\n"
		tmpFile := createTempFile(t, "models.go", content)

		reason := detectReason(
			os.DirFS(filepath.Dir(tmpFile)),
			filepath.Base(tmpFile),
			map[FilterOption]bool{},
		)

		if reason != ReasonNotFiltered {
			t.Errorf("Expected %v, got %v", ReasonNotFiltered, reason)
		}
	})
}

func testDetectReason(t *testing.T, filename, content string, filterOpts map[FilterOption]bool, expectedReason FilterReason) {
	reason := DetectReason(filename, content, filterOpts)

	if reason != expectedReason {
		t.Errorf("Expected %v, got %v", expectedReason, reason)
	}
}

func TestDetectReasonNoIO(t *testing.T) {
	t.Parallel()

	t.Run("detects sqlc from content without I/O", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by sqlc. DO NOT EDIT.\npackage db\ntype User struct{}\n"
		testDetectReason(t, "models.go", content, map[FilterOption]bool{FilterSQLC: true}, ReasonSQLC)
	})

	t.Run("detects generic from content without I/O", func(t *testing.T) {
		t.Parallel()

		content := "// Code generated by foobar. DO NOT EDIT.\npackage main\n"
		testDetectReason(t, "foo.go", content, map[FilterOption]bool{FilterGeneric: true}, ReasonGeneric)
	})

	t.Run("returns not filtered for non-matching content", func(t *testing.T) {
		t.Parallel()
		testDetectReasonNotFiltered(t, "file.go", "package main", map[FilterOption]bool{FilterGeneric: true})
	})
}

type detectorPriorityTest struct {
	name     string
	path     string
	content  string
	expected FilterReason
}

func detectorPriorityTests() []detectorPriorityTest {
	return []detectorPriorityTest{
		{
			name:     "stringer beats generic",
			path:     "status_string.go",
			content:  "// Code generated by \"stringer\". DO NOT EDIT.\npackage enums\n",
			expected: ReasonStringer,
		},
		{
			name:     "sqlc beats generic",
			path:     "db/models.go",
			content:  "// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
			expected: ReasonSQLC,
		},
		{
			name:     "mockgen beats generic",
			path:     "service_mock.go",
			content:  "// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n",
			expected: ReasonMockgen,
		},
		{
			name:     "generic catches unknown tool",
			path:     "custom_gen.go",
			content:  "// Code generated by my-tool. DO NOT EDIT.\npackage main\n",
			expected: ReasonGeneric,
		},
		{
			name:     "go-enum beats generic",
			path:     "status_enum.go",
			content:  "// Code generated by go-enum DO NOT EDIT.\npackage enums\n",
			expected: ReasonGoEnum,
		},
		{
			name:     "protobuf beats generic",
			path:     "user.pb.go",
			content:  "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
			expected: ReasonProtobuf,
		},
	}
}

func TestDetectorPriorityWithFilterAll(t *testing.T) {
	t.Parallel()

	allOpts := map[FilterOption]bool{
		FilterSQLC: true, FilterTempl: true, FilterGoEnum: true,
		FilterProtobuf: true, FilterMockgen: true, FilterStringer: true,
		FilterGeneric: true,
	}

	for _, tt := range detectorPriorityTests() {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			reason := DetectReason(tt.path, tt.content, allOpts)

			if reason != tt.expected {
				t.Errorf("DetectReason(%q) = %v, want %v", tt.path, reason, tt.expected)
			}
		})
	}
}

func TestDetectReasonFilenameOnlyNoContentCheck(t *testing.T) {
	t.Parallel()
	testDetectReasonNotFiltered(t, "regular.go", "", map[FilterOption]bool{FilterTempl: true})
}

func TestEmptyContent(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		fn   func(string, string) bool
	}{
		{"IsSQLCGenerated", IsSQLCGenerated},
		{"IsTemplGenerated", IsTemplGenerated},
		{"IsGoEnumGenerated", IsGoEnumGenerated},
		{"IsProtobufGenerated", IsProtobufGenerated},
		{"IsMockgenGenerated", IsMockgenGenerated},
		{"IsStringerGenerated", IsStringerGenerated},
		{"IsGenericGenerated", IsGenericGenerated},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			if tt.fn("file.go", "") {
				t.Errorf("%s with empty content should return false", tt.name)
			}
		})
	}
}

func TestMatchesSQLCFilenameFalsePositives(t *testing.T) {
	t.Parallel()

	tests := []sqlcFilenameTestCase{
		{name: "user_models.go is not sqlc", path: "db/user_models.go", expected: false},
		{name: "myquerier.go is not sqlc", path: "db/myquerier.go", expected: false},
		{name: "batch_processor.go is not sqlc", path: "db/batch_processor.go", expected: false},
	}

	runSQLCFilenameTests(t, tests)
}

func TestMatchesSQLCFilename(t *testing.T) {
	t.Parallel()

	tests := []sqlcFilenameTestCase{
		{name: "models.go", path: "db/models.go", expected: true},
		{name: "querier.go", path: "db/querier.go", expected: true},
		{name: "query.sql.go", path: "db/query.sql.go", expected: true},
		{name: "batch.go", path: "db/batch.go", expected: true},
		{name: "users.sql.go", path: "db/users.sql.go", expected: true},
		{name: "regular file", path: "db/main.go", expected: false},
	}

	runSQLCFilenameTests(t, tests)
}

func sqlcPatternAndContentTests() ([]boolTestCase[string], []boolTestCase[string]) {
	codePatternTests := make([]boolTestCase[string], 0, 4)
	codePatternTests = addBoolTestCase(addBoolTestCase(addBoolTestCase(addBoolTestCase(
		codePatternTests, "sqlc.Arg", "id := sqlc.Arg(\"user_id\")", true), "sqlc.Narg", "id := sqlc.Narg(\"user_id\")", true), "query method", "row := q.query(ctx, sql)", true), "no pattern", "package main\nfunc main() {}", false)

	contentTests := make([]boolTestCase[string], 0, 4)
	contentTests = addBoolTestCase(addBoolTestCase(addBoolTestCase(addBoolTestCase(
		contentTests, "code generated comment", "// Code generated by sqlc. DO NOT EDIT.\npackage db\n", true), "sqlc versions block", "// Code generated by sqlc v1.25.0\n// versions:\npackage db\n", true), "code pattern only", "package db\nid := sqlc.Arg(\"id\")\n", true), "no sqlc markers", "package main\nfunc main() {}\n", false)

	return codePatternTests, contentTests
}

func runSQLCSubTest(t *testing.T, name string, tests []boolTestCase[string], fn func(string) bool) {
	t.Helper()
	t.Run(name, func(t *testing.T) {
		t.Parallel()
		runBoolTableTest(t, tests, fn, name)
	})
}

func TestSQLCDetection(t *testing.T) {
	t.Parallel()

	codePatternTests, contentTests := sqlcPatternAndContentTests()

	runSQLCSubTest(t, "HasSQLCCodePatterns", codePatternTests, HasSQLCCodePatterns)
	runSQLCSubTest(t, "HasSQLCContent", contentTests, HasSQLCContent)
}
