package gogenfilter

import (
	"fmt"
	"io"
	"io/fs"
	"path/filepath"
	"slices"
	"strings"
)

// detector represents a code generator with optional filename and content detection.
// matchFilename is used in phase 1 (zero I/O); checkContent in phase 2 (reads file).
// The reason field explicitly maps each FilterOption to its FilterReason,
// eliminating the implicit string-value coupling between the two types.
type detector struct {
	option        FilterOption
	reason        FilterReason
	matchFilename func(string) bool
	checkContent  func(string, string) bool
}

// detectors lists all code generator detectors.
// Ordered from most specific to least specific; FilterGeneric must be last.
// Each detector may have a filename matcher (phase 1, zero I/O), a content checker
// (phase 2, reads file), or both.
//
//nolint:gochecknoglobals // immutable lookup table, never mutated
var detectors = []detector{
	{FilterSQLC, ReasonSQLC, matchesSQLCFilenamePattern, IsSQLCGenerated},
	{FilterTempl, ReasonTempl, matchesSuffixPattern("_templ.go"), IsTemplGenerated},
	{FilterGoEnum, ReasonGoEnum, matchesSuffixPattern("_enum.go"), IsGoEnumGenerated},
	{FilterProtobuf, ReasonProtobuf, matchesProtobufFilename, IsProtobufGenerated},
	{FilterOapi, ReasonOapi, nil, IsOapiGenerated},
	{FilterDeepcopy, ReasonDeepcopy, matchesDeepcopyFilename, IsDeepcopyGenerated},
	{FilterWire, ReasonWire, matchesSuffixPattern("wire_gen.go"), IsWireGenerated},
	{FilterMoq, ReasonMoq, matchesMoqFilename, IsMoqGenerated},
	{FilterMockgen, ReasonMockgen, matchesMockgenFilename, IsMockgenGenerated},
	{FilterStringer, ReasonStringer, nil, IsStringerGenerated},
	{FilterGeneric, ReasonGeneric, nil, IsGenericGenerated},
}

// allSpecificOptions returns all FilterOption values that correspond to specific
// code generators (i.e., everything except FilterGeneric and FilterAll).
// Derived from the detectors table so adding a new detector automatically updates this list.
func allSpecificOptions() []FilterOption {
	opts := make([]FilterOption, 0, len(detectors))

	for _, d := range detectors {
		if d.option != FilterGeneric {
			opts = append(opts, d.option)
		}
	}

	return opts
}

// matchesSQLCFilenamePattern checks if a base filename matches sqlc.dev naming patterns.
//
//nolint:gochecknoglobals // immutable lookup table, never mutated
var sqlcFilenamePatterns = []string{"models.go", "querier.go", "query.sql.go", "batch.go"}

func matchesSQLCFilenamePattern(filename string) bool {
	return slices.Contains(sqlcFilenamePatterns, filename) || strings.HasSuffix(filename, ".sql.go")
}

// IsSQLCGenerated checks if a file is generated by sqlc.dev.
func IsSQLCGenerated(filePath, content string) bool {
	if !MatchesSQLCFilename(filePath) {
		return false
	}

	return HasSQLCContent(content)
}

// matchesSuffixPattern returns a function that matches filenames ending with the given suffix.
func matchesSuffixPattern(suffix string) func(string) bool {
	return func(f string) bool {
		return strings.HasSuffix(f, suffix)
	}
}

// anyMatch returns true if the predicate returns true for any element.
func anyMatch(s string, candidates []string, pred func(string, string) bool) bool {
	return slices.ContainsFunc(candidates, func(c string) bool {
		return pred(s, c)
	})
}

func matchesProtobufFilename(filename string) bool {
	return anyMatch(filename, []string{".pb.go", "_grpc.pb.go"}, strings.HasSuffix)
}

// matchesMockgenFilename checks if a base filename matches mockgen naming patterns.
func matchesMockgenFilename(filename string) bool {
	if strings.HasSuffix(filename, "_mock.go") {
		return true
	}

	return strings.HasPrefix(filename, "mock_")
}

// MatchesSQLCFilename checks if filename matches sqlc.dev naming patterns.
func MatchesSQLCFilename(filePath string) bool {
	return matchesSQLCFilenamePattern(filepath.Base(filePath))
}

// HasSQLCContent checks if content contains sqlc.dev specific markers.
func HasSQLCContent(content string) bool {
	if strings.Contains(content, "// Code generated by sqlc. DO NOT EDIT.") {
		return true
	}

	if strings.Contains(content, "sqlc ") && strings.Contains(content, "versions:") {
		return true
	}

	return HasSQLCCodePatterns(content)
}

// matchAnyContentPattern checks if any of the candidate patterns exist in the content.
func matchAnyContentPattern(content string, candidates []string) bool {
	return slices.ContainsFunc(candidates, func(pattern string) bool {
		return strings.Contains(content, pattern)
	})
}

// HasSQLCCodePatterns checks for sqlc-specific code patterns in content.
func HasSQLCCodePatterns(content string) bool {
	return matchAnyContentPattern(content, []string{
		"sqlc.Arg",
		"sqlc.NamedArg",
		"sqlc.Literal",
		"sqlc.SliceArg",
		"sqlc.Narg",
		".query(ctx",
	})
}

// IsTemplGenerated checks if a file is generated by templ.guide.
func IsTemplGenerated(filePath, content string) bool {
	filename := filepath.Base(filePath)

	if !strings.HasSuffix(filename, "_templ.go") {
		return false
	}

	if strings.Contains(content, "templ.Component") {
		return true
	}

	if strings.Contains(content, "Render(ctx context.Context, w io.Writer) error") {
		return true
	}

	return false
}

// IsGoEnumGenerated checks if a file is generated by go-enum.
func IsGoEnumGenerated(filePath, content string) bool {
	filename := filepath.Base(filePath)

	if !strings.HasSuffix(filename, "_enum.go") {
		return false
	}

	return strings.Contains(content, "// Code generated by go-enum")
}

// isGeneratedBy checks if content contains a "Code generated by" comment for the given generator.
func isGeneratedBy(content, generator string) bool {
	return strings.Contains(content, "// Code generated by "+generator)
}

// IsProtobufGenerated checks if a file is generated by protoc-gen-go.
func IsProtobufGenerated(filePath, content string) bool {
	if !matchesProtobufFilename(filepath.Base(filePath)) {
		return false
	}

	return strings.Contains(content, codeGeneratedPrefix)
}

// IsMockgenGenerated checks if a file was generated by mockgen.
func IsMockgenGenerated(_, content string) bool {
	return isGeneratedBy(content, "MockGen")
}

// IsOapiGenerated checks if a file was generated by oapi-codegen.
func IsOapiGenerated(_, content string) bool {
	return strings.Contains(content, "oapi-codegen")
}

// matchesDeepcopyFilename checks if a base filename matches Kubernetes deepcopy-gen patterns.
func matchesDeepcopyFilename(filename string) bool {
	return strings.HasPrefix(filename, "zz_generated.") && strings.HasSuffix(filename, ".go")
}

// IsDeepcopyGenerated checks if a file was generated by deepcopy-gen (Kubernetes).
func IsDeepcopyGenerated(_, content string) bool {
	return isGeneratedBy(content, "deepcopy-gen")
}

// IsWireGenerated checks if a file was generated by google/wire.
func IsWireGenerated(_, content string) bool {
	return isGeneratedBy(content, "Wire")
}

// matchesMoqFilename checks if a base filename matches matryer/moq naming patterns.
func matchesMoqFilename(filename string) bool {
	return strings.HasSuffix(filename, "_moq.go") || strings.HasSuffix(filename, "_moq_test.go")
}

// IsMoqGenerated checks if a file was generated by matryer/moq.
func IsMoqGenerated(_, content string) bool {
	return isGeneratedBy(content, "moq")
}

// IsStringerGenerated checks if a file was generated by the stringer tool.
func IsStringerGenerated(_, content string) bool {
	return isGeneratedBy(content, `"stringer"`)
}

// IsGenericGenerated checks if a file was generated by go generate.
func IsGenericGenerated(_, content string) bool {
	return strings.Contains(content, codeGeneratedPrefix)
}

// DetectReason checks if a file is auto-generated based on filename and content.
// No I/O is performed — the caller provides the file content.
// Returns the reason for filtering, or ReasonNotFiltered if the file is not generated.
func DetectReason(filePath, content string, opts ...FilterOption) FilterReason {
	return detectReasonFromMap(filePath, content, optionsMap(opts...))
}

// DetectReasonReader checks if a file is auto-generated by reading content from an io.Reader.
// Useful when the caller already has the file content in a stream (e.g., from an HTTP handler
// or a processing pipeline) and wants to avoid reading it into a string first.
// Returns the reason for filtering, or ReasonNotFiltered if the file is not generated.
func DetectReasonReader(filePath string, r io.Reader, opts ...FilterOption) (FilterReason, error) {
	content, err := io.ReadAll(r)
	if err != nil {
		return ReasonNotFiltered, fmt.Errorf("read content from %q: %w", filePath, err)
	}

	return DetectReason(filePath, string(content), opts...), nil
}

// detectReasonFromMap is the shared core for both DetectReason and detectReasonFS.
func detectReasonFromMap(filePath, content string, options map[FilterOption]struct{}) FilterReason {
	// Phase 1: Check filename-based detectors (zero I/O)
	filenameReason := getFilenameBasedReason(filePath, options)
	if filenameReason != ReasonNotFiltered {
		return filenameReason
	}

	// Phase 2: Content-based detection only if needed
	if needsContentCheck(options) {
		return getContentBasedReason(filePath, content, options)
	}

	return ReasonNotFiltered
}

// optionsMap builds a lookup map from variadic FilterOption values.
// FilterAll is expanded to all specific options.
func optionsMap(opts ...FilterOption) map[FilterOption]struct{} {
	result := make(map[FilterOption]struct{}, len(opts))

	for _, opt := range opts {
		if opt == FilterAll {
			for _, specific := range allSpecificOptions() {
				result[specific] = struct{}{}
			}

			result[FilterGeneric] = struct{}{}
		} else {
			result[opt] = struct{}{}
		}
	}

	return result
}

// detectReasonFS determines if and why a file is auto-generated by reading it from the given filesystem.
// Two-phase detection: filename-based first (zero I/O), then content-based (reads file).
func detectReasonFS(
	fsys fs.FS,
	filePath string,
	options map[FilterOption]struct{},
) (FilterReason, error) {
	if reason := getFilenameBasedReason(filePath, options); reason != ReasonNotFiltered {
		return reason, nil
	}

	if !needsContentCheck(options) {
		return ReasonNotFiltered, nil
	}

	content, err := fs.ReadFile(fsys, filePath)
	if err != nil {
		return ReasonNotFiltered, fmt.Errorf("read file %q: %w", filePath, err)
	}

	return getContentBasedReason(filePath, string(content), options), nil
}

// needsContentCheck returns true if any enabled detector requires reading file content.
func needsContentCheck(options map[FilterOption]struct{}) bool {
	for i := range detectors {
		d := &detectors[i]
		if _, enabled := options[d.option]; enabled {
			if d.checkContent != nil {
				return true
			}
		}
	}

	return false
}

// getContentBasedReason checks content for generator-specific markers.
// Uses a table-driven approach: specific generators are checked first, FilterGeneric is the fallback.
func getContentBasedReason(
	path string,
	fileContent string,
	opts map[FilterOption]struct{},
) FilterReason {
	for i := range detectors {
		d := &detectors[i]
		if _, enabled := opts[d.option]; enabled {
			if d.checkContent != nil && d.checkContent(path, fileContent) {
				return d.reason
			}
		}
	}

	return ReasonNotFiltered
}

// getFilenameBasedReason determines the filter reason based on filename only.
func getFilenameBasedReason(filePath string, options map[FilterOption]struct{}) FilterReason {
	filename := filepath.Base(filePath)

	for i := range detectors {
		d := &detectors[i]
		if _, enabled := options[d.option]; enabled {
			if d.matchFilename != nil && d.matchFilename(filename) {
				return d.reason
			}
		}
	}

	return ReasonNotFiltered
}
