package gogenfilter

import (
	"os"
	"path/filepath"
	"strings"
)

// contentChecks returns filter options with their reasons and content-based detection functions.
// Ordered from most specific to least specific; FilterGeneric must be last.
func contentChecks() []struct {
	option FilterOption
	reason FilterReason
	check  func(string, string) bool
} {
	return []struct {
		option FilterOption
		reason FilterReason
		check  func(string, string) bool
	}{
		{FilterSQLC, ReasonSQLC, IsSQLCGenerated},
		{FilterTempl, ReasonTempl, IsTemplGenerated},
		{FilterGoEnum, ReasonGoEnum, IsGoEnumGenerated},
		{FilterProtobuf, ReasonProtobuf, IsProtobufGenerated},
		{FilterMockgen, ReasonMockgen, IsMockgenGenerated},
		{FilterStringer, ReasonStringer, IsStringerGenerated},
		{FilterGeneric, ReasonGeneric, IsGenericGenerated},
	}
}

// filenameChecks returns filter options with their reasons and filename-based detection functions.
// Ordered from most specific to least specific.
func filenameChecks() []struct {
	option FilterOption
	reason FilterReason
	match  func(string) bool
} {
	return []struct {
		option FilterOption
		reason FilterReason
		match  func(string) bool
	}{
		{FilterSQLC, ReasonSQLC, matchesSQLCFilenamePattern},
		{
			FilterTempl, ReasonTempl,
			func(f string) bool {
				return strings.HasSuffix(f, "_templ.go")
			},
		},
		{
			FilterGoEnum, ReasonGoEnum,
			func(f string) bool {
				return strings.HasSuffix(f, "_enum.go")
			},
		},
		{FilterProtobuf, ReasonProtobuf, matchesProtobufFilename},
		{FilterMockgen, ReasonMockgen, matchesMockgenFilename},
	}
}

// sqlcFilePatterns returns the standard filename patterns for sqlc.dev generated files.
func sqlcFilePatterns() []string {
	return []string{
		"models.go",
		"querier.go",
		"query.sql.go",
		"batch.go",
	}
}

// sqlcCodePatterns returns code patterns specific to sqlc-generated files.
func sqlcCodePatterns() []string {
	return []string{
		"sqlc.Arg",
		"sqlc.NamedArg",
		"sqlc.Literal",
		"sqlc.SliceArg",
		"sqlc.Narg",
		".query(ctx",
	}
}

// IsSQLCGenerated checks if a file is generated by sqlc.dev.
func IsSQLCGenerated(filePath, content string) bool {
	if !MatchesSQLCFilename(filePath) {
		return false
	}

	return HasSQLCContent(content)
}

// matchesSQLCFilenamePattern checks if a base filename matches sqlc.dev naming patterns.
func matchesSQLCFilenamePattern(filename string) bool {
	for _, pattern := range sqlcFilePatterns() {
		if strings.Contains(filename, pattern) {
			return true
		}
	}

	return strings.HasSuffix(filename, ".sql.go")
}

// matchesProtobufFilename checks if a base filename matches protobuf naming patterns.
func matchesProtobufFilename(filename string) bool {
	return strings.HasSuffix(filename, ".pb.go") || strings.HasSuffix(filename, "_grpc.pb.go")
}

// matchesMockgenFilename checks if a base filename matches mockgen naming patterns.
func matchesMockgenFilename(filename string) bool {
	return strings.Contains(filename, "_mock.go") || strings.Contains(filename, "mock_")
}

// MatchesSQLCFilename checks if filename matches sqlc.dev naming patterns.
func MatchesSQLCFilename(filePath string) bool {
	return matchesSQLCFilenamePattern(filepath.Base(filePath))
}

// HasSQLCContent checks if content contains sqlc.dev specific markers.
func HasSQLCContent(content string) bool {
	if strings.Contains(content, "// Code generated by sqlc. DO NOT EDIT.") {
		return true
	}

	if strings.Contains(content, "sqlc ") && strings.Contains(content, "versions:") {
		return true
	}

	return HasSQLCCodePatterns(content)
}

// HasSQLCCodePatterns checks for sqlc-specific code patterns in content.
func HasSQLCCodePatterns(content string) bool {
	for _, pattern := range sqlcCodePatterns() {
		if strings.Contains(content, pattern) {
			return true
		}
	}

	return false
}

// IsTemplGenerated checks if a file is generated by templ.guide.
func IsTemplGenerated(filePath, content string) bool {
	filename := filepath.Base(filePath)

	if !strings.HasSuffix(filename, "_templ.go") {
		return false
	}

	if strings.Contains(content, "templ.Component") {
		return true
	}

	if strings.Contains(content, "Render(ctx context.Context, w io.Writer) error") {
		return true
	}

	return false
}

// IsGoEnumGenerated checks if a file is generated by go-enum.
func IsGoEnumGenerated(filePath, content string) bool {
	filename := filepath.Base(filePath)

	if !strings.HasSuffix(filename, "_enum.go") {
		return false
	}

	return strings.Contains(content, "// Code generated by go-enum")
}

// IsProtobufGenerated checks if a file is generated by protoc-gen-go.
func IsProtobufGenerated(filePath, content string) bool {
	if !matchesProtobufFilename(filepath.Base(filePath)) {
		return false
	}

	return strings.Contains(content, codeGeneratedPrefix)
}

// hasGeneratedMarker checks if content contains a specific generated code marker.
func hasGeneratedMarker(_, content string, marker string) bool {
	return strings.Contains(content, marker)
}

// IsMockgenGenerated checks if a file is generated by mockgen.
func IsMockgenGenerated(filePath, content string) bool {
	return hasGeneratedMarker(filePath, content, "// Code generated by MockGen")
}

// IsStringerGenerated checks if a file is generated by stringer.
func IsStringerGenerated(filePath, content string) bool {
	return hasGeneratedMarker(filePath, content, `// Code generated by "stringer"`)
}

// IsGenericGenerated checks if a file contains any standard "Code generated by" comment.
func IsGenericGenerated(filePath, content string) bool {
	return hasGeneratedMarker(filePath, content, codeGeneratedPrefix)
}

// DetectGenerated checks if a file is auto-generated based on filename and optional content.
// If content is empty, it reads the file from disk.
// It returns the reason for filtering, or ReasonNotFiltered if the file is not generated.
func DetectGenerated(filePath string, options map[FilterOption]bool) FilterReason {
	return detectGeneratedReason(filePath, options)
}

// detectGeneratedReason determines if and why a file is auto-generated.
// Two-phase detection: filename-based first (zero I/O), then content-based (reads file).
func detectGeneratedReason(filePath string, options map[FilterOption]bool) FilterReason {
	if reason := getFilenameBasedReason(filePath, options); reason != ReasonNotFiltered {
		return reason
	}

	if !needsContentCheck(options) {
		return ReasonNotFiltered
	}

	content, err := os.ReadFile(filePath) //nolint:gosec // filePath is from controlled source
	if err != nil {
		return ReasonNotFiltered
	}

	contentStr := string(content)

	return getContentBasedReason(filePath, contentStr, options)
}

// needsContentCheck returns true if any enabled filter option requires reading file content.
func needsContentCheck(options map[FilterOption]bool) bool {
	for _, cc := range contentChecks() {
		if options[cc.option] {
			return true
		}
	}

	return false
}

// getContentBasedReason checks content for generator-specific markers.
// Uses a table-driven approach: specific generators are checked first, FilterGeneric is the fallback.
func getContentBasedReason(filePath, content string, options map[FilterOption]bool) FilterReason {
	for _, cc := range contentChecks() {
		if options[cc.option] && cc.check(filePath, content) {
			return cc.reason
		}
	}

	return ReasonNotFiltered
}

// getFilenameBasedReason determines the filter reason based on filename only.
func getFilenameBasedReason(filePath string, options map[FilterOption]bool) FilterReason {
	filename := filepath.Base(filePath)

	for _, fc := range filenameChecks() {
		if options[fc.option] && fc.match(filename) {
			return fc.reason
		}
	}

	return ReasonNotFiltered
}
