// Package gogenfilter detects and filters auto-generated Go code files.
//
// It identifies files generated by common tools including
// gendocs:generator-list:start
// sqlc, templ, go-enum, protobuf, oapi-codegen, deepcopy-gen, wire, moq, mockgen, stringer, mockery, ent, gqlgen, easyjson, msgp, counterfeiter, go-swagger, and any tool using the standard "Code generated by" comment convention
// gendocs:generator-list:end
// per https://go.dev/s/generatedcode.
//
// Detection is three-phase:
//
//  1. Filename-based (zero I/O) — matches generator-specific filename patterns
//     (e.g., `*.sql.go`, `*_templ.go`, `*.pb.go`).
//  2. Config-aware (reads sqlc.yaml, zero file reads for detection) — for sqlc,
//     parses `sqlc.yaml`/`sqlc.yml` to determine declared output directories and
//     classifies fixed filenames (models.go, db.go, querier.go, batch.go,
//     copyfrom.go) as generated **iff** they live in a configured output dir.
//     This eliminates false positives on hand-written files with common names
//     outside configured dirs. Only active on Filter (not standalone
//     DetectReason/DetectReasonFile).
//  3. Content-based (reads file) — searches the file header (before the package
//     clause) for generator-specific "Code generated by" markers.
//
// Phases are ordered by cost: filename checks are free, config parsing is a
// one-time walk cached for the filter's lifetime, and content reads are the
// most expensive.
//
// # Quick Start
//
// Create a filter with functional options:
//
//	opts, err := gogenfilter.WithFilterOptions(gogenfilter.FilterAll)
//	if err != nil {
//	    log.Fatal(err)
//	}
//	f, err := gogenfilter.NewFilter(opts)
//	if err != nil {
//	    log.Fatal(err)
//	}
//
// Check files — Filter returns (bool, error) to propagate I/O errors:
//
//	filtered, err := f.Filter("db/models.go")
//	if err != nil {
//	    log.Fatal(err)
//	}
//	if filtered {
//	    fmt.Println("skipping generated file")
//	}
//
// For low-level detection without a Filter:
//
//	reason := gogenfilter.DetectReason("file.go", content,
//	    gogenfilter.FilterSQLC,
//	    gogenfilter.FilterGeneric,
//	)
//
// Get the detection result and file content in one call (avoids double I/O):
//
//	result, content, err := f.FilterDetailedAndContent("db/models.go")
//	if err != nil {
//	    log.Fatal(err)
//	}
//	if result.Filtered {
//	    fmt.Printf("skipping %s-generated file\n", result.Reason)
//	}
//	// content is non-nil when phase-2 read the file; reuse it for further analysis
package gogenfilter
