package gogenfilter_test

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"testing/fstest"

	"github.com/LarsArtmann/gogenfilter"
)

// mapFSWithFile creates a MapFS with a single file for testing.
func mapFSWithFile(path, content string) fstest.MapFS {
	return fstest.MapFS{
		path: &fstest.MapFile{
			Data: []byte(content),
		},
	}
}

// mapFSWithFiles creates a MapFS with multiple files for testing.
func mapFSWithFiles(files map[string]string) fstest.MapFS {
	mapFS := make(fstest.MapFS, len(files))
	for path, content := range files {
		mapFS[path] = &fstest.MapFile{
			Data: []byte(content),
		}
	}

	return mapFS
}

// newTestFilter creates a Filter with enabled state, filter options, and filesystem.
func newTestFilter(opts gogenfilter.FilterOption, mapFS fstest.MapFS) *gogenfilter.Filter {
	configOpts, err := gogenfilter.WithFilterOptions(opts)
	if err != nil {
		panic(err)
	}

	filter, err := gogenfilter.NewFilter(
		configOpts,
		gogenfilter.WithFS(mapFS),
	)
	if err != nil {
		panic(err)
	}

	return filter
}

// newTestFilterWithInclude creates a Filter with include patterns.
func newTestFilterWithInclude(
	opts gogenfilter.FilterOption,
	include string,
	mapFS fstest.MapFS,
) *gogenfilter.Filter {
	configOpts, err := gogenfilter.WithFilterOptions(opts)
	if err != nil {
		panic(err)
	}

	filter, err := gogenfilter.NewFilter(
		configOpts,
		gogenfilter.WithIncludePatterns(include),
		gogenfilter.WithFS(mapFS),
	)
	if err != nil {
		panic(err)
	}

	return filter
}

func ExampleNewFilter() {
	opts, err := gogenfilter.WithFilterOptions(
		gogenfilter.FilterSQLC,
		gogenfilter.FilterTempl,
		gogenfilter.FilterGeneric,
	)
	if err != nil {
		return
	}

	filter, err := gogenfilter.NewFilter(opts)
	if err != nil {
		return
	}

	fmt.Println(filter.IsEnabled())
	// Output: true
}

func ExampleNewFilter_withExcludePatterns() {
	opts, err := gogenfilter.WithFilterOptions(gogenfilter.FilterAll)
	if err != nil {
		return
	}

	filter, err := gogenfilter.NewFilter(
		opts,
		gogenfilter.WithExcludePatterns("**/db/*.go"),
	)
	if err != nil {
		return
	}

	fmt.Println(filter.IsEnabled())
	// Output: true
}

func ExampleDetectReason() {
	sqlcContent := `// Code generated by sqlc. DO NOT EDIT.
// versions:
package db
`
	reason := gogenfilter.DetectReason(
		"db/models.go",
		sqlcContent,
		gogenfilter.FilterSQLC,
	)

	fmt.Println(reason)
	// Output: sqlc
}

func ExampleDetectReason_notFiltered() {
	reason := gogenfilter.DetectReason(
		"main.go",
		"package main\n",
		gogenfilter.FilterSQLC,
	)

	fmt.Println(reason)
	// Output: not-filtered
}

func ExampleMatchPattern() {
	fmt.Println(gogenfilter.MatchPattern("db/models.go", "**/*.go"))
	fmt.Println(gogenfilter.MatchPattern("db/models.go", "**/db/*.go"))
	fmt.Println(gogenfilter.MatchPattern("main.go", "**/db/*.go"))
	// Output:
	// true
	// true
	// false
}

func ExampleFilterReason_IsValid() {
	fmt.Println(gogenfilter.ReasonSQLC.IsValid())
	fmt.Println(gogenfilter.FilterReason("unknown").IsValid())
	// Output:
	// true
	// false
}

func ExampleFilterOption_IsValid() {
	fmt.Println(gogenfilter.FilterSQLC.IsValid())
	fmt.Println(gogenfilter.FilterOption("unknown").IsValid())
	// Output:
	// true
	// false
}

func ExampleAllFilterOptions() {
	opts := gogenfilter.AllFilterOptions()

	fmt.Println(len(opts))
	// Output: 12
}

func ExampleAllFilterReasons() {
	reasons := gogenfilter.AllFilterReasons()

	fmt.Println(len(reasons))
	// Output: 14
}

func runFilterExample(opts gogenfilter.FilterOption, filePath, content string) {
	filter := newTestFilter(opts, mapFSWithFile(filePath, content))
	filtered, _ := filter.Filter(filePath)
	_, _ = fmt.Fprintf(os.Stdout, "%v\n", filtered)
}

func ExampleFilter_Filter() {
	runFilterExample(
		gogenfilter.FilterSQLC,
		"db/models.go",
		"// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
	)
	// Output: true
}

func ExampleFilter_Filter_notFiltered() {
	runFilterExample(gogenfilter.FilterSQLC, "main.go", "package main\n")
	// Output: false
}

func ExampleWithIncludePatterns() {
	mapFS := mapFSWithFiles(map[string]string{
		"db/models.go":  "// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
		"other/file.go": "// Code generated by sqlc. DO NOT EDIT.\npackage other\n",
	})

	filter := newTestFilterWithInclude(gogenfilter.FilterSQLC, "db/**", mapFS)

	dbFiltered, _ := filter.Filter("db/models.go")
	otherFiltered, _ := filter.Filter("other/file.go")
	fmt.Println(dbFiltered, otherFiltered)
	// Output: true true
}

func ExampleWithFS() {
	mapFS := mapFSWithFile(
		"generated.go",
		"// Code generated by stringer. DO NOT EDIT.\npackage foo\n",
	)
	filter := newTestFilter(gogenfilter.FilterGeneric, mapFS)

	filtered, _ := filter.Filter("generated.go")
	fmt.Println(filtered)
	// Output: true
}

func ExampleFilter_GetStats() {
	mapFS := mapFSWithFiles(map[string]string{
		"db/models.go": "// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
		"main.go":      "package main\n",
	})
	filter := newTestFilter(gogenfilter.FilterSQLC, mapFS)

	_, _ = filter.Filter("db/models.go")
	_, _ = filter.Filter("main.go")

	stats := filter.GetStats()
	fmt.Println(stats.TotalFilesChecked)
	fmt.Println(stats.FilteredBy(gogenfilter.ReasonSQLC))
	fmt.Println(stats.TotalFiltered())
	// Output:
	// 2
	// 1
	// 1
}

func ExampleDetectReasonReader() {
	content := "// Code generated by sqlc. DO NOT EDIT.\npackage db\n"
	r := bytes.NewBufferString(content)

	reason, _ := gogenfilter.DetectReasonReader(
		"db/models.go",
		r,
		gogenfilter.FilterSQLC,
	)
	fmt.Println(reason)
	// Output: sqlc
}

func ExampleFindProjectRoot_errorHandling() {
	_, err := gogenfilter.FindProjectRoot(
		gogenfilter.StartPath("/nonexistent/path"),
		[]string{"go.mod"},
	)
	if err != nil {
		fmt.Println(errors.Is(err, gogenfilter.ErrProjectRootNotFound))
		fmt.Println(err.ErrorCode())
		fmt.Println(err.Help() != "")
	}
	// Output:
	// true
	// project_root_not_found
	// true
}

func ExampleCodeHelp() {
	help := gogenfilter.CodeHelp(gogenfilter.CodeSQLCConfigParse)
	fmt.Println(help != "")
	// Output: true
}

func ExampleAllErrorCodes() {
	codes := gogenfilter.AllErrorCodes()
	fmt.Println(len(codes))
	// Output: 8
}

func ExampleFilter_FilterDetailed() {
	mapFS := mapFSWithFile(
		"db/models.go",
		"// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
	)
	filter := newTestFilter(gogenfilter.FilterSQLC, mapFS)

	result, _ := filter.FilterDetailed("db/models.go")
	fmt.Println(result.Filtered)
	fmt.Println(result.Reason)
	fmt.Println(result.Trace != "")
	// Output:
	// true
	// sqlc
	// true
}

func ExampleFilter_FilterDetailed_notFiltered() {
	mapFS := mapFSWithFile(
		"main.go",
		"package main\nfunc main() {}\n",
	)
	filter := newTestFilter(gogenfilter.FilterSQLC, mapFS)

	result, _ := filter.FilterDetailed("main.go")
	fmt.Println(result.Filtered)
	fmt.Println(result.Reason)
	// Output:
	// false
	// not-filtered
}

func ExampleAllGeneratorOptions() {
	opts := gogenfilter.AllGeneratorOptions()

	fmt.Println(len(opts))
	// Output: 11
}

func ExampleFilterOption_Reason() {
	reason, found := gogenfilter.FilterSQLC.Reason()
	fmt.Println(found)
	fmt.Println(reason)
	// Output:
	// true
	// sqlc
}

func ExampleFilterOption_Reason_filterAll() {
	_, found := gogenfilter.FilterAll.Reason()
	fmt.Println(found)
	// Output: false
}
