package gogenfilter_test

import (
	"fmt"

	"github.com/LarsArtmann/gogenfilter"
)

func ExampleNewFilter() {
	filter := gogenfilter.NewFilter(true, []gogenfilter.FilterOption{
		gogenfilter.FilterSQLC,
		gogenfilter.FilterTempl,
		gogenfilter.FilterGeneric,
	})

	fmt.Println(filter.IsEnabled())
	// Output: true
}

func ExampleNewFilter_withExcludePatterns() {
	filter := gogenfilter.NewFilter(true, []gogenfilter.FilterOption{
		gogenfilter.FilterAll,
	}).WithExcludePatterns([]string{
		"**/db/*.go",
	})

	fmt.Println(filter.IsEnabled())
	// Output: true
}

func ExampleDetectReason() {
	sqlcContent := `// Code generated by sqlc. DO NOT EDIT.
// versions:
package db
`
	reason := gogenfilter.DetectReason(
		"db/models.go",
		sqlcContent,
		map[gogenfilter.FilterOption]bool{gogenfilter.FilterSQLC: true},
	)

	fmt.Println(reason)
	// Output: sqlc
}

func ExampleDetectReason_notFiltered() {
	reason := gogenfilter.DetectReason(
		"main.go",
		"package main\n",
		map[gogenfilter.FilterOption]bool{gogenfilter.FilterSQLC: true},
	)

	fmt.Println(reason)
	// Output: not-filtered
}

func ExampleMatchPattern() {
	fmt.Println(gogenfilter.MatchPattern("db/models.go", "**/*.go"))
	fmt.Println(gogenfilter.MatchPattern("db/models.go", "**/db/*.go"))
	fmt.Println(gogenfilter.MatchPattern("main.go", "**/db/*.go"))
	// Output:
	// true
	// true
	// false
}

func ExampleFilterReason_IsValid() {
	fmt.Println(gogenfilter.ReasonSQLC.IsValid())
	fmt.Println(gogenfilter.FilterReason("unknown").IsValid())
	// Output:
	// true
	// false
}

func ExampleFilterOption_IsValid() {
	fmt.Println(gogenfilter.FilterSQLC.IsValid())
	fmt.Println(gogenfilter.FilterOption("unknown").IsValid())
	// Output:
	// true
	// false
}

func ExampleAllFilterOptions() {
	opts := gogenfilter.AllFilterOptions()

	fmt.Println(len(opts))
	// Output: 8
}

func ExampleAllFilterReasons() {
	reasons := gogenfilter.AllFilterReasons()

	fmt.Println(len(reasons))
	// Output: 10
}
