package gogenfilter_test

import (
	"bytes"
	"fmt"
	"testing/fstest"

	"github.com/LarsArtmann/gogenfilter"
)

func ExampleNewFilter() {
	filter := gogenfilter.NewFilter(
		gogenfilter.Enabled(),
		gogenfilter.WithFilterOptions(
			gogenfilter.FilterSQLC,
			gogenfilter.FilterTempl,
			gogenfilter.FilterGeneric,
		),
	)

	fmt.Println(filter.IsEnabled())
	// Output: true
}

func ExampleNewFilter_withExcludePatterns() {
	filter := gogenfilter.NewFilter(
		gogenfilter.Enabled(),
		gogenfilter.WithFilterOptions(gogenfilter.FilterAll),
		gogenfilter.WithExcludePatterns("**/db/*.go"),
	)

	fmt.Println(filter.IsEnabled())
	// Output: true
}

func ExampleDetectReason() {
	sqlcContent := `// Code generated by sqlc. DO NOT EDIT.
// versions:
package db
`
	reason := gogenfilter.DetectReason(
		"db/models.go",
		sqlcContent,
		gogenfilter.FilterSQLC,
	)

	fmt.Println(reason)
	// Output: sqlc
}

func ExampleDetectReason_notFiltered() {
	reason := gogenfilter.DetectReason(
		"main.go",
		"package main\n",
		gogenfilter.FilterSQLC,
	)

	fmt.Println(reason)
	// Output: not-filtered
}

func ExampleMatchPattern() {
	fmt.Println(gogenfilter.MatchPattern("db/models.go", "**/*.go"))
	fmt.Println(gogenfilter.MatchPattern("db/models.go", "**/db/*.go"))
	fmt.Println(gogenfilter.MatchPattern("main.go", "**/db/*.go"))
	// Output:
	// true
	// true
	// false
}

func ExampleFilterReason_IsValid() {
	fmt.Println(gogenfilter.ReasonSQLC.IsValid())
	fmt.Println(gogenfilter.FilterReason("unknown").IsValid())
	// Output:
	// true
	// false
}

func ExampleFilterOption_IsValid() {
	fmt.Println(gogenfilter.FilterSQLC.IsValid())
	fmt.Println(gogenfilter.FilterOption("unknown").IsValid())
	// Output:
	// true
	// false
}

func ExampleAllFilterOptions() {
	opts := gogenfilter.AllFilterOptions()

	fmt.Println(len(opts))
	// Output: 12
}

func ExampleAllFilterReasons() {
	reasons := gogenfilter.AllFilterReasons()

	fmt.Println(len(reasons))
	// Output: 14
}

func ExampleFilter_ShouldFilter() {
	mapFS := fstest.MapFS{
		"db/models.go": &fstest.MapFile{
			Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
		},
	}

	filter := gogenfilter.NewFilter(
		gogenfilter.Enabled(),
		gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC),
		gogenfilter.WithFS(mapFS),
	)

	filtered, _ := filter.ShouldFilter("db/models.go")
	fmt.Println(filtered)
	// Output: true
}

func ExampleFilter_ShouldFilter_notFiltered() {
	mapFS := fstest.MapFS{
		"main.go": &fstest.MapFile{
			Data: []byte("package main\n"),
		},
	}

	filter := gogenfilter.NewFilter(
		gogenfilter.Enabled(),
		gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC),
		gogenfilter.WithFS(mapFS),
	)

	filtered, _ := filter.ShouldFilter("main.go")
	fmt.Println(filtered)
	// Output: false
}

func ExampleWithIncludePatterns() {
	mapFS := fstest.MapFS{
		"db/models.go": &fstest.MapFile{
			Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
		},
		"other/file.go": &fstest.MapFile{
			Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage other\n"),
		},
	}

	filter := gogenfilter.NewFilter(
		gogenfilter.Enabled(),
		gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC),
		gogenfilter.WithIncludePatterns("db/**"),
		gogenfilter.WithFS(mapFS),
	)

	dbFiltered, _ := filter.ShouldFilter("db/models.go")
	otherFiltered, _ := filter.ShouldFilter("other/file.go")
	fmt.Println(dbFiltered, otherFiltered)
	// Output: true true
}

func ExampleWithFS() {
	mapFS := fstest.MapFS{
		"generated.go": &fstest.MapFile{
			Data: []byte("// Code generated by stringer. DO NOT EDIT.\npackage foo\n"),
		},
	}

	filter := gogenfilter.NewFilter(
		gogenfilter.Enabled(),
		gogenfilter.WithFilterOptions(gogenfilter.FilterGeneric),
		gogenfilter.WithFS(mapFS),
	)

	filtered, _ := filter.ShouldFilter("generated.go")
	fmt.Println(filtered)
	// Output: true
}

func ExampleFilter_GetStats() {
	mapFS := fstest.MapFS{
		"db/models.go": &fstest.MapFile{
			Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
		},
		"main.go": &fstest.MapFile{
			Data: []byte("package main\n"),
		},
	}

	filter := gogenfilter.NewFilter(
		gogenfilter.Enabled(),
		gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC),
		gogenfilter.WithFS(mapFS),
	)

	filter.ShouldFilter("db/models.go")
	filter.ShouldFilter("main.go")

	stats := filter.GetStats()
	fmt.Println(stats.TotalFilesChecked)
	fmt.Println(stats.FilteredBy(gogenfilter.ReasonSQLC))
	fmt.Println(stats.TotalFiltered())
	// Output:
	// 2
	// 1
	// 1
}

func ExampleFilter_MustShouldFilter() {
	mapFS := fstest.MapFS{
		"db/models.go": &fstest.MapFile{
			Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
		},
	}

	filter := gogenfilter.NewFilter(
		gogenfilter.Enabled(),
		gogenfilter.WithFilterOptions(gogenfilter.FilterSQLC),
		gogenfilter.WithFS(mapFS),
	)

	fmt.Println(filter.MustShouldFilter("db/models.go"))
	// Output: true
}

func ExampleDetectReasonReader() {
	content := "// Code generated by sqlc. DO NOT EDIT.\npackage db\n"
	r := bytes.NewBufferString(content)

	reason, _ := gogenfilter.DetectReasonReader(
		"db/models.go",
		r,
		gogenfilter.FilterSQLC,
	)
	fmt.Println(reason)
	// Output: sqlc
}
