package gogenfilter

import (
	"bytes"
	"testing"
	"testing/fstest"
)

// TestFilterDetailedAndContent verifies the content-returning detection API.
// Each case maps to a row in the behavior matrix from the feedback proposal:
//
//	disabled filter               → nil content
//	include/exclude pattern match → nil content
//	phase 1 filename match        → nil content
//	no content-check detectors    → nil content
//	phase 2 ran (not filtered)    → content
//	phase 2 ran (filtered)       → content
//	read error                    → error + nil content
//	returned content matches file → correctness
func TestFilterDetailedAndContent(t *testing.T) {
	t.Parallel()

	// nilContentCases all expect content == nil (no file read occurred).
	nilContentCases := []struct {
		name     string
		filter   *Filter
		path     string
		filtered bool
		reason   FilterReason
	}{
		{
			name:     "disabled filter returns nil content and unfiltered result",
			filter:   mustNewFilter(t),
			path:     "any.go",
			filtered: false,
			reason:   "",
		},
		{
			name:     "include pattern scope returns nil content",
			filter:   mustNewFilter(t, WithIncludePatterns("pkg/*.go")),
			path:     "other/file.go",
			filtered: true,
			reason:   ReasonOutsideScope,
		},
		{
			name:     "exclude pattern match returns nil content",
			filter:   mustNewFilter(t, WithExcludePatterns("vendor/**")),
			path:     "vendor/util.go",
			filtered: true,
			reason:   ReasonExcludePattern,
		},
		{
			name: "phase 1 filename match returns nil content",
			filter: mustNewFilter(t,
				mustFilterOptions(t, FilterSQLC),
				WithFS(fstest.MapFS{
					"db/query.sql.go": newMapFile(
						"// Code generated by sqlc. DO NOT EDIT.\npackage db",
					),
				}),
			),
			path:     "db/query.sql.go",
			filtered: true,
			reason:   ReasonSQLC,
		},
		{
			name: "no content-check detectors returns nil content",
			// Enabled only via exclude patterns — no detector options,
			// so needsContentCheck returns false and no file is ever read.
			filter:   mustNewFilter(t, WithExcludePatterns("vendor/**")),
			path:     mainGo,
			filtered: false,
			reason:   ReasonNotFiltered,
		},
		{
			name: "config-aware sqlc detection returns nil content",
			// A models.go inside a configured sqlc output dir is caught by
			// phase 1.5 (configOrFilenameResult) — no file is read.
			filter: mustNewFilter(t,
				mustFilterOptions(t, FilterSQLC),
				WithFS(fstest.MapFS{
					"sqlc.yaml":    newMapFile(sqlcConfigV2YAML()),
					"db/models.go": newMapFile("package db\ntype User struct{}\n"),
				}),
			),
			path:     "db/models.go",
			filtered: true,
			reason:   ReasonSQLC,
		},
	}

	for _, tc := range nilContentCases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			result, content, err := tc.filter.FilterDetailedAndContent(tc.path)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			assertEqual(t, "Filtered", result.Filtered, tc.filtered)
			assertEqual(t, "Reason", result.Reason, tc.reason)
			assertEqual(t, "Path", result.Path, tc.path)
			assertNilContent(t, content)
		})
	}

	// contentCases all expect non-nil content read during phase 2.
	contentCases := []struct {
		name        string
		filter      *Filter
		path        string
		filtered    bool
		reason      FilterReason
		wantContent []byte
	}{
		{
			name: "phase 2 not filtered returns content",
			filter: mustNewFilter(t,
				mustFilterOptions(t, FilterSQLC),
				WithFS(fstest.MapFS{mainGo: newMapFile(packageMainFunc)}),
			),
			path:        mainGo,
			filtered:    false,
			reason:      ReasonNotFiltered,
			wantContent: []byte(packageMainFunc),
		},
		{
			name: "phase 2 filtered by content returns content",
			filter: mustNewFilter(t,
				mustFilterOptions(t, FilterSQLC),
				WithFS(fstest.MapFS{customGenGo: newMapFile(sqlcGeneratedContentTest)}),
			),
			// custom_gen.go has no SQLC filename heuristic, so phase 2 reads it.
			path:        customGenGo,
			filtered:    true,
			reason:      ReasonSQLC,
			wantContent: []byte(sqlcGeneratedContentTest),
		},
		{
			name: "generic content marker returns content",
			// The ReasonGeneric path — the primary motivation for this API.
			// art-dupl classifies generic-caught files via allowsContent(content).
			filter: mustNewFilter(t,
				mustFilterOptions(t, FilterGeneric),
				WithFS(fstest.MapFS{customGenGo: newMapFile(myToolGenContentTest)}),
			),
			path:        customGenGo,
			filtered:    true,
			reason:      ReasonGeneric,
			wantContent: []byte(myToolGenContentTest),
		},
	}

	for _, tc := range contentCases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			result, content, err := tc.filter.FilterDetailedAndContent(tc.path)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			assertEqual(t, "Filtered", result.Filtered, tc.filtered)
			assertEqual(t, "Reason", result.Reason, tc.reason)
			assertEqual(t, "Path", result.Path, tc.path)
			assertContentEquals(t, content, tc.wantContent)
		})
	}

	t.Run("read error returns error and nil content", func(t *testing.T) {
		t.Parallel()

		filter := mustNewFilter(t, mustFilterOptions(t, FilterSQLC))

		_, content, err := filter.FilterDetailedAndContent("nonexistent.go")
		if err == nil {
			t.Fatal("expected error for nonexistent file")
		}

		assertNilContent(t, content)
	})

	t.Run("config-aware sqlc detection returns nil content and config trace", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml":    newMapFile(sqlcConfigV2YAML()),
			"db/models.go": newMapFile("package db\ntype User struct{}\n"),
		}

		filter := mustNewFilter(t,
			mustFilterOptions(t, FilterSQLC),
			WithFS(fsys),
		)

		result, content, err := filter.FilterDetailedAndContent("db/models.go")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		assertEqual(t, "Filtered", result.Filtered, true)
		assertEqual(t, "Reason", result.Reason, ReasonSQLC)
		assertEqual(t, "Trace", result.Trace, sqlcConfigTrace)
		assertNilContent(t, content)
	})

	t.Run("returned content matches what fs.ReadFile returns", func(t *testing.T) {
		t.Parallel()

		expected := []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n")
		mapFS := fstest.MapFS{customGenGo: {Data: expected}}

		filter := mustNewFilter(t,
			mustFilterOptions(t, FilterSQLC),
			WithFS(mapFS),
		)

		_, content, err := filter.FilterDetailedAndContent(customGenGo)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		direct, err := readFile(filter.fsys, customGenGo)
		if err != nil {
			t.Fatalf("readFile error: %v", err)
		}

		assertContentEquals(t, content, direct)
		assertContentEquals(t, content, expected)
	})
}

func assertNilContent(t *testing.T, content []byte) {
	t.Helper()

	if content != nil {
		t.Errorf("expected nil content, got %d bytes: %q", len(content), content)
	}
}

func assertContentEquals(t *testing.T, got, want []byte) {
	t.Helper()

	if !bytes.Equal(got, want) {
		t.Errorf("content mismatch:\n got = %q\nwant = %q", got, want)
	}
}

// mustNewFilter builds a Filter from the given configs, failing the test on error.
func mustNewFilter(t *testing.T, configs ...FilterConfig) *Filter {
	t.Helper()

	filter, err := NewFilter(configs...)
	if err != nil {
		t.Fatalf("NewFilter error: %v", err)
	}

	return filter
}

// mustFilterOptions wraps WithFilterOptions, failing the test on error.
func mustFilterOptions(t *testing.T, opts ...FilterOption) FilterConfig {
	t.Helper()

	config, err := WithFilterOptions(opts...)
	if err != nil {
		t.Fatalf("WithFilterOptions error: %v", err)
	}

	return config
}
