package gogenfilter

import (
	"strings"
	"testing"
	"testing/fstest"
)

func TestFilterEdgeCases(t *testing.T) {
	t.Parallel()

	t.Run("empty path returns error", func(t *testing.T) {
		t.Parallel()

		filter := NewFilter(WithFilterOptions(FilterAll))

		_, err := filter.Filter("")
		if err == nil {
			t.Error("expected error for empty path")
		}
	})

	t.Run("special characters in path", func(t *testing.T) {
		t.Parallel()

		type tc struct {
			name     string
			filePath string
			content  string
		}

		cases := []tc{
			{
				name:     "spaces in path",
				filePath: "path with spaces/models.go",
				content:  "// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
			},
			{
				name:     "unicode filename",
				filePath: "dönner/models.go",
				content:  "// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
			},
		}

		for _, caze := range cases {
			t.Run(caze.name, func(t *testing.T) {
				t.Parallel()

				mapFS := fstest.MapFS{
					caze.filePath: newMapFile(caze.content),
				}

				assertFilter(t, mapFS, caze.filePath, true)
			})
		}
	})

	t.Run("very long filename", func(t *testing.T) {
		t.Parallel()

		longName := strings.Repeat("a", 200) + ".go"

		mapFS := fstest.MapFS{
			longName: newMapFile("package main\n"),
		}

		filter := NewFilter(WithFilterOptions(FilterAll), WithFS(mapFS))

		filtered, err := filter.Filter(longName)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if filtered {
			t.Error("expected long-named regular file to not be filtered")
		}
	})

	t.Run("nil FS defaults to OS filesystem", func(t *testing.T) {
		t.Parallel()

		filter := NewFilter(WithFilterOptions(FilterAll), WithFS(nil))

		filtered, err := filter.Filter("nonexistent_deffile_12345.go")
		if err == nil {
			t.Error("expected error for nonexistent file with OS FS")
		}

		if filtered {
			t.Error("expected nonexistent file to not be filtered even on error")
		}
	})
}
