package gogenfilter

import (
	"os"
	"path/filepath"
	"testing"
	"testing/fstest"
)

func TestNewFilter(t *testing.T) {
	t.Run("creates disabled filter", func(t *testing.T) {
		t.Parallel()

		f := NewFilter(false, nil)

		if f.IsEnabled() {
			t.Error("Expected disabled filter")
		}

		if len(f.options) != 0 {
			t.Errorf("Expected empty options, got %v", f.options)
		}
	})

	t.Run("creates enabled filter with options", func(t *testing.T) {
		t.Parallel()

		f := NewFilter(true, []FilterOption{FilterSQLC, FilterTempl})

		if !f.IsEnabled() {
			t.Error("Expected enabled filter")
		}

		if !f.options[FilterSQLC] {
			t.Error("Expected SQLC option enabled")
		}

		if !f.options[FilterTempl] {
			t.Error("Expected Templ option enabled")
		}
	})

	t.Run("creates enabled filter with FilterAll", func(t *testing.T) {
		t.Parallel()

		f := NewFilter(true, []FilterOption{FilterAll})

		if !f.IsEnabled() {
			t.Error("Expected enabled filter")
		}

		for _, opt := range allSpecificOptions {
			if !f.options[opt] {
				t.Errorf("Expected %s option enabled for FilterAll", opt)
			}
		}

		if !f.options[FilterGeneric] {
			t.Error("Expected Generic option enabled for FilterAll")
		}
	})
}

func TestShouldFilter(t *testing.T) {
	t.Run("disabled filter never filters", func(t *testing.T) {
		t.Parallel()

		f := NewFilter(false, []FilterOption{FilterAll})

		if f.ShouldFilter("any/file.go") {
			t.Error("Disabled filter should not filter")
		}
	})
}

func TestShouldFilterWithIncludes(t *testing.T) {
	t.Parallel()

	t.Run("matching include pattern is not filtered", func(t *testing.T) {
		t.Parallel()

		filter := NewFilter(true, []FilterOption{FilterSQLC})
		filter.WithIncludePatterns([]string{"models.go"})

		if filter.ShouldFilter("models.go") {
			t.Error("expected matching include pattern to not be filtered")
		}
	})

	t.Run("non-matching path is filtered with include reason", func(t *testing.T) {
		t.Parallel()

		filter := NewFilter(true, nil)
		filter.WithIncludePatterns([]string{"pkg/*.go"})

		if !filter.ShouldFilter("other/file.go") {
			t.Error("expected non-matching path to be filtered")
		}

		stats := filter.GetStats()

		if stats.FilteredBy(ReasonIncludePattern) != 1 {
			t.Errorf(
				"expected 1 include-pattern filter, got %d",
				stats.FilteredBy(ReasonIncludePattern),
			)
		}
	})

	t.Run("include pattern with wildcard", func(t *testing.T) {
		t.Parallel()

		filter := NewFilter(true, nil)
		filter.WithIncludePatterns([]string{"*.go"})

		if filter.ShouldFilter("main.go") {
			t.Error("expected *.go to match main.go")
		}
	})
}

func TestShouldFilterWithIncludesMultiple(t *testing.T) {
	t.Parallel()

	filter := NewFilter(true, nil)
	filter.WithIncludePatterns([]string{"keep.go", "safe.go"})

	if filter.ShouldFilter("keep.go") {
		t.Error("expected keep.go to match")
	}

	if filter.ShouldFilter("safe.go") {
		t.Error("expected safe.go to match")
	}

	if !filter.ShouldFilter("remove.go") {
		t.Error("expected remove.go to be filtered")
	}
}

func TestShouldFilterIntegration(t *testing.T) {
	t.Parallel()

	for _, tt := range shouldFilterTestCases() {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			assertFilterBehavior(t, tt.fileName, tt.content, tt.opts, tt.shouldFilter)
		})
	}
}

func TestFilterWithMetrics(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()

	files := map[string]string{
		"db/models.go": "// Code generated by sqlc. DO NOT EDIT.\npackage db\ntype User struct{ ID int64 }",
		"main.go":      "package main\nfunc main() {}",
		"components/header_templ.go": "// Code generated by templ DO NOT EDIT\n\npackage components\n\n" +
			"import \"github.com/a-h/templ\"\n\nfunc Header() templ.Component { return nil }",
		"enums/status_enum.go": "// Code generated by go-enum DO NOT EDIT.\npackage enums\n" +
			"type Status int\nconst StatusPending Status = iota",
	}

	for name, content := range files {
		dir := filepath.Join(tmpDir, filepath.Dir(name))

		err := os.MkdirAll(dir, 0o750)
		if err != nil {
			t.Fatalf("Failed to create dir: %v", err)
		}

		err = os.WriteFile(
			filepath.Join(tmpDir, name),
			[]byte(content),
			0o600,
		)
		if err != nil {
			t.Fatalf("Failed to write file: %v", err)
		}
	}

	fltr := NewFilter(true, []FilterOption{FilterAll})
	fltr.WithFS(os.DirFS(tmpDir))

	for name := range files {
		_ = fltr.ShouldFilter(name)
	}

	stats := fltr.GetStats()

	assertEqual(t, "TotalFilesChecked", stats.TotalFilesChecked, 4)
	assertEqual(t, "SQLC filtered", stats.FilteredBy(ReasonSQLC), 1)
	assertEqual(t, "Templ filtered", stats.FilteredBy(ReasonTempl), 1)
	assertEqual(t, "GoEnum filtered", stats.FilteredBy(ReasonGoEnum), 1)
	assertEqual(t, "TotalFiltered", stats.TotalFiltered(), 3)
}

func TestGetStatsDisabledFilter(t *testing.T) {
	t.Parallel()

	f := NewFilter(false, nil)
	stats := f.GetStats()

	assertEqual(t, "TotalFilesChecked", stats.TotalFilesChecked, 0)
	assertEqual(t, "TotalFiltered", stats.TotalFiltered(), 0)
	assertEqual(t, "FilteredBy SQLC", stats.FilteredBy(ReasonSQLC), 0)
}

func TestShouldFilterExcludePattern(t *testing.T) {
	t.Parallel()

	filter := NewFilter(true, []FilterOption{FilterSQLC})
	filter.WithExcludePatterns([]string{"**/db/*.go"})

	tmpDir := t.TempDir()

	dbDir := filepath.Join(tmpDir, "db")

	mkdirAll(t, dbDir)

	tmpFile := filepath.Join(dbDir, "models.go")
	writeFile(t, tmpFile, "// Code generated by sqlc. DO NOT EDIT.\npackage db\n")

	filter.WithFS(os.DirFS(tmpDir))

	if !filter.ShouldFilter(filepath.Join("db", "models.go")) {
		t.Error("expected exclude pattern match to be filtered")
	}

	stats := filter.GetStats()

	if stats.FilteredBy(ReasonExcludePattern) != 1 {
		t.Errorf(
			"expected 1 exclude-pattern filter, got %d",
			stats.FilteredBy(ReasonExcludePattern),
		)
	}
}

func TestWithPatterns(t *testing.T) {
	t.Parallel()

	testCases := []patternTestCase{
		{
			name:     "include patterns",
			setter:   func(f *Filter) { f.WithIncludePatterns([]string{"vendor/*", "generated/keep.go"}) },
			getter:   func(f *Filter) []string { return f.includePatterns },
			patterns: []string{"vendor/*", "generated/keep.go"},
		},
		{
			name:     "exclude patterns",
			setter:   func(f *Filter) { f.WithExcludePatterns([]string{"test/*", "*.pb.go"}) },
			getter:   func(f *Filter) []string { return f.excludePatterns },
			patterns: []string{"test/*", "*.pb.go"},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			f := NewFilter(true, []FilterOption{FilterAll})
			testPatternSetter(t, f, tc.setter, tc.getter, len(tc.patterns))
		})
	}
}

func TestFilterWithMapFS(t *testing.T) {
	t.Parallel()

	t.Run("detects sqlc via fstest.MapFS", testMapFSDetectsSQLC)
	t.Run("does not filter non-generated file", testMapFSNonGenerated)
	t.Run("non-existent file returns not filtered", testMapFSNonExistent)
	t.Run("WithFS ignores nil", testMapFSWithNilIgnored)
	t.Run("multiple generators via MapFS", testMapFSMultipleGenerators)
}

func testMapFSDetectsSQLC(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		"db/models.go": newMapFile(
			"// Code generated by sqlc. DO NOT EDIT.\n" +
				"package db\n" +
				"type User struct{ ID int64 }",
		),
	}

	fltr := NewFilter(true, []FilterOption{FilterSQLC})
	fltr.WithFS(mapFS)

	if !fltr.ShouldFilter("db/models.go") {
		t.Error("expected sqlc-generated file to be filtered")
	}

	stats := fltr.GetStats()
	assertEqual(t, "SQLC filtered", stats.FilteredBy(ReasonSQLC), 1)
}

func testMapFSNonGenerated(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		"main.go": newMapFile("package main\nfunc main() {}"),
	}

	fltr := NewFilter(true, []FilterOption{FilterAll})
	fltr.WithFS(mapFS)

	if fltr.ShouldFilter("main.go") {
		t.Error("expected non-generated file to not be filtered")
	}
}

func testMapFSNonExistent(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{}

	fltr := NewFilter(true, []FilterOption{FilterSQLC})
	fltr.WithFS(mapFS)

	if fltr.ShouldFilter("nonexistent.go") {
		t.Error("expected non-existent file to not be filtered")
	}
}

func testMapFSWithNilIgnored(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		"models.go": newMapFile(
			"// Code generated by sqlc. DO NOT EDIT.\n" +
				"package db\n",
		),
	}

	fltr := NewFilter(true, []FilterOption{FilterSQLC})
	fltr.WithFS(mapFS)
	fltr.WithFS(nil)

	if !fltr.ShouldFilter("models.go") {
		t.Error("expected WithFS(nil) to keep the previous filesystem")
	}
}

func testMapFSMultipleGenerators(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		"db/models.go": newMapFile(
			"// Code generated by sqlc. DO NOT EDIT.\n" +
				"package db\n",
		),
		"components/header_templ.go": newMapFile(
			"// Code generated by templ DO NOT EDIT\n" +
				"package components\n" +
				"import \"github.com/a-h/templ\"\n" +
				"func Header() templ.Component { return nil }",
		),
		"main.go": newMapFile("package main\nfunc main() {}"),
	}

	fltr := NewFilter(true, []FilterOption{FilterAll})
	fltr.WithFS(mapFS)

	_ = fltr.ShouldFilter("db/models.go")
	_ = fltr.ShouldFilter("components/header_templ.go")
	_ = fltr.ShouldFilter("main.go")

	stats := fltr.GetStats()
	assertEqual(t, "TotalFilesChecked", stats.TotalFilesChecked, 3)
	assertEqual(t, "SQLC filtered", stats.FilteredBy(ReasonSQLC), 1)
	assertEqual(t, "Templ filtered", stats.FilteredBy(ReasonTempl), 1)
	assertEqual(t, "TotalFiltered", stats.TotalFiltered(), 2)
}

func TestFindSQLCConfigsFSWithMapFS(t *testing.T) {
	t.Parallel()

	t.Run("finds sqlc.yaml in MapFS", testFindSQLCConfig("sqlc.yaml", validSQLCConfig))
	t.Run("finds sqlc.yml in subdirectory", testFindSQLCConfig("internal/db/sqlc.yml", validSQLCConfigMySQL))
	t.Run("skips dot directories", testFindSQLCSkipsDotDirs)
	t.Run("no configs returns empty map", testFindSQLCSkipsDotDirs)
}

func testFindSQLCConfig(path, configContent string) func(t *testing.T) {
	return func(t *testing.T) {
		t.Parallel()

		mapFS := fstest.MapFS{
			path: newMapFile(configContent),
		}

		testFindSQLCConfigCount(t, mapFS, 1)
	}
}

func testFindSQLCSkipsDotDirs(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		".git/sqlc.yaml": newMapFile("version: \"2\"\n"),
	}

	testFindSQLCConfigCount(t, mapFS, 0)
}

func testFindSQLCConfigCount(t *testing.T, mapFS fstest.MapFS, expected int) {
	t.Helper()

	configs, err := FindSQLCConfigsFS(mapFS, []string{"."})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(configs) != expected {
		t.Errorf("expected %d configs, got %d", expected, len(configs))
	}
}

func TestGetSQLOutputDirsFSWithMapFS(t *testing.T) {
	t.Parallel()

	t.Run("extracts output dirs from config", testOutputDirsFromConfig)
	t.Run("no configs returns empty slice", testOutputDirsNoConfigs)
	t.Run("invalid yaml returns error", testOutputDirsInvalidYAML)
}

func testOutputDirsFromConfig(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		"sqlc.yaml": newMapFile(validSQLCConfig),
	}

	dirs, err := GetSQLOutputDirsFS(mapFS, []string{"."})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(dirs) != 1 {
		t.Fatalf("expected 1 output dir, got %d: %v", len(dirs), dirs)
	}

	assertEqual(t, "output dir", dirs[0], "db")
}

func testOutputDirsNoConfigs(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{}

	dirs, err := GetSQLOutputDirsFS(mapFS, []string{"."})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(dirs) != 0 {
		t.Errorf("expected 0 dirs, got %d", len(dirs))
	}
}

func testOutputDirsInvalidYAML(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		"sqlc.yaml": newMapFile("{{invalid yaml"),
	}

	_, err := GetSQLOutputDirsFS(mapFS, []string{"."})
	if err == nil {
		t.Error("expected error for invalid yaml")
	}
}

func TestParseSQLCConfigFSWithMapFS(t *testing.T) {
	t.Parallel()

	t.Run("parses valid config", testParseValidConfig)
	t.Run("non-existent file returns error", testParseNonExistent)
}

func testParseValidConfig(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		"sqlc.yaml": newMapFile(
			"version: \"2\"\n" +
				"sql:\n" +
				"  - engine: \"postgresql\"\n" +
				"    gen:\n" +
				"      go:\n" +
				"        package: \"db\"\n" +
				"        out: \"db\"\n",
		),
	}

	config, err := parseSQLCConfigFS(mapFS, "sqlc.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	assertEqual(t, "version", config.Version, "2")
	assertEqual(t, "SQL engines", len(config.SQL), 1)
	assertEqual(t, "out dir", config.SQL[0].Gen.Go.Out, "db")
}

func testParseNonExistent(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{}

	_, err := parseSQLCConfigFS(mapFS, "missing.yaml")
	if err == nil {
		t.Error("expected error for missing file")
	}
}
