package gogenfilter

import (
	"os"
	"path/filepath"
	"testing"
)

func TestNewFilter(t *testing.T) {
	t.Run("creates disabled filter", func(t *testing.T) {
		t.Parallel()

		f := NewFilter(false, nil)

		if f.IsEnabled() {
			t.Error("Expected disabled filter")
		}

		if len(f.options) != 0 {
			t.Errorf("Expected empty options, got %v", f.options)
		}
	})

	t.Run("creates enabled filter with options", func(t *testing.T) {
		t.Parallel()

		f := NewFilter(true, []FilterOption{FilterSQLC, FilterTempl})

		if !f.IsEnabled() {
			t.Error("Expected enabled filter")
		}

		if !f.options[FilterSQLC] {
			t.Error("Expected SQLC option enabled")
		}

		if !f.options[FilterTempl] {
			t.Error("Expected Templ option enabled")
		}
	})

	t.Run("creates enabled filter with FilterAll", func(t *testing.T) {
		t.Parallel()

		f := NewFilter(true, []FilterOption{FilterAll})

		if !f.IsEnabled() {
			t.Error("Expected enabled filter")
		}

		for _, opt := range allSpecificOptions {
			if !f.options[opt] {
				t.Errorf("Expected %s option enabled for FilterAll", opt)
			}
		}

		if !f.options[FilterGeneric] {
			t.Error("Expected Generic option enabled for FilterAll")
		}
	})
}

func TestShouldFilter(t *testing.T) {
	t.Run("disabled filter never filters", func(t *testing.T) {
		t.Parallel()

		f := NewFilter(false, []FilterOption{FilterAll})

		if f.ShouldFilter("any/file.go") {
			t.Error("Disabled filter should not filter")
		}
	})
}

func TestShouldFilterWithIncludes(t *testing.T) {
	t.Parallel()

	t.Run("matching include pattern is not filtered", func(t *testing.T) {
		t.Parallel()

		filter := NewFilter(true, []FilterOption{FilterSQLC})
		filter.WithIncludePatterns([]string{"models.go"})

		if filter.ShouldFilter("models.go") {
			t.Error("expected matching include pattern to not be filtered")
		}
	})

	t.Run("non-matching path is filtered with include reason", func(t *testing.T) {
		t.Parallel()

		filter := NewFilter(true, nil)
		filter.WithIncludePatterns([]string{"pkg/*.go"})

		if !filter.ShouldFilter("other/file.go") {
			t.Error("expected non-matching path to be filtered")
		}

		stats := filter.GetStats()

		if stats.FilteredBy(ReasonIncludePattern) != 1 {
			t.Errorf(
				"expected 1 include-pattern filter, got %d",
				stats.FilteredBy(ReasonIncludePattern),
			)
		}
	})

	t.Run("include pattern with wildcard", func(t *testing.T) {
		t.Parallel()

		filter := NewFilter(true, nil)
		filter.WithIncludePatterns([]string{"*.go"})

		if filter.ShouldFilter("main.go") {
			t.Error("expected *.go to match main.go")
		}
	})
}

func TestShouldFilterWithIncludesMultiple(t *testing.T) {
	t.Parallel()

	filter := NewFilter(true, nil)
	filter.WithIncludePatterns([]string{"keep.go", "safe.go"})

	if filter.ShouldFilter("keep.go") {
		t.Error("expected keep.go to match")
	}

	if filter.ShouldFilter("safe.go") {
		t.Error("expected safe.go to match")
	}

	if !filter.ShouldFilter("remove.go") {
		t.Error("expected remove.go to be filtered")
	}
}

func TestShouldFilterIntegration(t *testing.T) {
	t.Parallel()

	for _, tt := range shouldFilterTestCases() {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			assertFilterBehavior(t, tt.fileName, tt.content, tt.opts, tt.shouldFilter)
		})
	}
}

func TestFilterWithMetrics(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()

	files := map[string]string{
		"db/models.go": "// Code generated by sqlc. DO NOT EDIT.\npackage db\ntype User struct{ ID int64 }",
		"main.go":      "package main\nfunc main() {}",
		"components/header_templ.go": "// Code generated by templ DO NOT EDIT\n\npackage components\n\n" +
			"import \"github.com/a-h/templ\"\n\nfunc Header() templ.Component { return nil }",
		"enums/status_enum.go": "// Code generated by go-enum DO NOT EDIT.\npackage enums\n" +
			"type Status int\nconst StatusPending Status = iota",
	}

	for name, content := range files {
		dir := filepath.Join(tmpDir, filepath.Dir(name))

		err := os.MkdirAll(dir, 0o750)
		if err != nil {
			t.Fatalf("Failed to create dir: %v", err)
		}

		err = os.WriteFile(
			filepath.Join(tmpDir, name),
			[]byte(content),
			0o600,
		)
		if err != nil {
			t.Fatalf("Failed to write file: %v", err)
		}
	}

	fltr := NewFilter(true, []FilterOption{FilterAll})

	for name := range files {
		filePath := filepath.Join(tmpDir, name)

		_ = fltr.ShouldFilter(filePath)
	}

	stats := fltr.GetStats()

	assertEqual(t, "TotalFilesChecked", stats.TotalFilesChecked, 4)
	assertEqual(t, "SQLC filtered", stats.FilteredBy(ReasonSQLC), 1)
	assertEqual(t, "Templ filtered", stats.FilteredBy(ReasonTempl), 1)
	assertEqual(t, "GoEnum filtered", stats.FilteredBy(ReasonGoEnum), 1)
	assertEqual(t, "TotalFiltered", stats.TotalFiltered(), 3)
}

func TestGetStatsDisabledFilter(t *testing.T) {
	t.Parallel()

	f := NewFilter(false, nil)
	stats := f.GetStats()

	assertEqual(t, "TotalFilesChecked", stats.TotalFilesChecked, 0)
	assertEqual(t, "TotalFiltered", stats.TotalFiltered(), 0)
	assertEqual(t, "FilteredBy SQLC", stats.FilteredBy(ReasonSQLC), 0)
}

func TestShouldFilterExcludePattern(t *testing.T) {
	t.Parallel()

	filter := NewFilter(true, []FilterOption{FilterSQLC})
	filter.WithExcludePatterns([]string{"**/db/*.go"})

	tmpDir := t.TempDir()

	dbDir := filepath.Join(tmpDir, "db")

	mkdirAll(t, dbDir)

	tmpFile := filepath.Join(dbDir, "models.go")
	writeFile(t, tmpFile, "// Code generated by sqlc. DO NOT EDIT.\npackage db\n")

	if !filter.ShouldFilter(tmpFile) {
		t.Error("expected exclude pattern match to be filtered")
	}

	stats := filter.GetStats()

	if stats.FilteredBy(ReasonExcludePattern) != 1 {
		t.Errorf(
			"expected 1 exclude-pattern filter, got %d",
			stats.FilteredBy(ReasonExcludePattern),
		)
	}
}

func TestWithPatterns(t *testing.T) {
	t.Parallel()

	testCases := []patternTestCase{
		{
			name:     "include patterns",
			setter:   func(f *Filter) { f.WithIncludePatterns([]string{"vendor/*", "generated/keep.go"}) },
			getter:   func(f *Filter) []string { return f.includePatterns },
			patterns: []string{"vendor/*", "generated/keep.go"},
		},
		{
			name:     "exclude patterns",
			setter:   func(f *Filter) { f.WithExcludePatterns([]string{"test/*", "*.pb.go"}) },
			getter:   func(f *Filter) []string { return f.excludePatterns },
			patterns: []string{"test/*", "*.pb.go"},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			f := NewFilter(true, []FilterOption{FilterAll})
			testPatternSetter(t, f, tc.setter, tc.getter, len(tc.patterns))
		})
	}
}
