package gogenfilter

import (
	"testing"
	"testing/fstest"
)

func newAllFilterWithFS(fsys fstest.MapFS) *Filter {
	opts, err := WithFilterOptions(FilterAll)
	if err != nil {
		panic(err)
	}

	filter, err := NewFilter(opts, WithFS(fsys))
	if err != nil {
		panic(err)
	}

	return filter
}

func TestFilterWithContent(t *testing.T) {
	t.Parallel()

	t.Run("detects generated from content without file I/O", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{}
		filter := newAllFilterWithFS(fsys)

		content := []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n")

		filtered, err := filter.FilterWithContent("models.go", content)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if !filtered {
			t.Error("expected filtered=true for sqlc content")
		}
	})

	t.Run("detects via filename with nil content", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{}
		filter := newAllFilterWithFS(fsys)

		filtered, err := filter.FilterWithContent("page_templ.go", nil)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if !filtered {
			t.Error("expected filtered=true for templ filename")
		}
	})

	t.Run("returns false for regular file", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{}
		filter := newAllFilterWithFS(fsys)

		filtered, err := filter.FilterWithContent(mainGo, []byte(packageMainFunc))
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if filtered {
			t.Error("expected filtered=false for regular file")
		}
	})

	t.Run("returns false when disabled", func(t *testing.T) {
		t.Parallel()

		filter, err := NewFilter()
		if err != nil {
			t.Fatal(err)
		}

		filtered, err := filter.FilterWithContent("models.go", []byte(sqlcGeneratedContentTest))
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if filtered {
			t.Error("expected filtered=false for disabled filter")
		}
	})

	t.Run("respects exclude patterns", func(t *testing.T) {
		t.Parallel()

		opts, err := WithFilterOptions(FilterAll)
		if err != nil {
			t.Fatal(err)
		}

		filter, err := NewFilter(opts, WithExcludePatterns("vendor/**"))
		if err != nil {
			t.Fatal(err)
		}

		filtered, err := filter.FilterWithContent("vendor/foo.go", []byte(packageMainFunc))
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if !filtered {
			t.Error("expected filtered=true for excluded path")
		}
	})

	t.Run("empty content triggers filename-only check", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{}
		filter := newAllFilterWithFS(fsys)

		filtered, err := filter.FilterWithContent(mainGo, []byte{})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if filtered {
			t.Error("expected filtered=false for regular file with empty content")
		}
	})

	t.Run("respects include patterns", func(t *testing.T) {
		t.Parallel()

		opts, err := WithFilterOptions(FilterAll)
		if err != nil {
			t.Fatal(err)
		}

		filter, err := NewFilter(opts, WithIncludePatterns("pkg/**"))
		if err != nil {
			t.Fatal(err)
		}

		filtered, err := filter.FilterWithContent(
			"other/models.go",
			[]byte(sqlcGeneratedContentTest),
		)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if !filtered {
			t.Error("expected filtered=true for outside include scope")
		}
	})
}

func TestFilterDetailedWithContent(t *testing.T) {
	t.Parallel()

	t.Run("returns reason and trace from content", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{}
		filter := newAllFilterWithFS(fsys)

		content := []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n")

		result, err := filter.FilterDetailedWithContent("models.go", content)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if !result.Filtered {
			t.Error("expected filtered=true")
		}

		if result.Reason != ReasonSQLC {
			t.Errorf("expected reason=%v, got %v", ReasonSQLC, result.Reason)
		}

		if result.Trace == "" {
			t.Error("expected non-empty trace")
		}
	})

	t.Run("returns filename-based trace with nil content", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{}
		filter := newAllFilterWithFS(fsys)

		result, err := filter.FilterDetailedWithContent("page_templ.go", nil)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if !result.Filtered {
			t.Error("expected filtered=true")
		}

		if result.Reason != ReasonTempl {
			t.Errorf("expected reason=%v, got %v", ReasonTempl, result.Reason)
		}

		if result.Trace == "" {
			t.Error("expected non-empty trace")
		}
	})

	t.Run("returns not-filtered for regular file", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{}
		filter := newAllFilterWithFS(fsys)

		result, err := filter.FilterDetailedWithContent(mainGo, []byte(packageMainFunc))
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.Filtered {
			t.Error("expected filtered=false")
		}

		if result.Reason != ReasonNotFiltered {
			t.Errorf("expected reason=%v, got %v", ReasonNotFiltered, result.Reason)
		}
	})

	t.Run("returns disabled result when filter disabled", func(t *testing.T) {
		t.Parallel()

		filter, err := NewFilter()
		if err != nil {
			t.Fatal(err)
		}

		result, err := filter.FilterDetailedWithContent(
			"models.go",
			[]byte(sqlcGeneratedContentTest),
		)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.Filtered {
			t.Error("expected filtered=false for disabled filter")
		}
	})

	t.Run("respects include patterns", func(t *testing.T) {
		t.Parallel()

		opts, err := WithFilterOptions(FilterAll)
		if err != nil {
			t.Fatal(err)
		}

		filter, err := NewFilter(opts, WithIncludePatterns("pkg/**"))
		if err != nil {
			t.Fatal(err)
		}

		result, err := filter.FilterDetailedWithContent(
			"other/models.go",
			[]byte(sqlcGeneratedContentTest),
		)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if !result.Filtered {
			t.Error("expected filtered=true for outside include scope")
		}

		if result.Reason != ReasonOutsideScope {
			t.Errorf("expected reason=%v, got %v", ReasonOutsideScope, result.Reason)
		}
	})

	t.Run("respects exclude patterns", func(t *testing.T) {
		t.Parallel()

		opts, err := WithFilterOptions(FilterAll)
		if err != nil {
			t.Fatal(err)
		}

		filter, err := NewFilter(opts, WithExcludePatterns("vendor/**"))
		if err != nil {
			t.Fatal(err)
		}

		result, err := filter.FilterDetailedWithContent(
			"vendor/models.go",
			[]byte(sqlcGeneratedContentTest),
		)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if !result.Filtered {
			t.Error("expected filtered=true for excluded path")
		}

		if result.Reason != ReasonExcludePattern {
			t.Errorf("expected reason=%v, got %v", ReasonExcludePattern, result.Reason)
		}
	})

	t.Run("detects via filename with empty content", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{}
		filter := newAllFilterWithFS(fsys)

		result, err := filter.FilterDetailedWithContent("page_templ.go", []byte{})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if !result.Filtered {
			t.Error("expected filtered=true for templ filename")
		}

		if result.Reason != ReasonTempl {
			t.Errorf("expected reason=%v, got %v", ReasonTempl, result.Reason)
		}
	})
}
