package gogenfilter

import (
	"os"
	"path/filepath"
	"testing"
	"testing/fstest"
)

func TestFilterWithMapFS(t *testing.T) {
	t.Parallel()

	t.Run("detects sqlc via fstest.MapFS", testMapFSDetectsSQLC)
	t.Run("does not filter non-generated file", testMapFSNonGenerated)
	t.Run("non-existent file returns not filtered", testMapFSNonExistent)
	t.Run("multiple generators via MapFS", testMapFSMultipleGenerators)
}

func testMapFSDetectsSQLC(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		"db/models.go": newMapFile(
			"// Code generated by sqlc. DO NOT EDIT.\n" +
				"package db\n" +
				"type User struct{ ID int64 }",
		),
	}

	opts, err := WithFilterOptions(FilterSQLC)
	if err != nil {
		t.Fatal(err)
	}

	fltr, err := NewFilter(opts, WithFS(mapFS))
	if err != nil {
		t.Fatal(err)
	}

	if !mustFilter(t, fltr, "db/models.go") {
		t.Error("expected sqlc-generated file to be filtered")
	}
}

func testMapFSNonGenerated(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		mainGo: newMapFile(packageMainFunc),
	}

	opts, err := WithFilterOptions(FilterAll)
	if err != nil {
		t.Fatal(err)
	}

	fltr, err := NewFilter(opts, WithFS(mapFS))
	if err != nil {
		t.Fatal(err)
	}

	if mustFilter(t, fltr, "main.go") {
		t.Error("expected non-generated file to not be filtered")
	}
}

func testMapFSNonExistent(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{}

	opts, err := WithFilterOptions(FilterSQLC)
	if err != nil {
		t.Fatal(err)
	}

	fltr, err := NewFilter(opts, WithFS(mapFS))
	if err != nil {
		t.Fatal(err)
	}

	_, err = fltr.Filter("nonexistent.go")
	if err == nil {
		t.Error("expected error for non-existent file")
	}
}

func testMapFSMultipleGenerators(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		dbModelsGo: newMapFile(
			"// Code generated by sqlc. DO NOT EDIT.\n" +
				"package db\n",
		),
		"components/header_templ.go": newMapFile(
			"// Code generated by templ DO NOT EDIT\n" +
				"package components\n" +
				"import \"github.com/a-h/templ\"\n" +
				"func Header() templ.Component { return nil }",
		),
		mainGo: newMapFile(packageMainFunc),
	}

	opts, err := WithFilterOptions(FilterAll)
	if err != nil {
		t.Fatal(err)
	}

	fltr, err := NewFilter(opts, WithFS(mapFS))
	if err != nil {
		t.Fatal(err)
	}

	_, _ = fltr.Filter("db/models.go")
	_, _ = fltr.Filter("components/header_templ.go")
	_, _ = fltr.Filter("main.go")
}

func TestFindSQLCConfigsFSWithMapFS(t *testing.T) {
	t.Parallel()

	t.Run("finds sqlc.yaml in MapFS",
		testFindSQLCConfig("sqlc.yaml", ValidSQLCConfig("postgresql")))
	t.Run("finds sqlc.yml in subdirectory",
		testFindSQLCConfig("internal/db/sqlc.yml", ValidSQLCConfig("mysql")))
	t.Run("skips dot directories", testFindSQLCSkipsDotDirs)
	t.Run("no configs returns empty map", testFindSQLCSkipsDotDirs)
}

func testFindSQLCConfig(path, configContent string) func(t *testing.T) {
	return func(t *testing.T) {
		t.Parallel()

		mapFS := fstest.MapFS{
			path: newMapFile(configContent),
		}

		testFindSQLCConfigCount(t, mapFS, 1)
	}
}

func testFindSQLCSkipsDotDirs(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		".git/sqlc.yaml": newMapFile("version: \"2\"\n"),
	}

	testFindSQLCConfigCount(t, mapFS, 0)
}

func testFindSQLCConfigCount(t *testing.T, mapFS fstest.MapFS, expected int) {
	t.Helper()

	configs, err := FindSQLCConfigsFS(mapFS, []string{"."})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	assertMapLen(t, "configs", configs, expected)
}

func TestGetSQLOutputDirsFSWithMapFS(t *testing.T) {
	t.Parallel()

	t.Run("extracts output dirs from config", testOutputDirsFromConfig)
	t.Run("no configs returns empty slice", testOutputDirsNoConfigs)
	t.Run("invalid yaml returns error", testOutputDirsInvalidYAML)
}

func testOutputDirsFromConfig(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		testFileSQLCConfig: newMapFile(ValidSQLCConfig("postgresql")),
	}

	dirs, err := GetSQLOutputDirsFS(mapFS, []string{"."})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(dirs) != 1 {
		t.Fatalf("expected 1 output dir, got %d: %v", len(dirs), dirs)
	}

	assertEqual(t, "output dir", dirs[0], "db")
}

func testOutputDirsNoConfigs(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{}

	dirs, err := GetSQLOutputDirsFS(mapFS, []string{"."})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if len(dirs) != 0 {
		t.Errorf("expected 0 dirs, got %d", len(dirs))
	}
}

func testOutputDirsInvalidYAML(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		"sqlc.yaml": newMapFile("{{invalid yaml"),
	}

	_, err := GetSQLOutputDirsFS(mapFS, []string{"."})
	if err == nil {
		t.Error("expected error for invalid yaml")
	}
}

func TestParseSQLCConfigFSWithMapFS(t *testing.T) {
	t.Parallel()

	t.Run("parses valid config", testParseValidConfig)
	t.Run("non-existent file returns error", testParseNonExistent)
}

func testParseValidConfig(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		"sqlc.yaml": newMapFile(
			"version: \"2\"\n" +
				"sql:\n" +
				"  - engine: \"postgresql\"\n" +
				"    gen:\n" +
				"      go:\n" +
				"        package: \"db\"\n" +
				"        out: \"db\"\n",
		),
	}

	config, err := parseSQLCConfigFS(mapFS, "sqlc.yaml")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	assertEqual(t, "version", config.Version, "2")
	assertEqual(t, "SQL engines", len(config.SQL), 1)
	assertEqual(t, "out dir", config.SQL[0].Gen.Go.Out, "db")
}

func testParseNonExistent(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{}

	_, err := parseSQLCConfigFS(mapFS, "missing.yaml")
	if err == nil {
		t.Error("expected error for missing file")
	}
}

func TestFilterExcludePattern(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()

	dbDir := filepath.Join(tmpDir, "db")

	mkdirAll(t, dbDir)

	tmpFile := filepath.Join(dbDir, "models.go")
	writeFile(t, tmpFile, "// Code generated by sqlc. DO NOT EDIT.\npackage db\n")

	opts, err := WithFilterOptions(FilterSQLC)
	if err != nil {
		t.Fatal(err)
	}

	filter, err := NewFilter(
		opts,
		WithExcludePatterns("**/db/*.go"),
		WithFS(os.DirFS(tmpDir)),
	)
	if err != nil {
		t.Fatal(err)
	}

	if !mustFilter(t, filter, filepath.Join("db", "models.go")) {
		t.Error("expected exclude pattern match to be filtered")
	}
}
