package gogenfilter

import (
	"strings"
	"testing"
	"testing/fstest"
)

func TestShouldFilterEdgeCases(t *testing.T) {
	t.Parallel()

	t.Run("empty path returns error", func(t *testing.T) {
		t.Parallel()

		filter := NewFilter(Enabled(), WithFilterOptions(FilterAll))

		_, err := filter.ShouldFilter("")
		if err == nil {
			t.Error("expected error for empty path")
		}
	})

	t.Run("special characters in path", func(t *testing.T) {
		t.Parallel()

		type tc struct {
			name     string
			filePath string
			content  string
		}

		cases := []tc{
			{
				name:     "spaces in path",
				filePath: "path with spaces/models.go",
				content:  "// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
			},
			{
				name:     "unicode filename",
				filePath: "dönner/models.go",
				content:  "// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
			},
		}

		for _, caze := range cases {
			t.Run(caze.name, func(t *testing.T) {
				t.Parallel()

				mapFS := fstest.MapFS{
					caze.filePath: newMapFile(caze.content),
				}

				assertShouldFilter(t, mapFS, caze.filePath, true)
			})
		}
	})

	t.Run("very long filename", func(t *testing.T) {
		t.Parallel()

		longName := strings.Repeat("a", 200) + ".go"

		mapFS := fstest.MapFS{
			longName: newMapFile("package main\n"),
		}

		filter := NewFilter(Enabled(), WithFilterOptions(FilterAll), WithFS(mapFS))

		filtered, err := filter.ShouldFilter(longName)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if filtered {
			t.Error("expected long-named regular file to not be filtered")
		}
	})

	t.Run("nil FS defaults to OS filesystem", func(t *testing.T) {
		t.Parallel()

		filter := NewFilter(Enabled(), WithFilterOptions(FilterAll), WithFS(nil))

		filtered, err := filter.ShouldFilter("nonexistent_deffile_12345.go")
		if err == nil {
			t.Error("expected error for nonexistent file with OS FS")
		}

		if filtered {
			t.Error("expected nonexistent file to not be filtered even on error")
		}
	})

	t.Run("MustFilter panics on error", func(t *testing.T) {
		t.Parallel()

		filter := NewFilter(Enabled(), WithFilterOptions(FilterAll), WithFS(nil))

		defer func() {
			r := recover()
			if r == nil {
				t.Fatal("expected MustFilter to panic on error")
			}

			msg, ok := r.(string)
			if !ok {
				t.Fatalf("expected string panic, got %T: %v", r, r)
			}

			if !strings.Contains(msg, "gogenfilter: MustFilter error:") {
				t.Errorf("panic message should contain prefix, got: %s", msg)
			}
		}()

		filter.MustFilter("nonexistent_deffile_12345.go")
	})
}
