package gogenfilter

import (
	"sync"
	"testing"
	"testing/fstest"
)

func TestFilterConcurrent(t *testing.T) {
	t.Parallel()

	mapFS := fstest.MapFS{
		"db/models.go": newMapFile("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
		"main.go":      newMapFile("package main\nfunc main() {}\n"),
		"api.go":       newMapFile("package main\n"),
	}

	filter := NewFilter(
		WithFilterOptions(FilterAll),
		WithFS(mapFS),
	)

	const goroutines = 100

	var waitGroup sync.WaitGroup
	waitGroup.Add(goroutines)

	for i := range goroutines {
		go func() {
			defer waitGroup.Done()

			files := []string{"db/models.go", "main.go", "api.go"}
			file := files[i%len(files)]

			filtered, err := filter.Filter(file)
			if err != nil {
				t.Errorf("Filter(%q) error: %v", file, err)
			}

			switch file {
			case "db/models.go":
				if !filtered {
					t.Error("expected db/models.go to be filtered")
				}
			case "main.go", "api.go":
				if filtered {
					t.Errorf("expected %s to not be filtered", file)
				}
			}
		}()
	}

	waitGroup.Wait()

	stats := filter.GetStats()

	assertEqual(t, "total checked", int(stats.TotalFilesChecked), goroutines)
}
