package gogenfilter

import (
	"testing"
	"testing/fstest"
)

const (
	contentOnlyTemplContent  = "// Code generated by templ - DO NOT EDIT.\npackage x\nvar _ = templ.Component\n"
	contentOnlyGoEnumContent = "// Code generated by go-enum DO NOT EDIT.\npackage x\n"
)

// TestContentOnlyDetectionCatchesMisnamedFiles verifies that the four
// filename-gated detectors (SQLC, Templ, GoEnum, Protobuf) correctly detect
// files by content even when the filename does not match the expected pattern.
// This is the core fix: checkContent is now content-only (no filename gate),
// so phase-2 detection catches misnamed generated files.
func TestContentOnlyDetectionCatchesMisnamedFiles(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		filename string
		content  string
		option   FilterOption
		reason   FilterReason
	}{
		{
			name:     "sqlc content with non-sqlc filename",
			filename: "repository.go",
			content:  sqlcGeneratedContentTest,
			option:   FilterSQLC,
			reason:   ReasonSQLC,
		},
		{
			name:     "templ content with non-templ filename",
			filename: "custom_template.go",
			content:  contentOnlyTemplContent,
			option:   FilterTempl,
			reason:   ReasonTempl,
		},
		{
			name:     "go-enum content with non-enum filename",
			filename: "types.go",
			content:  contentOnlyGoEnumContent,
			option:   FilterGoEnum,
			reason:   ReasonGoEnum,
		},
		{
			name:     "protobuf content with non-pb filename",
			filename: "messages.go",
			content:  protobufGeneratedContent,
			option:   FilterProtobuf,
			reason:   ReasonProtobuf,
		},
		{
			name:     "protobuf grpc content with non-pb filename",
			filename: "service.go",
			content:  protobufGeneratedContent,
			option:   FilterProtobuf,
			reason:   ReasonProtobuf,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			opts, err := WithFilterOptions(tt.option)
			if err != nil {
				t.Fatal(err)
			}

			filter, err := NewFilter(opts, WithFS(fstest.MapFS{}))
			if err != nil {
				t.Fatal(err)
			}

			result, err := filter.FilterDetailedWithContent(tt.filename, []byte(tt.content))
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if !result.Filtered {
				t.Fatalf("expected file to be filtered, got not-filtered")
			}

			if result.Reason != tt.reason {
				t.Errorf("expected reason=%s, got reason=%s", tt.reason, result.Reason)
			}
		})
	}
}

// TestIsGeneratedStillRequiresFilename verifies that the public Is*Generated
// functions still require the correct filename (backward compatibility).
func TestIsGeneratedStillRequiresFilename(t *testing.T) {
	t.Parallel()

	goEnumContent := contentOnlyGoEnumContent
	templContent := contentOnlyTemplContent

	tests := []struct {
		name     string
		fn       func(string, string) bool
		filename string
		content  string
	}{
		{"IsSQLCGenerated with wrong filename", IsSQLCGenerated, "repository.go", sqlcGeneratedContentTest},
		{"IsTemplGenerated with wrong filename", IsTemplGenerated, "custom_template.go", templContent},
		{"IsGoEnumGenerated with wrong filename", IsGoEnumGenerated, "types.go", goEnumContent},
		{"IsProtobufGenerated with wrong filename", IsProtobufGenerated, "messages.go", protobufGeneratedContent},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			if tt.fn(tt.filename, tt.content) {
				t.Errorf("expected false: Is*Generated should require correct filename")
			}
		})
	}
}

// TestContentOnlyFunctionsNoFalsePositives verifies that content-only
// detection functions do not flag regular (non-generated) files.
func TestContentOnlyFunctionsNoFalsePositives(t *testing.T) {
	t.Parallel()

	if hasSQLCContent(packageMainFunc) {
		t.Error("hasSQLCContent should return false for regular content")
	}

	if hasTemplContent(packageMainFunc) {
		t.Error("hasTemplContent should return false for regular content")
	}

	if hasGoEnumContent(packageMainFunc) {
		t.Error("hasGoEnumContent should return false for regular content")
	}

	if hasProtobufContent(packageMainFunc) {
		t.Error("hasProtobufContent should return false for regular content")
	}
}
