package gogenfilter

import (
	"testing"
)

func FuzzMatchPattern(f *testing.F) {
	for _, tc := range matchPatternTestCases() {
		f.Add(tc.path, tc.pattern)
	}

	f.Add("", "")
	f.Add("a/b/c/d/e/file.go", "**/*.go")
	f.Add("vendor/pkg/file.go", "vendor/**")
	f.Add("deep/nested/path/to/file.txt", "**/file.*")
	f.Add("file.go", "*.go")
	f.Add("file.txt", "*.go")
	f.Add("a.go", "?.go")
	f.Add("ab.go", "?.go")
	f.Add("[invalid", "[invalid")

	f.Fuzz(func(t *testing.T, path, pattern string) {
		result := MatchPattern(path, pattern)

		if pattern == "" || path == "" {
			return
		}

		doubleResult := MatchPattern(path, pattern)
		if result != doubleResult {
			t.Errorf("MatchPattern not idempotent: first=%v second=%v", result, doubleResult)
		}
	})
}

func FuzzDetectReason(f *testing.F) {
	seeds := []struct {
		path, content string
	}{
		{"db/models.go", "// Code generated by sqlc. DO NOT EDIT.\npackage db\n"},
		{
			"page_templ.go",
			"// Code generated by templ DO NOT EDIT\n" +
				"package components\n" +
				"import \"github.com/a-h/templ\"\n" +
				"func Page() templ.Component { return nil }\n",
		},
		{"status_enum.go", "// Code generated by go-enum DO NOT EDIT.\npackage enums\n"},
		{"user.pb.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n"},
		{"service_mock.go", "// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n"},
		{"status_string.go", "// Code generated by \"stringer\". DO NOT EDIT.\npackage enums\n"},
		{"custom.go", "// Code generated by my-tool. DO NOT EDIT.\npackage main\n"},
		{"main.go", "package main\nfunc main() {}\n"},
		{"", ""},
		{"file.go", "// Code generated by "},
	}

	for _, s := range seeds {
		f.Add(s.path, s.content)
	}

	f.Fuzz(func(t *testing.T, path, content string) {
		reason := DetectReason(path, content, FilterAll)

		if !reason.IsValid() {
			t.Errorf("DetectReason returned invalid reason %q for path=%q", reason, path)
		}

		reason2 := DetectReason(path, content, FilterAll)
		if reason != reason2 {
			t.Errorf("DetectReason not idempotent: first=%v second=%v", reason, reason2)
		}
	})
}
