package gogenfilter

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"testing/fstest"
)

func TestScanProject(t *testing.T) {
	t.Parallel()

	t.Run("detects mixed generators", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"db/models.go": &fstest.MapFile{
				Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
			},
			pageTemplGo: &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			userPbGo: &fstest.MapFile{
				Data: []byte("// Code generated by protoc. DO NOT EDIT.\npackage pb\n"),
			},
			mainGo: &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			"handler/handler.go": &fstest.MapFile{
				Data: []byte("package handler\nfunc Handle() {}\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 5 {
			t.Errorf("expected 5 scanned files, got %d", result.ScannedFiles)
		}

		if len(result.Files) != 3 {
			t.Errorf("expected 3 generated files, got %d", len(result.Files))
		}

		generators := make(map[string]bool)
		for _, gen := range result.Generators {
			generators[gen] = true
		}

		if !generators["sqlc"] || !generators["templ"] || !generators["protobuf"] {
			t.Errorf("expected sqlc,templ,protobuf in generators, got %v", result.Generators)
		}
	})

	t.Run("empty directory returns empty result", func(t *testing.T) {
		t.Parallel()

		result, err := ScanProject(fstest.MapFS{})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 0 || len(result.Files) != 0 {
			t.Errorf(
				"expected empty result, got scanned=%d files=%d",
				result.ScannedFiles,
				len(result.Files),
			)
		}
	})

	t.Run("no generated files returns empty generators", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			mainGo:   &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			"foo.go": &fstest.MapFile{Data: []byte("package foo\n")},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 2 {
			t.Errorf("expected 2 scanned files, got %d", result.ScannedFiles)
		}

		if len(result.Generators) != 0 {
			t.Errorf("expected 0 generators, got %v", result.Generators)
		}
	})

	t.Run("skips vendor directory", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			mainGo: &fstest.MapFile{Data: []byte("package main\n")},
			"vendor/generated/models.go": &fstest.MapFile{
				Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 1 {
			t.Errorf("expected 1 scanned file (vendor skipped), got %d", result.ScannedFiles)
		}
	})

	t.Run("skips node_modules and hidden directories", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			mainGo: &fstest.MapFile{Data: []byte("package main\n")},
			"node_modules/pkg/gen.go": &fstest.MapFile{
				Data: []byte("// Code generated\npackage pkg\n"),
			},
			".hidden/file.go": &fstest.MapFile{
				Data: []byte("// Code generated\npackage h\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 1 {
			t.Errorf("expected 1 scanned file, got %d", result.ScannedFiles)
		}
	})
}

func TestScanProjectExclusions(t *testing.T) {
	t.Parallel()

	t.Run("derives exclusion patterns", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			pageTemplGo: &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			userPbGo: &fstest.MapFile{
				Data: []byte("// Code generated by protoc. DO NOT EDIT.\npackage pb\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		patterns := ExclusionPaths(result.Exclusions)

		foundTempl := false
		foundProtobuf := false

		for _, p := range patterns {
			if strings.Contains(p, "templ") {
				foundTempl = true
			}

			if strings.Contains(p, "pb") {
				foundProtobuf = true
			}
		}

		if !foundTempl || !foundProtobuf {
			t.Errorf("expected templ+protobuf exclusion patterns, got %v", patterns)
		}
	})

	t.Run("works with os.DirFS on real filesystem", func(t *testing.T) {
		t.Parallel()

		tmpDir := t.TempDir()

		err := os.WriteFile(
			filepath.Join(tmpDir, mainGo),
			[]byte("package main\nfunc main() {}\n"),
			0o600,
		)
		if err != nil {
			t.Fatal(err)
		}

		err = os.WriteFile(
			filepath.Join(tmpDir, pageTemplGo),
			[]byte("package main\nfunc main() {}\n"),
			0o600,
		)
		if err != nil {
			t.Fatal(err)
		}

		result, err := ScanProject(os.DirFS(tmpDir))
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 2 || len(result.Files) != 1 {
			t.Errorf(
				"expected scanned=2 files=1, got scanned=%d files=%d",
				result.ScannedFiles,
				len(result.Files),
			)
		}

		if len(result.Generators) != 1 || result.Generators[0] != "templ" {
			t.Errorf("expected [templ] generators, got %v", result.Generators)
		}
	})
}

func TestExclusionPattern(t *testing.T) {
	t.Parallel()

	tests := []struct {
		reason     FilterReason
		hasPattern bool
	}{
		{ReasonTempl, true},
		{ReasonProtobuf, true},
		{ReasonGoEnum, true},
		{ReasonDeepcopy, true},
		{ReasonWire, true},
		{ReasonMoq, true},
		{ReasonMockgen, true},
		{ReasonStringer, true},
		{ReasonMockery, true},
		{ReasonEasyjson, true},
		{ReasonMsgp, false},
		{ReasonCounterfeiter, true},
		{ReasonEnt, false},
		{ReasonGqlgen, false},
		{ReasonGoSwagger, false},
		{ReasonSQLC, false},
		{ReasonOapi, false},
		{ReasonGeneric, false},
		{ReasonNotFiltered, false},
		{ReasonOutsideScope, false},
		{ReasonExcludePattern, false},
	}

	for _, tc := range tests {
		t.Run(string(tc.reason), func(t *testing.T) {
			t.Parallel()

			_, ok := tc.reason.ExclusionPattern()
			if ok != tc.hasPattern {
				t.Errorf("ExclusionPattern() ok=%v, want %v", ok, tc.hasPattern)
			}
		})
	}
}

func TestExclusionDerivation(t *testing.T) {
	t.Parallel()

	t.Run("oapi-codegen with .gen.go files", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"api/types.gen.go": &fstest.MapFile{
				Data: []byte("// Code generated by oapi-codegen. DO NOT EDIT.\npackage api\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		patterns := ExclusionPaths(result.Exclusions)

		foundGenGo := false

		for _, p := range patterns {
			if strings.Contains(p, ".gen.go") {
				foundGenGo = true
			}
		}

		if !foundGenGo {
			t.Errorf("expected .gen.go exclusion pattern for oapi-codegen, got %v", patterns)
		}
	})

	t.Run("ent directory-based exclusions", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"ent/client.go": &fstest.MapFile{
				Data: []byte("// Code generated by ent. DO NOT EDIT.\npackage ent\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) == 0 {
			t.Error("expected exclusions for ent generated files")
		}
	})

	t.Run("gqlgen directory-based exclusions", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"graph/generated.go": &fstest.MapFile{
				Data: []byte(
					"// Code generated by github.com/99designs/gqlgen. DO NOT EDIT.\npackage graph\n",
				),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) == 0 {
			t.Error("expected exclusions for gqlgen generated files")
		}
	})

	t.Run("go-swagger directory-based exclusions", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"restapi/user.go": &fstest.MapFile{
				Data: []byte("// Code generated by go-swagger. DO NOT EDIT.\npackage restapi\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) == 0 {
			t.Error("expected exclusions for go-swagger generated files")
		}
	})

	t.Run("generic fallback exclusions", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"tools/custom.go": &fstest.MapFile{
				Data: []byte("// Code generated by my-custom-tool. DO NOT EDIT.\npackage tools\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) == 0 {
			t.Error("expected exclusions for generic generated files")
		}
	})

	t.Run("oapi-codegen without .gen.go falls back to directory-based", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"api/types.go": &fstest.MapFile{
				Data: []byte("// Code generated by oapi-codegen. DO NOT EDIT.\npackage api\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) == 0 {
			t.Error("expected directory-based exclusions for oapi-codegen without .gen.go")
		}
	})

	t.Run("ScanProject with custom configs", func(t *testing.T) {
		t.Parallel()

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		fsys := fstest.MapFS{
			"db/models.go": &fstest.MapFile{
				Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
			},
			pageTemplGo: &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
		}

		result, err := ScanProject(fsys, opts)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Files) != 1 {
			t.Errorf("expected 1 file (sqlc only), got %d", len(result.Files))
		}

		if len(result.Generators) != 1 || result.Generators[0] != string(ReasonSQLC) {
			t.Errorf("expected [sqlc] generators, got %v", result.Generators)
		}
	})

	t.Run("msgp uses directory-based exclusion with specific reason", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"msgp/types_gen.go": &fstest.MapFile{
				Data: []byte("// Code generated by github.com/tinylib/msgp; DO NOT EDIT.\npackage msgp\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) < 1 {
			t.Fatalf("expected at least 1 exclusion, got %d", len(result.Exclusions))
		}

		found := false
		for _, exc := range result.Exclusions {
			if strings.Contains(exc.Reason, "msgp") {
				found = true

				break
			}
		}

		if !found {
			t.Errorf("expected msgp-specific reason in exclusions, got %v", result.Exclusions)
		}
	})
}

func TestExclusionPatternRegexCompiles(t *testing.T) {
	t.Parallel()

	for _, reason := range AllFilterReasons() {
		pattern, ok := reason.ExclusionPattern()
		if !ok {
			continue
		}

		t.Run(string(reason), func(t *testing.T) {
			t.Parallel()

			_, err := regexp.Compile(pattern)
			if err != nil {
				t.Errorf(
					"ExclusionPattern() for %q returned invalid regex %q: %v",
					reason,
					pattern,
					err,
				)
			}
		})
	}
}

func TestGeneratedFileString(t *testing.T) {
	t.Parallel()

	f := GeneratedFile{Path: "db/models.go", Reason: ReasonSQLC}
	got := f.String()
	assertContains(t, got, "db/models.go")
	assertContains(t, got, "sqlc")
}

func TestExclusionString(t *testing.T) {
	t.Parallel()

	e := Exclusion{Pattern: `_templ\.go$`, Reason: "templ generated HTML components"}
	got := e.String()
	assertContains(t, got, "_templ")
	assertContains(t, got, "templ generated")
}

func TestScanResultString(t *testing.T) {
	t.Parallel()

	r := &ScanResult{
		ScannedFiles: 42,
		Files:        []GeneratedFile{{Path: "a.go", Reason: ReasonTempl}},
		Generators:   []string{"templ"},
	}
	got := r.String()
	assertContains(t, got, "scanned=42")
	assertContains(t, got, "generated=1")
	assertContains(t, got, "templ")
}
