package gogenfilter

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"testing/fstest"
)

func TestScanProject(t *testing.T) {
	t.Parallel()

	t.Run("detects mixed generators", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			dbModelsGo: &fstest.MapFile{
				Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
			},
			pageTemplGo: &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			userPbGo: &fstest.MapFile{
				Data: []byte("// Code generated by protoc. DO NOT EDIT.\npackage pb\n"),
			},
			mainGo: &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			"handler/handler.go": &fstest.MapFile{
				Data: []byte("package handler\nfunc Handle() {}\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 5 {
			t.Errorf("expected 5 scanned files, got %d", result.ScannedFiles)
		}

		if len(result.Files) != 3 {
			t.Errorf("expected 3 generated files, got %d", len(result.Files))
		}

		generators := make(map[string]bool)
		for _, gen := range result.Generators {
			generators[gen] = true
		}

		if !generators["sqlc"] || !generators["templ"] || !generators["protobuf"] {
			t.Errorf("expected sqlc,templ,protobuf in generators, got %v", result.Generators)
		}
	})

	t.Run("empty directory returns empty result", func(t *testing.T) {
		t.Parallel()

		result, err := ScanProject(fstest.MapFS{})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 0 || len(result.Files) != 0 {
			t.Errorf(
				"expected empty result, got scanned=%d files=%d",
				result.ScannedFiles,
				len(result.Files),
			)
		}
	})

	t.Run("no generated files returns empty generators", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			mainGo:   &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			"foo.go": &fstest.MapFile{Data: []byte("package foo\n")},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 2 {
			t.Errorf("expected 2 scanned files, got %d", result.ScannedFiles)
		}

		if len(result.Generators) != 0 {
			t.Errorf("expected 0 generators, got %v", result.Generators)
		}
	})

	t.Run("skips vendor directory", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			mainGo: &fstest.MapFile{Data: []byte("package main\n")},
			"vendor/generated/models.go": &fstest.MapFile{
				Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 1 {
			t.Errorf("expected 1 scanned file (vendor skipped), got %d", result.ScannedFiles)
		}
	})

	t.Run("skips node_modules and hidden directories", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			mainGo: &fstest.MapFile{Data: []byte("package main\n")},
			"node_modules/pkg/gen.go": &fstest.MapFile{
				Data: []byte("// Code generated\npackage pkg\n"),
			},
			".hidden/file.go": &fstest.MapFile{
				Data: []byte("// Code generated\npackage h\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 1 {
			t.Errorf("expected 1 scanned file, got %d", result.ScannedFiles)
		}
	})
}

func TestScanProjectExclusions(t *testing.T) {
	t.Parallel()

	t.Run("derives exclusion patterns", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			pageTemplGo: &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			userPbGo: &fstest.MapFile{
				Data: []byte("// Code generated by protoc. DO NOT EDIT.\npackage pb\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		patterns := ExclusionPaths(result.Exclusions)

		foundTempl := false
		foundProtobuf := false

		for _, p := range patterns {
			if strings.Contains(p, "templ") {
				foundTempl = true
			}

			if strings.Contains(p, "pb") {
				foundProtobuf = true
			}
		}

		if !foundTempl || !foundProtobuf {
			t.Errorf("expected templ+protobuf exclusion patterns, got %v", patterns)
		}
	})

	t.Run("works with os.DirFS on real filesystem", func(t *testing.T) {
		t.Parallel()

		tmpDir := t.TempDir()

		err := os.WriteFile(
			filepath.Join(tmpDir, mainGo),
			[]byte("package main\nfunc main() {}\n"),
			0o600,
		)
		if err != nil {
			t.Fatal(err)
		}

		err = os.WriteFile(
			filepath.Join(tmpDir, pageTemplGo),
			[]byte("package main\nfunc main() {}\n"),
			0o600,
		)
		if err != nil {
			t.Fatal(err)
		}

		result, err := ScanProject(os.DirFS(tmpDir))
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 2 || len(result.Files) != 1 {
			t.Errorf(
				"expected scanned=2 files=1, got scanned=%d files=%d",
				result.ScannedFiles,
				len(result.Files),
			)
		}

		if len(result.Generators) != 1 || result.Generators[0] != string(FilterTempl) {
			t.Errorf("expected [templ] generators, got %v", result.Generators)
		}
	})
}

func TestExclusionPattern(t *testing.T) {
	t.Parallel()

	tests := []struct {
		reason     FilterReason
		hasPattern bool
	}{
		{ReasonTempl, true},
		{ReasonProtobuf, true},
		{ReasonGoEnum, true},
		{ReasonDeepcopy, true},
		{ReasonWire, true},
		{ReasonMoq, true},
		{ReasonMockgen, true},
		{ReasonStringer, true},
		{ReasonMockery, true},
		{ReasonEasyjson, true},
		{ReasonMsgp, true},
		{ReasonCounterfeiter, true},
		{ReasonEnt, false},
		{ReasonGqlgen, false},
		{ReasonGoSwagger, false},
		{ReasonSQLC, true},
		{ReasonOapi, true},
		{ReasonGeneric, false},
		{ReasonNotFiltered, false},
		{ReasonOutsideScope, false},
		{ReasonExcludePattern, false},
	}

	for _, testCase := range tests {
		t.Run(string(testCase.reason), func(t *testing.T) {
			t.Parallel()

			_, ok := testCase.reason.ExclusionPattern()
			if ok != testCase.hasPattern {
				t.Errorf("ExclusionPattern() ok=%v, want %v", ok, testCase.hasPattern)
			}
		})
	}
}

func TestExclusionDerivation(t *testing.T) {
	t.Parallel()

	t.Run("oapi-codegen with .gen.go files", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"api/types.gen.go": &fstest.MapFile{
				Data: []byte(
					"// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.\npackage api\n",
				),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		patterns := ExclusionPaths(result.Exclusions)

		foundGenGo := false

		for _, p := range patterns {
			if p == `\.gen\.go$` {
				foundGenGo = true
			}
		}

		if !foundGenGo {
			t.Errorf(
				"expected escaped .gen.go exclusion pattern for oapi-codegen, got %v",
				patterns,
			)
		}
	})

	t.Run("ent directory-based exclusions", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"ent/client.go": &fstest.MapFile{
				Data: []byte("// Code generated by ent. DO NOT EDIT.\npackage ent\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) == 0 {
			t.Error("expected exclusions for ent generated files")
		}
	})

	t.Run("gqlgen directory-based exclusions", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"graph/generated.go": &fstest.MapFile{
				Data: []byte(
					"// Code generated by github.com/99designs/gqlgen. DO NOT EDIT.\npackage graph\n",
				),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) == 0 {
			t.Error("expected exclusions for gqlgen generated files")
		}
	})

	t.Run("go-swagger directory-based exclusions", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"restapi/user.go": &fstest.MapFile{
				Data: []byte("// Code generated by go-swagger. DO NOT EDIT.\npackage restapi\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) == 0 {
			t.Error("expected exclusions for go-swagger generated files")
		}
	})

	t.Run("generic fallback exclusions", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"tools/custom.go": &fstest.MapFile{
				Data: []byte("// Code generated by my-custom-tool. DO NOT EDIT.\npackage tools\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) == 0 {
			t.Error("expected exclusions for generic generated files")
		}
	})

	t.Run("oapi-codegen without .gen.go falls back to directory-based", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"api/types.go": &fstest.MapFile{
				Data: []byte(
					"// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.\npackage api\n",
				),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) == 0 {
			t.Error("expected directory-based exclusions for oapi-codegen without .gen.go")
		}
	})

	t.Run("ScanProject with custom configs", func(t *testing.T) {
		t.Parallel()

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		fsys := fstest.MapFS{
			dbModelsGo: &fstest.MapFile{
				Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
			},
			pageTemplGo: &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
		}

		result, err := ScanProject(fsys, opts)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Files) != 1 {
			t.Errorf("expected 1 file (sqlc only), got %d", len(result.Files))
		}

		if len(result.Generators) != 1 || result.Generators[0] != string(ReasonSQLC) {
			t.Errorf("expected [sqlc] generators, got %v", result.Generators)
		}
	})

	t.Run("msgp uses fixed _gen.go pattern with specific reason", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"msgp/types_gen.go": &fstest.MapFile{
				Data: []byte(
					"// Code generated by github.com/tinylib/msgp; DO NOT EDIT.\npackage msgp\n",
				),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Exclusions) < 1 {
			t.Fatalf("expected at least 1 exclusion, got %d", len(result.Exclusions))
		}

		found := false

		for _, exc := range result.Exclusions {
			if strings.Contains(exc.Reason, "msgp") {
				found = true

				break
			}
		}

		if !found {
			t.Errorf("expected msgp-specific reason in exclusions, got %v", result.Exclusions)
		}
	})

	t.Run(
		"sqlc with partially matching filenames uses scoped directory pattern",
		func(t *testing.T) {
			t.Parallel()

			// Old-style sqlc output (models.go) has no .sql.go suffix, so the fixed
			// pattern does not fully cover the detected files. The db/ directory is
			// fully generated, so a scoped directory pattern covers everything.
			byGenerator := map[string][]string{
				string(ReasonSQLC): {
					"db/query.sql.go",
					"db/models.go",
					"db/user.sql.go",
				},
			}
			allGoFiles := []string{"db/query.sql.go", "db/models.go", "db/user.sql.go"}

			exclusions := deriveExclusions(byGenerator, allGoFiles)
			if len(exclusions) != 1 {
				t.Fatalf("expected 1 exclusion for sqlc, got %d: %v", len(exclusions), exclusions)
			}

			exc := exclusions[0]
			assertEqual(t, "Pattern", exc.Pattern, `^db/`)
			assertEqual(t, "Reason", exc.Reason, "sqlc generated database code")
		},
	)

	t.Run("sqlc with fully matching filenames uses fixed pattern", func(t *testing.T) {
		t.Parallel()

		byGenerator := map[string][]string{
			string(ReasonSQLC): {"db/query.sql.go", "other/user.sql.go"},
		}
		allGoFiles := []string{"db/query.sql.go", "other/user.sql.go", "main.go"}

		exclusions := deriveExclusions(byGenerator, allGoFiles)
		if len(exclusions) != 1 {
			t.Fatalf("expected 1 exclusion for sqlc, got %d: %v", len(exclusions), exclusions)
		}

		exc := exclusions[0]
		assertEqual(t, "Pattern", exc.Pattern, `\.sql\.go$`)
		assertEqual(t, "Reason", exc.Reason, "sqlc generated database code")
	})

	t.Run("mixed directory never gets a directory pattern", func(t *testing.T) {
		t.Parallel()

		// ent/client.go is detected, but hand-written schema/user.go shares the
		// directory tree. A directory pattern would blanket-exclude the hand-written
		// file, so per-file patterns are required.
		byGenerator := map[string][]string{
			string(ReasonEnt): {"ent/client.go", "ent/mutation.go"},
		}
		allGoFiles := []string{"ent/client.go", "ent/mutation.go", "ent/schema/user.go"}

		exclusions := deriveExclusions(byGenerator, allGoFiles)
		patterns := ExclusionPaths(exclusions)

		for _, p := range patterns {
			if strings.HasSuffix(p, "/") {
				t.Errorf("mixed directory must not produce a directory pattern, got %v", patterns)
			}
		}

		expected := map[string]bool{
			`^ent/client\.go$`:   false,
			`^ent/mutation\.go$`: false,
		}

		for _, p := range patterns {
			if _, ok := expected[p]; ok {
				expected[p] = true
			}
		}

		for p, found := range expected {
			if !found {
				t.Errorf("expected per-file pattern %s, got %v", p, patterns)
			}
		}
	})

	t.Run("fully generated directory uses anchored directory pattern", func(t *testing.T) {
		t.Parallel()

		byGenerator := map[string][]string{
			string(ReasonGqlgen): {"graph/generated.go", "graph/models.go"},
		}
		allGoFiles := []string{"graph/generated.go", "graph/models.go", "main.go"}

		exclusions := deriveExclusions(byGenerator, allGoFiles)
		if len(exclusions) != 1 {
			t.Fatalf("expected 1 exclusion for gqlgen, got %d: %v", len(exclusions), exclusions)
		}

		exc := exclusions[0]
		assertEqual(t, "Pattern", exc.Pattern, `^graph/`)
	})

	t.Run("nested generated directories emit only the parent pattern", func(t *testing.T) {
		t.Parallel()

		byGenerator := map[string][]string{
			string(ReasonEnt): {"ent/generated/client.go", "ent/generated/predicate/predicate.go"},
		}
		allGoFiles := []string{
			"ent/generated/client.go",
			"ent/generated/predicate/predicate.go",
			"ent/schema/user.go",
		}

		exclusions := deriveExclusions(byGenerator, allGoFiles)
		patterns := ExclusionPaths(exclusions)

		found := false

		for _, pattern := range patterns {
			if pattern == `^ent/generated/` {
				found = true
			}

			if pattern == `^ent/generated/predicate/` {
				t.Errorf(
					"redundant child dir pattern %s alongside parent, got %v",
					pattern,
					patterns,
				)
			}
		}

		if !found {
			t.Errorf("expected parent dir pattern ^ent/generated/, got %v", patterns)
		}
	})

	t.Run("root-level generated files use per-file patterns", func(t *testing.T) {
		t.Parallel()

		byGenerator := map[string][]string{
			string(ReasonGeneric): {"zz_generated.deepcopy.go"},
		}
		allGoFiles := []string{"main.go", "zz_generated.deepcopy.go"}

		exclusions := deriveExclusions(byGenerator, allGoFiles)
		if len(exclusions) != 1 {
			t.Fatalf("expected 1 exclusion, got %d: %v", len(exclusions), exclusions)
		}

		exc := exclusions[0]
		assertEqual(t, "Pattern", exc.Pattern, `^zz_generated\.deepcopy\.go$`)
	})

	t.Run("sqlc mixed with directory-based generator uses both patterns", func(t *testing.T) {
		t.Parallel()

		byGenerator := map[string][]string{
			string(ReasonSQLC):   {"db/query.sql.go"},
			string(ReasonGqlgen): {"graph/generated.go"},
		}
		allGoFiles := []string{"db/query.sql.go", "graph/generated.go"}

		exclusions := deriveExclusions(byGenerator, allGoFiles)
		patterns := ExclusionPaths(exclusions)

		foundSQLCPattern := false
		foundDirPattern := false

		for _, p := range patterns {
			if p == `\.sql\.go$` {
				foundSQLCPattern = true
			}

			if p == `^graph/` {
				foundDirPattern = true
			}
		}

		if !foundSQLCPattern {
			t.Errorf("expected .sql.go$ pattern for sqlc, got %v", patterns)
		}

		if !foundDirPattern {
			t.Errorf("expected anchored directory pattern for gqlgen, got %v", patterns)
		}
	})
}

func TestScanSQLCExclusion(t *testing.T) {
	t.Parallel()

	t.Run("query.sql.go produces .sql.go exclusion pattern", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"db/query.sql.go": &fstest.MapFile{
				Data: []byte("package db\n\nfunc GetUser() {}\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(result.Files) != 1 {
			t.Fatalf("expected 1 sqlc file, got %d", len(result.Files))
		}

		if result.Files[0].Reason != ReasonSQLC {
			t.Errorf("expected ReasonSQLC, got %s", result.Files[0].Reason)
		}

		patterns := ExclusionPaths(result.Exclusions)
		foundSQLCSuffix := false

		for _, p := range patterns {
			if strings.Contains(p, `sql\.go`) {
				foundSQLCSuffix = true

				break
			}
		}

		if !foundSQLCSuffix {
			t.Errorf("expected \\.sql\\.go$ exclusion pattern, got %v", patterns)
		}
	})

	t.Run("sqlc exclusion is not directory-based", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"db/query.sql.go": &fstest.MapFile{
				Data: []byte("package db\n\nfunc GetUser() {}\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		for _, exc := range result.Exclusions {
			if exc.Reason == "sqlc generated database code" {
				if !strings.Contains(exc.Pattern, `sql`) || !strings.Contains(exc.Pattern, `go`) {
					t.Errorf(
						"sqlc exclusion should use .sql.go pattern, got %q",
						exc.Pattern,
					)
				}

				return
			}
		}

		t.Errorf("expected sqlc exclusion in %v", result.Exclusions)
	})
}

func TestExclusionPatternRegexCompiles(t *testing.T) {
	t.Parallel()

	for _, reason := range AllFilterReasons() {
		pattern, ok := reason.ExclusionPattern()
		if !ok {
			continue
		}

		t.Run(string(reason), func(t *testing.T) {
			t.Parallel()

			_, err := regexp.Compile(pattern)
			if err != nil {
				t.Errorf(
					"ExclusionPattern() for %q returned invalid regex %q: %v",
					reason,
					pattern,
					err,
				)
			}
		})
	}
}

func TestGeneratedFileString(t *testing.T) {
	t.Parallel()

	f := GeneratedFile{Path: "db/models.go", Reason: ReasonSQLC}
	got := f.String()
	assertContains(t, got, "db/models.go")
	assertContains(t, got, "sqlc")
}

func TestExclusionString(t *testing.T) {
	t.Parallel()

	e := Exclusion{Pattern: `_templ\.go$`, Reason: "templ generated HTML components"}
	got := e.String()
	assertContains(t, got, "_templ")
	assertContains(t, got, "templ generated")
}

func TestScanResultString(t *testing.T) {
	t.Parallel()

	result := &ScanResult{
		ScannedFiles: 42,
		Files:        []GeneratedFile{{Path: "a.go", Reason: ReasonTempl}},
		Generators:   []string{string(FilterTempl)},
		ByGenerator:  map[string][]string{"templ": {"a.go"}},
		Exclusions: []Exclusion{
			{Pattern: `_templ\.go$`, Reason: "templ generated HTML components"},
		},
	}
	got := result.String()
	assertContains(t, got, "scanned=42")
	assertContains(t, got, "generated=1")
	assertContains(t, got, "templ")
}
