package gogenfilter

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"
)

func TestScanProject(t *testing.T) {
	t.Parallel()

	t.Run("detects mixed generators", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"db/models.go": &fstest.MapFile{
				Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
			},
			pageTemplGo: &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			userPbGo: &fstest.MapFile{
				Data: []byte("// Code generated by protoc. DO NOT EDIT.\npackage pb\n"),
			},
			mainGo: &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			"handler/handler.go": &fstest.MapFile{
				Data: []byte("package handler\nfunc Handle() {}\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 5 {
			t.Errorf("expected 5 scanned files, got %d", result.ScannedFiles)
		}

		if len(result.Files) != 3 {
			t.Errorf("expected 3 generated files, got %d", len(result.Files))
		}

		generators := make(map[string]bool)
		for _, gen := range result.Generators {
			generators[gen] = true
		}

		if !generators["sqlc"] || !generators["templ"] || !generators["protobuf"] {
			t.Errorf("expected sqlc,templ,protobuf in generators, got %v", result.Generators)
		}
	})

	t.Run("empty directory returns empty result", func(t *testing.T) {
		t.Parallel()

		result, err := ScanProject(fstest.MapFS{})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 0 || len(result.Files) != 0 {
			t.Errorf(
				"expected empty result, got scanned=%d files=%d",
				result.ScannedFiles,
				len(result.Files),
			)
		}
	})

	t.Run("no generated files returns empty generators", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			mainGo:   &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			"foo.go": &fstest.MapFile{Data: []byte("package foo\n")},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 2 {
			t.Errorf("expected 2 scanned files, got %d", result.ScannedFiles)
		}

		if len(result.Generators) != 0 {
			t.Errorf("expected 0 generators, got %v", result.Generators)
		}
	})

	t.Run("skips vendor directory", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			mainGo: &fstest.MapFile{Data: []byte("package main\n")},
			"vendor/generated/models.go": &fstest.MapFile{
				Data: []byte("// Code generated by sqlc. DO NOT EDIT.\npackage db\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 1 {
			t.Errorf("expected 1 scanned file (vendor skipped), got %d", result.ScannedFiles)
		}
	})

	t.Run("skips node_modules and hidden directories", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			mainGo: &fstest.MapFile{Data: []byte("package main\n")},
			"node_modules/pkg/gen.go": &fstest.MapFile{
				Data: []byte("// Code generated\npackage pkg\n"),
			},
			".hidden/file.go": &fstest.MapFile{
				Data: []byte("// Code generated\npackage h\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 1 {
			t.Errorf("expected 1 scanned file, got %d", result.ScannedFiles)
		}
	})
}

func TestScanProjectExclusions(t *testing.T) {
	t.Parallel()

	t.Run("derives exclusion patterns", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			pageTemplGo: &fstest.MapFile{Data: []byte("package main\nfunc main() {}\n")},
			userPbGo: &fstest.MapFile{
				Data: []byte("// Code generated by protoc. DO NOT EDIT.\npackage pb\n"),
			},
		}

		result, err := ScanProject(fsys)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		patterns := ExclusionPaths(result.Exclusions)

		foundTempl := false
		foundProtobuf := false

		for _, p := range patterns {
			if strings.Contains(p, "templ") {
				foundTempl = true
			}

			if strings.Contains(p, "pb") {
				foundProtobuf = true
			}
		}

		if !foundTempl || !foundProtobuf {
			t.Errorf("expected templ+protobuf exclusion patterns, got %v", patterns)
		}
	})

	t.Run("works with os.DirFS on real filesystem", func(t *testing.T) {
		t.Parallel()

		tmpDir := t.TempDir()

		err := os.WriteFile(
			filepath.Join(tmpDir, mainGo),
			[]byte("package main\nfunc main() {}\n"),
			0o600,
		)
		if err != nil {
			t.Fatal(err)
		}

		err = os.WriteFile(
			filepath.Join(tmpDir, pageTemplGo),
			[]byte("package main\nfunc main() {}\n"),
			0o600,
		)
		if err != nil {
			t.Fatal(err)
		}

		result, err := ScanProject(os.DirFS(tmpDir))
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if result.ScannedFiles != 2 || len(result.Files) != 1 {
			t.Errorf(
				"expected scanned=2 files=1, got scanned=%d files=%d",
				result.ScannedFiles,
				len(result.Files),
			)
		}

		if len(result.Generators) != 1 || result.Generators[0] != "templ" {
			t.Errorf("expected [templ] generators, got %v", result.Generators)
		}
	})
}

func TestExclusionPattern(t *testing.T) {
	t.Parallel()

	tests := []struct {
		reason     FilterReason
		hasPattern bool
	}{
		{ReasonTempl, true},
		{ReasonProtobuf, true},
		{ReasonGoEnum, true},
		{ReasonDeepcopy, true},
		{ReasonWire, true},
		{ReasonMoq, true},
		{ReasonMockgen, true},
		{ReasonStringer, true},
		{ReasonMockery, true},
		{ReasonEasyjson, true},
		{ReasonMsgp, true},
		{ReasonCounterfeiter, true},
		{ReasonEnt, false},
		{ReasonGqlgen, false},
		{ReasonGoSwagger, false},
		{ReasonSQLC, false},
		{ReasonOapi, false},
		{ReasonGeneric, false},
		{ReasonNotFiltered, false},
		{ReasonOutsideScope, false},
		{ReasonExcludePattern, false},
	}

	for _, tc := range tests {
		t.Run(string(tc.reason), func(t *testing.T) {
			t.Parallel()

			_, ok := tc.reason.ExclusionPattern()
			if ok != tc.hasPattern {
				t.Errorf("ExclusionPattern() ok=%v, want %v", ok, tc.hasPattern)
			}
		})
	}
}
