package gogenfilter

import (
	"slices"
	"strings"
	"testing"
	"testing/fstest"
)

// sqlcConfigV2YAML returns a minimal v2 sqlc config with output dir "db".
func sqlcConfigV2YAML() string {
	return `version: "2"
sql:
  - engine: "postgresql"
    schema: "schema.sql"
    queries: "query.sql"
    gen:
      go:
        package: "db"
        out: "db"
`
}

func TestConfiguredSQLCFileNames(t *testing.T) {
	t.Parallel()

	t.Run("defaults when no custom names", func(t *testing.T) {
		t.Parallel()

		//nolint:exhaustruct // only Out matters
		names := configuredSQLCFileNames(&sqlcGoConfig{Out: "db"})

		want := []string{"db.go", "models.go", "querier.go", "batch.go", "copyfrom.go"}
		if len(names) != len(want) {
			t.Fatalf("expected %d names, got %d: %v", len(want), len(names), names)
		}

		for i, w := range want {
			if names[i] != w {
				t.Errorf("names[%d] = %q, want %q", i, names[i], w)
			}
		}
	})

	t.Run("honors custom names", func(t *testing.T) {
		t.Parallel()

		//nolint:exhaustruct // only Out + custom names matter
		names := configuredSQLCFileNames(&sqlcGoConfig{
			Out:                   "db",
			OutputModelsFileName:  "custom_models.go",
			OutputQuerierFileName: "custom_querier.go",
		})

		if !slices.Contains(names, "custom_models.go") {
			t.Errorf("expected custom_models.go in %v", names)
		}

		if !slices.Contains(names, "custom_querier.go") {
			t.Errorf("expected custom_querier.go in %v", names)
		}

		if slices.Contains(names, "models.go") {
			t.Errorf("custom models name should replace default, got %v", names)
		}

		if slices.Contains(names, "querier.go") {
			t.Errorf("custom querier name should replace default, got %v", names)
		}

		// Uncustomized names keep defaults.
		if !slices.Contains(names, "db.go") || !slices.Contains(names, "batch.go") {
			t.Errorf("uncustomized names should keep defaults, got %v", names)
		}
	})
}

func TestSQLCDerivedConfigForFS(t *testing.T) {
	t.Parallel()

	t.Run("no config yields empty derived", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{}

		derived, err := sqlcDerivedConfigForFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if derived == nil || len(derived.dirFiles) != 0 {
			t.Errorf("expected empty derived config, got %v", derived)
		}
	})

	t.Run("v2 config output dir with default names", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(sqlcConfigV2YAML()),
		}

		derived, err := sqlcDerivedConfigForFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		names, ok := derived.dirFiles["db"]
		if !ok {
			t.Fatal("expected derived config to contain output dir 'db'")
		}

		for _, want := range []string{"db.go", "models.go", "querier.go", "batch.go", "copyfrom.go"} {
			if !names[want] {
				t.Errorf("expected %q in output dir names: %v", want, names)
			}
		}
	})

	t.Run("v1 config converts output dir and names", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(`version: "1"
packages:
  - name: "db"
    path: "internal/db"
    queries: "./sql/query/"
    schema: "./sql/schema/"
    engine: "postgresql"
    output_models_file_name: "tables.go"
`),
		}

		derived, err := sqlcDerivedConfigForFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		names, ok := derived.dirFiles["internal/db"]
		if !ok {
			t.Fatalf(
				"expected derived config to contain output dir 'internal/db', got %v",
				derived.dirFiles,
			)
		}

		if !names["tables.go"] {
			t.Errorf("expected custom tables.go in names: %v", names)
		}

		if names["models.go"] {
			t.Errorf("custom models name should replace default, got %v", names)
		}
	})
}

func TestSQLCDerivedConfigInvalidYAML(t *testing.T) {
	t.Parallel()

	t.Run("filter falls back to headerContent on invalid yaml", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile("this is not: valid: yaml: [[[\n"),
			"db/models.go": newMapFile(
				"// Code generated by sqlc. DO NOT EDIT.\npackage db\n\ntype User struct{}\n",
			),
		}

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		filter, err := NewFilter(opts, WithFS(fsys))
		if err != nil {
			t.Fatal(err)
		}

		result, err := filter.FilterDetailed("db/models.go")
		if err != nil {
			t.Fatal(err)
		}

		if !result.Filtered || result.Reason != ReasonSQLC {
			t.Errorf(
				"expected sqlc via headerContent fallback, got filtered=%v reason=%s",
				result.Filtered,
				result.Reason,
			)
		}
	})

	t.Run("unsupported version yields error from derived config", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(`version: "99"
sql: []
`),
		}

		_, err := sqlcDerivedConfigForFS(fsys, []string{"."})
		if err == nil {
			t.Fatal("expected error for unsupported version")
		}
	})
}

func TestConfigAwareSQLCReason(t *testing.T) {
	t.Parallel()

	t.Run("file in configured output dir is sqlc", func(t *testing.T) {
		t.Parallel()

		derived := &sqlcDerivedConfig{
			dirFiles: map[string]map[string]bool{
				"db": {
					"models.go": true,
					"batch.go":  true,
				},
			},
		}

		reason, ok := configAwareSQLCReason("db/models.go", derived)
		if !ok || reason != ReasonSQLC {
			t.Errorf("expected ReasonSQLC, got %v ok=%v", reason, ok)
		}
	})

	t.Run("file not in configured output dir is not sqlc", func(t *testing.T) {
		t.Parallel()

		derived := &sqlcDerivedConfig{
			dirFiles: map[string]map[string]bool{
				"db": {"models.go": true},
			},
		}

		reason, ok := configAwareSQLCReason("pkg/batch.go", derived)
		if ok || reason != ReasonNotFiltered {
			t.Errorf("expected not filtered, got %v ok=%v", reason, ok)
		}
	})

	t.Run("empty derived config is not sqlc", func(t *testing.T) {
		t.Parallel()

		derived := &sqlcDerivedConfig{dirFiles: map[string]map[string]bool{}}

		reason, ok := configAwareSQLCReason("db/models.go", derived)
		if ok || reason != ReasonNotFiltered {
			t.Errorf("expected not filtered, got %v ok=%v", reason, ok)
		}
	})

	t.Run("nil derived config is not sqlc", func(t *testing.T) {
		t.Parallel()

		reason, ok := configAwareSQLCReason("db/models.go", nil)
		if ok || reason != ReasonNotFiltered {
			t.Errorf("expected not filtered, got %v ok=%v", reason, ok)
		}
	})
}

func TestFilterSQLCConfigAwareDetection(t *testing.T) {
	t.Parallel()

	t.Run("models.go in configured dir with no header is sqlc", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml":    newMapFile(sqlcConfigV2YAML()),
			"db/models.go": newMapFile("package db\n\ntype User struct{}\n"),
		}

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		f, err := NewFilter(opts, WithFS(fsys))
		if err != nil {
			t.Fatal(err)
		}

		result, err := f.FilterDetailed("db/models.go")
		if err != nil {
			t.Fatal(err)
		}

		if !result.Filtered {
			t.Fatal("expected models.go in configured sqlc output dir to be filtered")
		}

		assertEqual(t, "Reason", result.Reason, ReasonSQLC)
	})

	t.Run("models.go without config is NOT sqlc (false-positive regression)", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"db/models.go": newMapFile("package db\n\ntype User struct{}\n"),
		}

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		f, err := NewFilter(opts, WithFS(fsys))
		if err != nil {
			t.Fatal(err)
		}

		result, err := f.FilterDetailed("db/models.go")
		if err != nil {
			t.Fatal(err)
		}

		if result.Filtered {
			t.Fatal("models.go without sqlc config must not be classified as sqlc")
		}

		assertEqual(t, "Reason", result.Reason, ReasonNotFiltered)
	})

	t.Run("batch.go outside output dir is NOT sqlc", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml":    newMapFile(sqlcConfigV2YAML()),
			"pkg/batch.go": newMapFile("package pkg\n\nfunc ProcessBatch() {}\n"),
			"db/batch.go":  newMapFile("package db\n\nfunc Batch() {}\n"),
		}

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		f, err := NewFilter(opts, WithFS(fsys))
		if err != nil {
			t.Fatal(err)
		}

		outside, err := f.FilterDetailed("pkg/batch.go")
		if err != nil {
			t.Fatal(err)
		}

		if outside.Filtered {
			t.Fatal("batch.go outside configured output dir must not be sqlc")
		}

		inside, err := f.FilterDetailed("db/batch.go")
		if err != nil {
			t.Fatal(err)
		}

		if !inside.Filtered {
			t.Fatal("batch.go in configured output dir should be sqlc")
		}
	})

	t.Run("custom output filenames honored", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(`version: "2"
sql:
  - engine: "postgresql"
    gen:
      go:
        package: "db"
        out: "db"
        output_models_file_name: "custom_models.go"
`),
			"db/custom_models.go": newMapFile("package db\n\ntype User struct{}\n"),
			"db/models.go":        newMapFile("package db\n\ntype User struct{}\n"),
		}

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		f, err := NewFilter(opts, WithFS(fsys))
		if err != nil {
			t.Fatal(err)
		}

		custom, err := f.FilterDetailed("db/custom_models.go")
		if err != nil {
			t.Fatal(err)
		}

		if !custom.Filtered {
			t.Fatal("custom models filename should be classified as sqlc in output dir")
		}

		def, err := f.FilterDetailed("db/models.go")
		if err != nil {
			t.Fatal(err)
		}

		if def.Filtered {
			t.Fatal("default models.go should NOT be sqlc when custom name configured")
		}
	})

	t.Run("header content fallback without config", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"misc/generated.go": newMapFile(
				"// Code generated by sqlc. DO NOT EDIT.\n\npackage misc\n",
			),
		}

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		f, err := NewFilter(opts, WithFS(fsys))
		if err != nil {
			t.Fatal(err)
		}

		result, err := f.FilterDetailed("misc/generated.go")
		if err != nil {
			t.Fatal(err)
		}

		if !result.Filtered {
			t.Fatal("sqlc header comment must be detected without a config")
		}

		assertEqual(t, "Reason", result.Reason, ReasonSQLC)
	})

	t.Run("query.sql.go always sqlc regardless of config", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"db/query.sql.go": newMapFile("package db\n\nfunc GetUser() {}\n"),
		}

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		f, err := NewFilter(opts, WithFS(fsys))
		if err != nil {
			t.Fatal(err)
		}

		result, err := f.FilterDetailed("db/query.sql.go")
		if err != nil {
			t.Fatal(err)
		}

		if !result.Filtered {
			t.Fatal("query.sql.go must always be sqlc via filename suffix")
		}

		assertEqual(t, "Reason", result.Reason, ReasonSQLC)
	})

	t.Run("derived config cached across calls", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml":    newMapFile(sqlcConfigV2YAML()),
			"db/models.go": newMapFile("package db\n"),
		}

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		f, err := NewFilter(opts, WithFS(fsys))
		if err != nil {
			t.Fatal(err)
		}

		r1, err := f.FilterDetailed("db/models.go")
		if err != nil {
			t.Fatal(err)
		}

		if !r1.Filtered {
			t.Fatal("first call should detect sqlc via config")
		}

		// Second call must not error and use the cached derived config.
		r2, err := f.FilterDetailed("db/models.go")
		if err != nil {
			t.Fatal(err)
		}

		if !r2.Filtered {
			t.Fatal("second call should still detect sqlc via cached config")
		}
	})
}

func TestOutputFilesSuffix(t *testing.T) {
	t.Parallel()

	t.Run("configuredSQLCFileNames does not include per-query suffix files", func(t *testing.T) {
		t.Parallel()

		//nolint:exhaustruct // only Out + suffix matter
		names := configuredSQLCFileNames(&sqlcGoConfig{
			Out:               "db",
			OutputFilesSuffix: "_gen",
		})

		// The 5 fixed names are present, but no per-query suffix names.
		for _, want := range []string{"db.go", "models.go", "querier.go", "batch.go", "copyfrom.go"} {
			if !slices.Contains(names, want) {
				t.Errorf("expected %q in names, got %v", want, names)
			}
		}

		if slices.Contains(names, "query.sql_gen.go") {
			t.Errorf("per-query suffix file should NOT be in configuredSQLCFileNames: %v", names)
		}
	})

	t.Run("query.sql_gen.go does not match filename pattern", func(t *testing.T) {
		t.Parallel()

		if matchesSQLCFilenamePattern("query.sql_gen.go") {
			t.Error("query.sql_gen.go should NOT match .sql.go filename pattern")
		}

		// Default per-query name DOES match.
		if !matchesSQLCFilenamePattern("query.sql.go") {
			t.Error("query.sql.go should match .sql.go filename pattern")
		}
	})

	t.Run("query.sql_gen.go with suffix detected via content, not config", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(`version: "2"
sql:
  - engine: "postgresql"
    gen:
      go:
        package: "db"
        out: "db"
        output_files_suffix: "_gen"
`),
			"db/query.sql_gen.go": newMapFile(
				"// Code generated by sqlc. DO NOT EDIT.\npackage db\n\nfunc GetUser() {}\n",
			),
		}

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		f, err := NewFilter(opts, WithFS(fsys))
		if err != nil {
			t.Fatal(err)
		}

		result, err := f.FilterDetailed("db/query.sql_gen.go")
		if err != nil {
			t.Fatal(err)
		}

		if !result.Filtered {
			t.Fatal("query.sql_gen.go with sqlc header should be detected via content")
		}

		assertEqual(t, "Reason", result.Reason, ReasonSQLC)

		// The trace should indicate content-based detection, not config-based.
		if result.Trace == sqlcConfigTrace {
			t.Errorf(
				"query.sql_gen.go should NOT be detected via config (not in derived names), got trace=%q",
				result.Trace,
			)
		}
	})

	t.Run(
		"query.sql_gen.go without header and without filename match is not detected",
		func(t *testing.T) {
			t.Parallel()

			fsys := fstest.MapFS{
				"sqlc.yaml": newMapFile(`version: "2"
sql:
  - engine: "postgresql"
    gen:
      go:
        package: "db"
        out: "db"
        output_files_suffix: "_gen"
`),
				"db/query.sql_gen.go": newMapFile("package db\n\nfunc GetUser() {}\n"),
			}

			opts, err := WithFilterOptions(FilterSQLC)
			if err != nil {
				t.Fatal(err)
			}

			f, err := NewFilter(opts, WithFS(fsys))
			if err != nil {
				t.Fatal(err)
			}

			result, err := f.FilterDetailed("db/query.sql_gen.go")
			if err != nil {
				t.Fatal(err)
			}

			if result.Filtered {
				t.Errorf(
					"query.sql_gen.go without header and without .sql.go suffix should not be detected, got reason=%s",
					result.Reason,
				)
			}
		},
	)
}

func TestNestedSQLCConfig(t *testing.T) {
	t.Parallel()

	t.Run("FindSQLCConfigsFS walks into subdirectories", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"services/api/sqlc.yaml": newMapFile(sqlcConfigV2YAML()),
		}

		configs, err := FindSQLCConfigsFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(configs) != 1 {
			t.Fatalf("expected 1 config, got %d: %v", len(configs), configs)
		}

		for configPath := range configs {
			if configPath != "services/api/sqlc.yaml" {
				t.Errorf("expected config at services/api/sqlc.yaml, got %q", configPath)
			}
		}
	})

	t.Run("derived config built from nested config", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"services/api/sqlc.yaml": newMapFile(sqlcConfigV2YAML()),
		}

		derived, err := sqlcDerivedConfigForFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		// mergeSQLCConfig stores goCfg.Out directly (not resolved against
		// the config's parent directory). The config says out: "db".
		names, ok := derived.dirFiles["db"]
		if !ok {
			t.Fatalf("expected derived config to contain output dir 'db', got %v", derived.dirFiles)
		}

		if !names["models.go"] {
			t.Errorf("expected models.go in derived names, got %v", names)
		}
	})

	t.Run("deeply nested config found at 3+ levels", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"apps/backend/internal/repo/sqlc.yaml": newMapFile(sqlcConfigV2YAML()),
		}

		configs, err := FindSQLCConfigsFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(configs) != 1 {
			t.Fatalf("expected 1 deeply nested config, got %d: %v", len(configs), configs)
		}
	})

	t.Run("multiple configs at different depths", func(t *testing.T) {
		t.Parallel()

		mysqlConfig := `version: "2"
sql:
  - engine: "mysql"
    gen:
      go:
        package: "repo"
        out: "repo"
`

		fsys := fstest.MapFS{
			"sqlc.yaml":              newMapFile(sqlcConfigV2YAML()),
			"services/api/sqlc.yaml": newMapFile(mysqlConfig),
		}

		configs, err := FindSQLCConfigsFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		if len(configs) != 2 {
			t.Fatalf("expected 2 configs at different depths, got %d: %v", len(configs), configs)
		}
	})
}

func TestMultipleSQLEngines(t *testing.T) {
	t.Parallel()

	multiEngineYAML := `version: "2"
sql:
  - engine: "postgresql"
    schema: "postgres/schema/"
    gen:
      go:
        package: "pgdb"
        out: "postgres/db"
  - engine: "mysql"
    schema: "mysql/schema/"
    gen:
      go:
        package: "mydb"
        out: "mysql/db"
`

	t.Run("derived config has both output dirs", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(multiEngineYAML),
		}

		derived, err := sqlcDerivedConfigForFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		pgNames, ok := derived.dirFiles["postgres/db"]
		if !ok {
			t.Fatalf("expected output dir 'postgres/db', got %v", derived.dirFiles)
		}

		if !pgNames["models.go"] {
			t.Errorf("expected models.go in postgres/db: %v", pgNames)
		}

		myNames, ok := derived.dirFiles["mysql/db"]
		if !ok {
			t.Fatalf("expected output dir 'mysql/db', got %v", derived.dirFiles)
		}

		if !myNames["models.go"] {
			t.Errorf("expected models.go in mysql/db: %v", myNames)
		}
	})

	t.Run("filter detects files in both output dirs", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml":             newMapFile(multiEngineYAML),
			"postgres/db/models.go": newMapFile("package pgdb\ntype User struct{}\n"),
			"mysql/db/models.go":    newMapFile("package mydb\ntype Product struct{}\n"),
			"other/models.go":       newMapFile("package other\ntype Foo struct{}\n"),
		}

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		f, err := NewFilter(opts, WithFS(fsys))
		if err != nil {
			t.Fatal(err)
		}

		pgResult, err := f.FilterDetailed("postgres/db/models.go")
		if err != nil {
			t.Fatal(err)
		}

		if !pgResult.Filtered || pgResult.Reason != ReasonSQLC {
			t.Errorf(
				"expected postgres/db/models.go to be sqlc, got filtered=%v reason=%s",
				pgResult.Filtered,
				pgResult.Reason,
			)
		}

		myResult, err := f.FilterDetailed("mysql/db/models.go")
		if err != nil {
			t.Fatal(err)
		}

		if !myResult.Filtered || myResult.Reason != ReasonSQLC {
			t.Errorf(
				"expected mysql/db/models.go to be sqlc, got filtered=%v reason=%s",
				myResult.Filtered,
				myResult.Reason,
			)
		}

		otherResult, err := f.FilterDetailed("other/models.go")
		if err != nil {
			t.Fatal(err)
		}

		if otherResult.Filtered {
			t.Errorf(
				"other/models.go should NOT be sqlc (outside output dirs), got reason=%s",
				otherResult.Reason,
			)
		}
	})

	t.Run("different custom filenames per engine", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(`version: "2"
sql:
  - engine: "postgresql"
    gen:
      go:
        package: "pgdb"
        out: "pg"
        output_models_file_name: "pg_models.go"
  - engine: "mysql"
    gen:
      go:
        package: "mydb"
        out: "my"
        output_models_file_name: "my_models.go"
`),
		}

		derived, err := sqlcDerivedConfigForFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		pgNames := derived.dirFiles["pg"]
		if !pgNames["pg_models.go"] {
			t.Errorf("expected pg_models.go in pg: %v", pgNames)
		}

		if pgNames["models.go"] {
			t.Errorf("models.go should NOT be in pg (custom name configured): %v", pgNames)
		}

		myNames := derived.dirFiles["my"]
		if !myNames["my_models.go"] {
			t.Errorf("expected my_models.go in my: %v", myNames)
		}
	})
}

func TestPluginCodegenOutput(t *testing.T) {
	t.Parallel()

	codegenYAML := `version: "2"
sql:
  - engine: "postgresql"
    schema: "schema/"
    gen:
      go:
        package: "db"
        out: "db"
    codegen:
      - plugin: "my-plugin"
        out: "plugin_out"
`

	t.Run("GetSQLOutputDirsFS includes plugin codegen output", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(codegenYAML),
		}

		dirs, err := GetSQLOutputDirsFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		foundGo := false
		foundPlugin := false

		for _, d := range dirs {
			if strings.Contains(d, "db") {
				foundGo = true
			}

			if strings.Contains(d, "plugin_out") {
				foundPlugin = true
			}
		}

		if !foundGo {
			t.Errorf("expected Go output dir in %v", dirs)
		}

		if !foundPlugin {
			t.Errorf("expected plugin codegen output dir in %v", dirs)
		}
	})

	t.Run("derived config does NOT track plugin codegen dir", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(codegenYAML),
		}

		derived, err := sqlcDerivedConfigForFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		// mergeSQLCConfig only processes engine.Gen.Go, not engine.Codegen.
		// Plugin output dirs have unknown filename patterns, so they are
		// intentionally excluded from config-aware detection.
		if _, ok := derived.dirFiles["plugin_out"]; ok {
			t.Errorf(
				"plugin codegen dir should NOT be in derived config (unknown filenames): %v",
				derived.dirFiles,
			)
		}

		// The Go output dir IS tracked.
		if _, ok := derived.dirFiles["db"]; !ok {
			t.Errorf("expected Go output dir 'db' in derived config: %v", derived.dirFiles)
		}
	})

	t.Run("file in plugin output dir not detected via config", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml":               newMapFile(codegenYAML),
			"plugin_out/generated.go": newMapFile("package plugin_out\n"),
			"db/models.go":            newMapFile("package db\n"),
		}

		opts, err := WithFilterOptions(FilterSQLC)
		if err != nil {
			t.Fatal(err)
		}

		f, err := NewFilter(opts, WithFS(fsys))
		if err != nil {
			t.Fatal(err)
		}

		// db/models.go IS detected via config-aware detection.
		dbResult, err := f.FilterDetailed("db/models.go")
		if err != nil {
			t.Fatal(err)
		}

		if !dbResult.Filtered {
			t.Error("db/models.go should be detected via config-aware sqlc detection")
		}

		// plugin_out/generated.go is NOT detected — plugin codegen dirs are
		// excluded from config-aware detection because their filenames are
		// plugin-dependent and unknowable.
		pluginResult, err := f.FilterDetailed("plugin_out/generated.go")
		if err != nil {
			t.Fatal(err)
		}

		if pluginResult.Filtered {
			t.Errorf(
				"plugin_out/generated.go should NOT be config-detected: reason=%s",
				pluginResult.Reason,
			)
		}
	})
}

func TestJSONOutputConfig(t *testing.T) {
	t.Parallel()

	jsonYAML := `version: "2"
sql:
  - engine: "postgresql"
    schema: "schema/"
    gen:
      go:
        package: "db"
        out: "db"
      json:
        out: "json_out"
`

	t.Run("config with JSON output parses correctly", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(jsonYAML),
		}

		configs, err := FindSQLCConfigsFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		for configPath := range configs {
			config, cfgErr := parseSQLCConfigFS(fsys, configPath)
			if cfgErr != nil {
				t.Fatalf("parse error: %v", cfgErr)
			}

			if config.SQL[0].Gen.JSON == nil {
				t.Fatal("expected JSON config to be parsed")
			}

			assertEqual(t, "JSON.Out", config.SQL[0].Gen.JSON.Out, "json_out")
		}
	})

	t.Run("GetSQLOutputDirsFS includes JSON output dir", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(jsonYAML),
		}

		dirs, err := GetSQLOutputDirsFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		foundGo := false
		foundJSON := false

		for _, d := range dirs {
			if strings.Contains(d, "db") {
				foundGo = true
			}

			if strings.Contains(d, "json_out") {
				foundJSON = true
			}
		}

		if !foundGo {
			t.Errorf("expected Go output dir in %v", dirs)
		}

		if !foundJSON {
			t.Errorf("expected JSON output dir in %v", dirs)
		}
	})

	t.Run("derived config tracks Go output but not JSON", func(t *testing.T) {
		t.Parallel()

		fsys := fstest.MapFS{
			"sqlc.yaml": newMapFile(jsonYAML),
		}

		derived, err := sqlcDerivedConfigForFS(fsys, []string{"."})
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}

		// Go output dir IS tracked.
		if _, ok := derived.dirFiles["db"]; !ok {
			t.Errorf("expected Go output dir 'db' in derived config: %v", derived.dirFiles)
		}

		// JSON output dir is NOT tracked — JSON output contains JSON files,
		// not Go files, so config-aware Go filename detection does not apply.
		if _, ok := derived.dirFiles["json_out"]; ok {
			t.Errorf("JSON output dir should NOT be in derived config: %v", derived.dirFiles)
		}
	})
}
