package gogenfilter

//nolint:gochecknoglobals
var generatedTestCases = []generatorTestCase{
	{
		name: "SQLC",
		fn:   IsSQLCGenerated,
		tests: generatedFileTests4(
			"sqlc",
			"db/models.go", "// Code generated by sqlc. DO NOT EDIT.\npackage db\n\ntype User struct {\n\tID int\n}",
			"db/query.sql.go", "package db\n\n// versions:\n//   sqlc v1.25.0\n",
			"db/models.go", "package db\n\ntype User struct {\n\tID string\n}",
			"models/user.go", "// Code generated by sqlc. DO NOT EDIT.\npackage models\n",
		),
	},
	{
		name: "Templ",
		fn:   IsTemplGenerated,
		tests: []generatedFileTest{
			{
				name:     "templ generated file",
				filePath: "components/header_templ.go",
				content: "// Code generated by templ DO NOT EDIT\n\npackage components\n\n" +
					"import (\n\t\"context\"\n\t\"io\"\n\t\"github.com/a-h/templ\"\n)\n\n" +
					"func header(name string) templ.Component {\n\treturn templ.ComponentFunc(nil)\n}",
				expected: true,
			},
			{
				name:     "templ with Render method",
				filePath: "page_templ.go",
				content: "package main\n\n" +
					"import (\n\t\"context\"\n\t\"io\"\n)\n\n" +
					"func Page() string {\n\treturn \"\"\n}\n\n" +
					"func (p *Page) Render(ctx context.Context, w io.Writer) error {\n\treturn nil\n}",
				expected: true,
			},
			{
				name:     "not templ - regular file",
				filePath: "components/helper.go",
				content:  "package components\n\nfunc Helper() string {\n\treturn \"helper\"\n}",
				expected: false,
			},
			{
				name:     "templ suffix but no templ content",
				filePath: "utils_templ.go",
				content:  "package utils\n\nfunc Process() string {\n\treturn \"\"\n}",
				expected: false,
			},
		},
	},
	{
		name: "GoEnum",
		fn:   IsGoEnumGenerated,
		tests: []generatedFileTest{
			{
				name:     "go-enum generated file",
				filePath: "enums/status_enum.go",
				content:  "// Code generated by go-enum DO NOT EDIT.\npackage enums\n\ntype Status int",
				expected: true,
			},
			{
				name:     "not go-enum - regular file",
				filePath: "models/user.go",
				content:  "package models\n\ntype User struct {\n\tID   int\n\tName string\n}",
				expected: false,
			},
			{
				name:     "wrong filename - not _enum.go suffix",
				filePath: "enums/status.go",
				content:  "// Code generated by go-enum DO NOT EDIT.\npackage enums\n\ntype Status int",
				expected: false,
			},
		},
	},
	{
		name: "Protobuf",
		fn:   IsProtobufGenerated,
		tests: generatedFileTests4(
			"protobuf",
			"pb/user.pb.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
			"pb/user_grpc.pb.go", "// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\npackage pb\n",
			"pb/user.pb.go", "package pb\n",
			"pb/user.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
		),
	},
	{
		name: "Mockgen",
		fn:   IsMockgenGenerated,
		tests: simpleGeneratedFileTests(
			"mockgen",
			"mocks/service_mock.go",
			"// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n",
			"service/service.go",
			"package service\nfunc New() *Service { return nil }\n",
		),
	},
	{
		name: "Stringer",
		fn:   IsStringerGenerated,
		tests: simpleGeneratedFileTests(
			"stringer",
			"enums/status_string.go",
			"// Code generated by \"stringer\". DO NOT EDIT.\npackage enums\n",
			"enums/status.go",
			"package enums\ntype Status int\n",
		),
	},
	{
		name: "Generic",
		fn:   IsGenericGenerated,
		tests: []generatedFileTest{
			{
				name:     "generic generated file",
				filePath: "generated/custom.go",
				content:  "// Code generated by my-custom-tool. DO NOT EDIT.\npackage generated\n",
				expected: true,
			},
			{
				name:     "generic catches sqlc comment",
				filePath: "db/models.go",
				content:  "// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
				expected: true,
			},
			{
				name:     "not generated - no comment",
				filePath: "regular/file.go",
				content:  "package regular\nfunc DoSomething() {}\n",
				expected: false,
			},
		},
	},
}

//nolint:funlen
func shouldFilterTestCases() []shouldFilterTestCase {
	return []shouldFilterTestCase{
		newShouldFilterTest(
			"filters sqlc file",
			"models.go",
			"// Code generated by sqlc. DO NOT EDIT.\npackage db\ntype User struct {}\n",
			FilterSQLC,
		),
		newShouldFilterTest(
			"filters templ file",
			"header_templ.go",
			"package components\nimport \"github.com/a-h/templ\"\nfunc header() templ.Component { return nil }\n",
			FilterTempl,
		),
		{
			name:         "does not filter regular file",
			fileName:     "main.go",
			content:      "package main\nfunc main() {}\n",
			opts:         []FilterOption{FilterAll},
			shouldFilter: false,
		},
		newShouldFilterTest(
			"filters go-enum file",
			"status_enum.go",
			"// Code generated by go-enum DO NOT EDIT.\npackage enums\nconst StatusPending Status = iota\n",
			FilterGoEnum,
		),
		newShouldFilterTest(
			"filters protobuf .pb.go file",
			"user.pb.go",
			"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
			FilterProtobuf,
		),
		newShouldFilterTest(
			"filters protobuf grpc file",
			"user_grpc.pb.go",
			"// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\npackage pb\n",
			FilterProtobuf,
		),
		newShouldFilterTest(
			"filters mockgen file",
			"service_mock.go",
			"// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n",
			FilterMockgen,
		),
		newShouldFilterTest(
			"filters stringer file",
			"status_string.go",
			"// Code generated by \"stringer\". DO NOT EDIT.\npackage enums\n",
			FilterStringer,
		),
		newShouldFilterTest(
			"filters generic generated file",
			"custom_gen.go",
			"// Code generated by custom-tool. DO NOT EDIT.\npackage main\n",
			FilterGeneric,
		),
		{
			name:         "generic does not filter without comment",
			fileName:     "regular.go",
			content:      "package main\nfunc main() {}\n",
			opts:         []FilterOption{FilterGeneric},
			shouldFilter: false,
		},
	}
}

func detectGeneratedTestCases() []filenameTestCase {
	return []filenameTestCase{
		{
			"detects sqlc by filename",
			"db/models.go",
			map[FilterOption]bool{FilterSQLC: true},
			ReasonSQLC,
		},
		{
			"detects templ by filename",
			"page_templ.go",
			map[FilterOption]bool{FilterTempl: true},
			ReasonTempl,
		},
		{
			"detects go-enum by filename",
			"status_enum.go",
			map[FilterOption]bool{FilterGoEnum: true},
			ReasonGoEnum,
		},
		{
			"detects protobuf .pb.go by filename",
			"user.pb.go",
			map[FilterOption]bool{FilterProtobuf: true},
			ReasonProtobuf,
		},
		{
			"detects protobuf grpc by filename",
			"user_grpc.pb.go",
			map[FilterOption]bool{FilterProtobuf: true},
			ReasonProtobuf,
		},
		{
			"detects mockgen _mock.go by filename",
			"service_mock.go",
			map[FilterOption]bool{FilterMockgen: true},
			ReasonMockgen,
		},
		{
			"detects mockgen mock_ by filename",
			"mock_service.go",
			map[FilterOption]bool{FilterMockgen: true},
			ReasonMockgen,
		},
		{
			"does not match mock_ in middle of filename",
			"remove_mock_data.go",
			map[FilterOption]bool{FilterMockgen: true},
			ReasonNotFiltered,
		},
		{
			"returns not filtered for regular file",
			"main.go",
			map[FilterOption]bool{FilterSQLC: true},
			ReasonNotFiltered,
		},
	}
}
