// Package gogenfilter detects and filters auto-generated Go code files.
//
// It identifies files generated by common tools like sqlc.dev, templ.guide,
// go-enum, protobuf, mockgen, and any tool using the standard
// "Code generated by" comment convention.
//
// Detection is two-phase: filename-based first (zero I/O), then content-based
// (reads file). This optimization avoids unnecessary file reads.
package gogenfilter

// FilterOption represents a type of generated code to filter.
type FilterOption string

// stringFrom returns the string representation of a string-based type.
func stringFrom[T ~string](t T) string { return string(t) }

// Validatable is implemented by types that can validate themselves.
type Validatable interface {
	IsValid() bool
}

func (o FilterOption) String() string { return stringFrom(o) }

// Reason returns the FilterReason corresponding to this FilterOption.
// Since FilterOption and FilterReason share the same underlying string values,
// this is a direct type conversion. For example, FilterSQLC.Reason() == ReasonSQLC.
func (o FilterOption) Reason() FilterReason { return FilterReason(o) }

// IsValid reports whether the FilterOption is a recognized value.
func (o FilterOption) IsValid() bool {
	switch o {
	case FilterSQLC, FilterTempl, FilterGoEnum, FilterProtobuf,
		FilterMockgen, FilterStringer, FilterGeneric, FilterAll:
		return true

	default:
		return false
	}
}

const (
	// FilterSQLC filters sqlc.dev generated files.
	FilterSQLC FilterOption = "sqlc"

	// FilterTempl filters templ.guide generated files.
	FilterTempl FilterOption = "templ"

	// FilterGoEnum filters go-enum generated files.
	FilterGoEnum FilterOption = "go-enum"

	// FilterProtobuf filters protoc-gen-go generated files (.pb.go, _grpc.pb.go).
	FilterProtobuf FilterOption = "protobuf"

	// FilterMockgen filters mockgen generated files.
	FilterMockgen FilterOption = "mockgen"

	// FilterStringer filters stringer generated files.
	FilterStringer FilterOption = "stringer"

	// FilterGeneric filters any file with the standard "Code generated by" comment.
	// This catches all Go generators that follow the convention from https://go.dev/s/generatedcode.
	// It acts as a fallback after specific detectors have been checked.
	FilterGeneric FilterOption = "generic"

	// FilterAll filters all auto-generated code.
	FilterAll FilterOption = "all"
)

// FilterReason represents the reason a file was filtered.
type FilterReason string

func (r FilterReason) String() string { return stringFrom(r) }

// IsValid reports whether the FilterReason is a recognized value.
func (r FilterReason) IsValid() bool {
	switch r {
	case ReasonSQLC, ReasonTempl, ReasonGoEnum, ReasonProtobuf,
		ReasonMockgen, ReasonStringer, ReasonGeneric,
		ReasonIncludePattern, ReasonExcludePattern, ReasonNotFiltered:
		return true

	default:
		return false
	}
}

// FilterReason values for each supported generator and special filter outcomes.
const (
	ReasonSQLC           FilterReason = "sqlc"
	ReasonTempl          FilterReason = "templ"
	ReasonGoEnum         FilterReason = "go-enum"
	ReasonProtobuf       FilterReason = "protobuf"
	ReasonMockgen        FilterReason = "mockgen"
	ReasonStringer       FilterReason = "stringer"
	ReasonGeneric        FilterReason = "generic"
	ReasonIncludePattern FilterReason = "include-pattern"
	ReasonExcludePattern FilterReason = "exclude-pattern"
	ReasonNotFiltered    FilterReason = "not-filtered"
)

// codeGeneratedPrefix is the standard prefix for Go code generation comments.
// See https://go.dev/s/generatedcode for the specification.
const codeGeneratedPrefix = "// Code generated by"

// AllFilterOptions returns all valid FilterOption values.
func AllFilterOptions() []FilterOption {
	return []FilterOption{
		FilterSQLC, FilterTempl, FilterGoEnum, FilterProtobuf,
		FilterMockgen, FilterStringer, FilterGeneric, FilterAll,
	}
}

// AllFilterReasons returns all valid FilterReason values.
func AllFilterReasons() []FilterReason {
	return []FilterReason{
		ReasonSQLC, ReasonTempl, ReasonGoEnum, ReasonProtobuf,
		ReasonMockgen, ReasonStringer, ReasonGeneric,
		ReasonIncludePattern, ReasonExcludePattern, ReasonNotFiltered,
	}
}

// maxProjectRootDepth is the maximum number of parent directories to search
// when looking for project root markers.
const maxProjectRootDepth = 10

//nolint:gochecknoglobals // immutable lookup table, never mutated
var allSpecificOptions = []FilterOption{
	FilterSQLC,
	FilterTempl,
	FilterGoEnum,
	FilterProtobuf,
	FilterMockgen,
	FilterStringer,
}
