// Package gogenfilter detects and filters auto-generated Go code files.
//
// It identifies files generated by common tools like sqlc.dev, templ.guide,
// and go-enum so that linters and analysis tools can skip them.
//
// Detection is two-phase: filename-based first (zero I/O), then content-based
// (reads file). This optimization avoids unnecessary file reads.
package gogenfilter

// FilterOption represents a type of generated code to filter.
type FilterOption string

const (
	// FilterSQLC filters sqlc.dev generated files.
	FilterSQLC FilterOption = "sqlc"

	// FilterTempl filters templ.guide generated files.
	FilterTempl FilterOption = "templ"

	// FilterGoEnum filters go-enum generated files.
	FilterGoEnum FilterOption = "go-enum"

	// FilterAll filters all auto-generated code.
	FilterAll FilterOption = "all"
)

// FilterReason represents the reason a file was filtered.
type FilterReason string

const (
	ReasonSQLC           FilterReason = "sqlc"
	ReasonTempl          FilterReason = "templ"
	ReasonGoEnum         FilterReason = "go-enum"
	ReasonIncludePattern FilterReason = "include-pattern"
	ReasonExcludePattern FilterReason = "exclude-pattern"
	ReasonNotFiltered    FilterReason = "not-filtered"
)

// sqlcFilePatterns contains the standard filename patterns for sqlc.dev generated files.
var sqlcFilePatterns = []string{
	"models.go",
	"querier.go",
	"query.sql.go",
	"batch.go",
}
