// Package gogenfilter detects and filters auto-generated Go code files.
//
// It identifies files generated by common tools including sqlc, templ, go-enum,
// protobuf, oapi-codegen, deepcopy-gen, wire, moq, mockgen, stringer, and any
// tool using the standard "Code generated by" comment convention per
// https://go.dev/s/generatedcode.
//
// Detection is two-phase: filename-based first (zero I/O), then content-based
// (reads file). This optimization avoids unnecessary file reads.
//
// # Quick Start
//
// Create a filter with functional options:
//
//	f := gogenfilter.NewFilter(
//	    gogenfilter.Enabled(),
//	    gogenfilter.WithFilterOptions(gogenfilter.FilterAll),
//	)
//
// Check files — ShouldFilter returns (bool, error) to propagate I/O errors:
//
//	filtered, err := f.ShouldFilter("db/models.go")
//	if err != nil {
//	    log.Fatal(err)
//	}
//	if filtered {
//	    fmt.Println("skipping generated file")
//	}
//
// For low-level detection without a Filter:
//
//	reason := gogenfilter.DetectReason("file.go", content,
//	    gogenfilter.FilterSQLC,
//	    gogenfilter.FilterGeneric,
//	)
package gogenfilter

// FilterOption represents a type of generated code to filter.
type FilterOption string

// Validatable is implemented by types that can validate themselves.
type Validatable interface {
	IsValid() bool
}

func (o FilterOption) String() string { return string(o) }

// Reason returns the FilterReason corresponding to this FilterOption.
// Since FilterOption and FilterReason share the same underlying string values,
// this is a direct type conversion. For example, FilterSQLC.Reason() == ReasonSQLC.
func (o FilterOption) Reason() FilterReason { return FilterReason(o) }

// IsValid reports whether the FilterOption is a recognized value.
func (o FilterOption) IsValid() bool {
	for _, opt := range AllFilterOptions() {
		if o == opt {
			return true
		}
	}

	return false
}

const (
	// FilterSQLC filters sqlc.dev generated files.
	FilterSQLC FilterOption = "sqlc"

	// FilterTempl filters templ.guide generated files.
	FilterTempl FilterOption = "templ"

	// FilterGoEnum filters go-enum generated files.
	FilterGoEnum FilterOption = "go-enum"

	// FilterProtobuf filters protoc-gen-go generated files (.pb.go, _grpc.pb.go).
	FilterProtobuf FilterOption = "protobuf"

	// FilterOapi filters oapi-codegen generated files (*.gen.go with oapi-codegen markers).
	FilterOapi FilterOption = "oapi-codegen"

	// FilterDeepcopy filters deepcopy-gen generated files (Kubernetes ecosystem).
	FilterDeepcopy FilterOption = "deepcopy-gen"

	// FilterWire filters google/wire generated dependency injection files.
	FilterWire FilterOption = "wire"

	// FilterMoq filters matryer/moq generated mock files.
	FilterMoq FilterOption = "moq"

	// FilterMockgen filters mockgen generated files.
	FilterMockgen FilterOption = "mockgen"

	// FilterStringer filters stringer generated files.
	FilterStringer FilterOption = "stringer"

	// FilterGeneric filters any file with the standard "Code generated by" comment.
	// This catches all Go generators that follow the convention from https://go.dev/s/generatedcode.
	// It acts as a fallback after specific detectors have been checked.
	FilterGeneric FilterOption = "generic"

	// FilterAll filters all auto-generated code.
	FilterAll FilterOption = "all"
)

// FilterReason represents the reason a file was filtered.
type FilterReason string

func (r FilterReason) String() string { return string(r) }

// IsValid reports whether the FilterReason is a recognized value.
func (r FilterReason) IsValid() bool {
	for _, reason := range AllFilterReasons() {
		if r == reason {
			return true
		}
	}

	return false
}

// FilterReason values for each supported generator and special filter outcomes.
const (
	ReasonSQLC           FilterReason = "sqlc"
	ReasonTempl          FilterReason = "templ"
	ReasonGoEnum         FilterReason = "go-enum"
	ReasonProtobuf       FilterReason = "protobuf"
	ReasonOapi           FilterReason = "oapi-codegen"
	ReasonDeepcopy       FilterReason = "deepcopy-gen"
	ReasonWire           FilterReason = "wire"
	ReasonMoq            FilterReason = "moq"
	ReasonMockgen        FilterReason = "mockgen"
	ReasonStringer       FilterReason = "stringer"
	ReasonGeneric        FilterReason = "generic"
	ReasonIncludePattern FilterReason = "include-pattern"
	ReasonExcludePattern FilterReason = "exclude-pattern"
	ReasonNotFiltered    FilterReason = "not-filtered"
)

// codeGeneratedPrefix is the standard prefix for Go code generation comments.
// See https://go.dev/s/generatedcode for the specification.
const codeGeneratedPrefix = "// Code generated by"

// AllFilterOptions returns all valid FilterOption values.
// Derived from the detectors table plus FilterAll, so adding a new detector
// automatically updates this list.
func AllFilterOptions() []FilterOption {
	opts := make([]FilterOption, 0, len(detectors)+1)

	for _, d := range detectors {
		opts = append(opts, d.option)
	}

	return append(opts, FilterAll)
}

// AllFilterReasons returns all valid FilterReason values.
// Derived from the detectors table plus special reasons (include/exclude/not-filtered),
// so adding a new detector automatically updates this list.
func AllFilterReasons() []FilterReason {
	reasons := make([]FilterReason, 0, len(detectors)+3)

	for _, d := range detectors {
		reasons = append(reasons, d.reason)
	}

	return append(reasons, ReasonIncludePattern, ReasonExcludePattern, ReasonNotFiltered)
}

// maxProjectRootDepth is the maximum number of parent directories to search
// when looking for project root markers.
const maxProjectRootDepth = 10
