// Package testhelpers provides shared test constants for gogenfilter tests.
package testhelpers

// Test constants used across multiple test packages.
const (
	// TestMarkerGoMod is the marker file used to identify a Go project root.
	TestMarkerGoMod = "go.mod"

	// DbModelsGo is the path to SQLC generated models file.
	DbModelsGo = "db/models.go"

	// MainGo is the main Go file path.
	MainGo = "main.go"

	// FileGo is a generic Go file path for testing.
	FileGo = "file.go"

	// SqlcConfigFile is the SQLC configuration file name.
	SqlcConfigFile = "sqlc.yaml"

	// SQLCGeneratedContentTest is sample SQLC generated file content.
	SQLCGeneratedContentTest = "// Code generated by sqlc. DO NOT EDIT.\npackage db\n"

	// MyToolGenContentTest is sample tool generated file content.
	MyToolGenContentTest = "// Code generated by my-tool. DO NOT EDIT.\npackage main\n"

	// MoqGeneratedContentTest is sample moq generated file content.
	MoqGeneratedContentTest = "// Code generated by moq; DO NOT EDIT.\npackage service\n"

	// GoEnumContentTest is sample go-enum generated file content.
	GoEnumContentTest = "// Code generated by go-enum DO NOT EDIT.\npackage enums\n"
)
