// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: user.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
)

type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}
