// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownBytes  protoimpl.UnknownFields
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}
