// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"context"
)

type Resolver struct{}

func (r *queryResolver) Hello(ctx context.Context) (*string, error) {
	return nil, nil
}
