// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package example

import "github.com/tinylib/msgp/msgp"

type MyStruct struct {
	Name string
}

func (z *MyStruct) EncodeMsg(w *msgp.Writer) error { return nil }
