// Code generated by MockGen. DO NOT EDIT.
// source: service.go

package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

type MockServiceMockRecorder struct {
	mock *MockService
}

func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}
