// Package gogenfilter provides a golangci-lint v2 module plugin that detects
// auto-generated Go files using the gogenfilter library.
//
// The plugin reports a diagnostic for each file that gogenfilter classifies as
// auto-generated, naming the detected generator (sqlc, templ, protobuf, etc.).
// Users can then configure golangci-lint issue exclusions to skip these files
// in other linters.
//
// To use:
//
//	# .custom-gcl.yml
//	version: v2.4.0
//	plugins:
//	  - module: 'github.com/LarsArtmann/gogenfilter/plugin'
//	    import: 'github.com/LarsArtmann/gogenfilter/plugin'
//	    version: v0.1.0
//
//	# .golangci.yml
//	version: "2"
//	linters:
//	  default: none
//	  enable:
//	    - gogenfilter
//	  settings:
//	    custom:
//	      gogenfilter:
//	        type: module
//	        description: "Detect auto-generated Go files"
//	        settings:
//	          generators:
//	            - sqlc
//	            - templ
package plugin

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/LarsArtmann/gogenfilter/v3"
	"github.com/golangci/plugin-module-register/register"
	"golang.org/x/tools/go/analysis"
)

func init() {
	register.Plugin("gogenfilter", New)
}

// Settings configures the gogenfilter linter.
type Settings struct {
	// Generators restricts detection to specific generators (e.g., "sqlc", "templ").
	// When empty, all generators are detected.
	Generators []string `json:"generators"`

	// ExcludePaths adds glob patterns to exclude from detection
	// (e.g., "vendor/**", "**/testdata/**").
	ExcludePaths []string `json:"exclude-paths"`
}

type gogenfilterPlugin struct {
	settings Settings
	filter   *gogenfilter.Filter
}

// New creates a new gogenfilter linter plugin from the given settings.
func New(conf any) (register.LinterPlugin, error) {
	s, err := register.DecodeSettings[Settings](conf)
	if err != nil {
		return nil, fmt.Errorf("gogenfilter: decode settings: %w", err)
	}

	return &gogenfilterPlugin{settings: s}, nil
}

// BuildAnalyzers implements register.LinterPlugin.
func (p *gogenfilterPlugin) BuildAnalyzers() ([]*analysis.Analyzer, error) {
	opts, err := p.buildFilterOptions()
	if err != nil {
		return nil, err
	}

	configs := []gogenfilter.FilterConfig{opts}
	if len(p.settings.ExcludePaths) > 0 {
		configs = append(configs, gogenfilter.WithExcludePatterns(p.settings.ExcludePaths...))
	}

	filter, err := gogenfilter.NewFilter(configs...)
	if err != nil {
		return nil, fmt.Errorf("gogenfilter: create filter: %w", err)
	}

	p.filter = filter

	return []*analysis.Analyzer{{
		Name: "gogenfilter",
		Doc:  "detect auto-generated Go files (sqlc, templ, protobuf, mockgen, etc.)",
		Run:  p.run,
	}}, nil
}

// GetLoadMode implements register.LinterPlugin.
func (p *gogenfilterPlugin) GetLoadMode() string {
	return register.LoadModeSyntax
}

func (p *gogenfilterPlugin) buildFilterOptions() (gogenfilter.FilterConfig, error) {
	if len(p.settings.Generators) == 0 {
		return gogenfilter.WithFilterOptions(gogenfilter.FilterAll)
	}

	opts := make([]gogenfilter.FilterOption, len(p.settings.Generators))
	for i, gen := range p.settings.Generators {
		opts[i] = gogenfilter.FilterOption(gen)
	}

	return gogenfilter.WithFilterOptions(opts...)
}

func (p *gogenfilterPlugin) run(pass *analysis.Pass) (any, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return nil, fmt.Errorf("gogenfilter: get working directory: %w", err)
	}

	for _, file := range pass.Files {
		pos := pass.Fset.Position(file.Pos())

		filename := pos.Filename
		if filename == "" {
			continue
		}

		relPath, relErr := filepath.Rel(cwd, filename)
		if relErr != nil {
			relPath = filename
		}

		result, filterErr := p.filter.FilterDetailed(relPath)
		if filterErr != nil {
			continue
		}

		if result.Filtered && result.Reason != gogenfilter.ReasonNotFiltered {
			pass.Report(analysis.Diagnostic{
				Pos:      file.Pos(),
				End:      file.End(),
				Category: "generated",
				Message: fmt.Sprintf(
					"file is auto-generated by %s — consider excluding from linting",
					result.Reason,
				),
			})
		}
	}

	return nil, nil
}
