// Code generated by moq; DO NOT EDIT.

package service

import (
	"context"
	"sync"
)

var lockServiceMock sync.RWMutex

type ServiceMock struct {
	GetUserFunc func(ctx context.Context, id string) (*User, error)
	calls       struct {
		GetUser []struct {
			Ctx context.Context
			ID  string
		}
	}
}

func (mock *ServiceMock) GetUser(ctx context.Context, id string) (*User, error) {
	if mock.GetUserFunc == nil {
		panic("ServiceMock.GetUserFunc: method is nil but was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{Ctx: ctx, ID: id}
	lockServiceMock.Lock()
	mock.calls.GetUser = append(mock.calls.GetUser, callInfo)
	lockServiceMock.Unlock()
	return mock.GetUserFunc(ctx, id)
}
