// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.

package petstore

import (
	"context"
	"net/http"
)

type Pet struct {
	Id   int64  `json:"id,omitempty"`
	Name string `json:"name"`
	Tag  string `json:"tag,omitempty"`
}

type PetStore interface {
	FindPets(ctx context.Context, params FindPetsParams) ([]Pet, error)
	AddPet(ctx context.Context, pet NewPet) (Pet, error)
}

type ServerInterface interface {
	FindPets(w http.ResponseWriter, r *http.Request)
	AddPet(w http.ResponseWriter, r *http.Request)
}
