import type { Generator } from "./types";

export const logoPaths = [
  "/logos/sqlc.svg",
  "/logos/templ.svg",
  "/logos/protobuf.svg",
  "/logos/go-enum.svg",
  "/logos/mockgen.svg",
  "/logos/moq.svg",
  "/logos/wire.svg",
  "/logos/oapi-codegen.svg",
  "/logos/deepcopy-gen.svg",
  "/logos/stringer.svg",
  "/logos/generic.svg",
] as const;
export type LogoPath = (typeof logoPaths)[number];

export const generators: Generator[] = [
  { name: "sqlc", file: ".sql.go", url: "https://sqlc.dev", logo: "/logos/sqlc.svg" as LogoPath },
  { name: "templ", file: "_templ.go", url: "https://templ.guide", logo: "/logos/templ.svg" as LogoPath },
  { name: "protobuf", file: ".pb.go", url: "https://protobuf.dev", logo: "/logos/protobuf.svg" as LogoPath },
  {
    name: "go-enum",
    file: "_enum.go",
    url: "https://github.com/abice/go-enum",
    logo: "/logos/go-enum.svg" as LogoPath,
  },
  {
    name: "mockgen",
    file: "_mock.go",
    url: "https://github.com/golang/mock",
    logo: "/logos/mockgen.svg" as LogoPath,
  },
  { name: "moq", file: "_moq.go", url: "https://github.com/matryer/moq", logo: "/logos/moq.svg" as LogoPath },
  {
    name: "wire",
    file: "wire_gen.go",
    url: "https://github.com/google/wire",
    logo: "/logos/wire.svg" as LogoPath,
  },
  {
    name: "oapi-codegen",
    file: ".gen.go",
    url: "https://github.com/oapi-codegen/oapi-codegen",
    logo: "/logos/oapi-codegen.svg" as LogoPath,
  },
  {
    name: "deepcopy-gen",
    file: "zz_generated.*",
    url: "https://github.com/kubernetes/gengo",
    logo: "/logos/deepcopy-gen.svg" as LogoPath,
  },
  {
    name: "stringer",
    file: "content marker",
    url: "https://pkg.go.dev/golang.org/x/tools/cmd/stringer",
    logo: "/logos/stringer.svg" as LogoPath,
  },
  { name: "generic", file: "Code generated by", url: "", logo: "/logos/generic.svg" as LogoPath },
];

export const generatorCount = generators.length;
