import type { Generator } from './types';

export const generators: Generator[] = [
  { name: 'sqlc', file: '.sql.go', url: 'https://sqlc.dev', logo: '/logos/sqlc.svg' },
  { name: 'templ', file: '_templ.go', url: 'https://templ.guide', logo: '/logos/templ.svg' },
  { name: 'protobuf', file: '.pb.go', url: 'https://protobuf.dev', logo: '/logos/protobuf.svg' },
  { name: 'go-enum', file: '_enum.go', url: 'https://github.com/abice/go-enum', logo: '/logos/go-enum.svg' },
  { name: 'mockgen', file: '_mock.go', url: 'https://github.com/golang/mock', logo: '/logos/mockgen.svg' },
  { name: 'moq', file: '_moq.go', url: 'https://github.com/matryer/moq', logo: '/logos/moq.svg' },
  { name: 'wire', file: 'wire_gen.go', url: 'https://github.com/google/wire', logo: '/logos/wire.svg' },
  { name: 'oapi-codegen', file: '.gen.go', url: 'https://github.com/oapi-codegen/oapi-codegen', logo: '/logos/oapi-codegen.svg' },
  { name: 'deepcopy-gen', file: 'zz_generated.*', url: 'https://github.com/kubernetes/gengo', logo: '/logos/deepcopy-gen.svg' },
  { name: 'stringer', file: 'content marker', url: 'https://pkg.go.dev/golang.org/x/tools/cmd/stringer', logo: '/logos/stringer.svg' },
  { name: 'generic', file: 'Code generated by', url: '', logo: '/logos/generic.svg' },
];

export const generatorCount = generators.length;
