import type { PhaseCard, ComparisonItem, UseCase } from "./types";
import { generatorCount } from "./generators";

export const phases: PhaseCard[] = [
  {
    phase: "P1",
    phaseColor: "accent",
    title: "Phase 1: Filename",
    patterns: [".pb.go", "_templ.go", "wire_gen.go"],
    note: "Zero I/O — no file reads",
    noteColor: "accent",
    noteIcon: "bolt",
  },
  {
    phase: "P2",
    phaseColor: "amber",
    title: "Phase 2: Content",
    patterns: ['"Code generated by"', "stringer iota markers"],
    note: "Only runs when Phase 1 is inconclusive",
    noteColor: "amber",
    noteIcon: "check",
  },
];

export const comparisons: ComparisonItem[] = [
  {
    variant: "DIY",
    price: "DIY",
    accent: false,
    pros: [],
    cons: ["No filename detection", "Manual pattern maintenance", "No structued results"],
  },
  {
    variant: "gogenfilter",
    price: "Free",
    accent: true,
    pros: [
      `${generatorCount} generators, table-driven`,
      "Two-phase (zero I/O first)",
      "FilterResult with trace info",
      "fs.FS testable",
      "Pattern scoping",
    ],
    cons: [],
  },
  {
    variant: "Heavy",
    price: "Heavy",
    accent: false,
    pros: [],
    cons: ["Requires go/ast import", "Slow (parse entire file)", "Overkill for filtering"],
  },
];

export const useCases: UseCase[] = [
  {
    title: "Linters",
    desc: "Skip generated files in static analysis",
    icon: "cog",
  },
  {
    title: "Code Quality",
    desc: "Exclude generated code from metrics",
    icon: "chart",
  },
  {
    title: "CI / CD",
    desc: "Filter noise from review tooling",
    icon: "refresh",
  },
];
