import type { PhaseCard, ComparisonItem, UseCase } from './types';
import { generatorCount } from './generators';

export const phases: PhaseCard[] = [
  {
    phase: 'P1',
    phaseColor: 'accent',
    title: 'Phase 1: Filename',
    patterns: ['.pb.go', '_templ.go', 'wire_gen.go'],
    note: 'Zero I/O — no file reads',
    noteColor: 'accent',
    noteIcon: 'bolt',
  },
  {
    phase: 'P2',
    phaseColor: 'amber',
    title: 'Phase 2: Content',
    patterns: ['"Code generated by"', 'stringer iota markers'],
    note: 'Only runs when Phase 1 is inconclusive',
    noteColor: 'amber',
    noteIcon: 'check',
  },
];

export const comparisons: ComparisonItem[] = [
  {
    variant: 'DIY',
    price: 'DIY',
    accent: false,
    pros: [],
    cons: [
      'No filename detection',
      'Manual pattern maintenance',
      'No metrics',
    ],
  },
  {
    variant: 'gogenfilter',
    price: 'Free',
    accent: true,
    pros: [
      `${generatorCount} generators, table-driven`,
      'Two-phase (zero I/O first)',
      'Thread-safe metrics',
      'fs.FS testable',
      'Pattern scoping',
    ],
    cons: [],
  },
  {
    variant: 'Heavy',
    price: 'Heavy',
    accent: false,
    pros: [],
    cons: [
      'Requires go/ast import',
      'Slow (parse entire file)',
      'Overkill for filtering',
    ],
  },
];

export const useCases: UseCase[] = [
  {
    title: 'Linters',
    desc: 'Skip generated files in static analysis',
    icon: 'cog',
  },
  {
    title: 'Code Quality',
    desc: 'Exclude generated code from metrics',
    icon: 'chart',
  },
  {
    title: 'CI / CD',
    desc: 'Filter noise from review tooling',
    icon: 'refresh',
  },
];

export const useCaseIcons: Record<string, string> = {
  cog: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.066 2.573c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.573 1.066c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.066-2.573c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>',
  chart: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/>',
  refresh: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/>',
  bolt: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>',
  check: '<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>',
};
