import type { PhaseCard, UseCase } from "./types";

export const phases: PhaseCard[] = [
  {
    phase: "P1",
    phaseColor: "accent",
    title: "Phase 1: Filename",
    patterns: [".pb.go", "_templ.go", "wire_gen.go"],
    hint: "Zero I/O — no file reads",
    hintColor: "accent",
    hintIcon: "bolt",
  },
  {
    phase: "P2",
    phaseColor: "amber",
    title: "Phase 2: Content",
    patterns: ['"Code generated by"', "stringer iota markers"],
    hint: "Only runs when Phase 1 is inconclusive",
    hintColor: "amber",
    hintIcon: "check",
  },
];

export const useCases: UseCase[] = [
  {
    title: "Linters",
    desc: "Skip generated files in static analysis",
    icon: "cog",
    accent: "accent",
  },
  {
    title: "Code Quality",
    desc: "Exclude generated code from reports",
    icon: "chart",
    accent: "amber",
  },
  {
    title: "CI / CD",
    desc: "Filter noise from review tooling",
    icon: "refresh",
    accent: "success",
  },
];
