// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import "fmt"

func main() {
	app := InitializeApp()
	fmt.Println(app.Run())
}
