// Code generated by "stringer" -type=Priority . DO NOT EDIT.

package priority

import "strconv"

func _() {
	var x [1]struct{}
	_ = x[PriorityLow-1]
	_ = x[PriorityMedium-2]
	_ = x[PriorityHigh-3]
}

const _Priority_name = "LowMediumHigh"

var _Priority_index = [...]uint8{0, 3, 9, 13}

func (i Priority) String() string {
	i -= 1
	if i < 0 || i >= Priority(len(_Priority_index)-1) {
		return "Priority(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Priority_name[_Priority_index[i]:_Priority_index[i+1]]
}
