// Code generated by templ - DO NOT EDIT.

package templ

import (
	"context"
	"io"

	"github.com/a-h/templ"
)

func Page() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		return nil
	})
}
