// Code generated by mockery v2.53.3. DO NOT EDIT.
//
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/stretchr/testify/mock"
)

type MockUserService struct {
	mock.Mock
}

func (m *MockUserService) GetUser(id string) (string, error) {
	args := m.Called(id)
	return args.String(0), args.Error(1)
}
