// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entgo.io/ent/dialect/sql"
)

type UserClient struct {
	config
}

func (c *UserClient) Create() *UserCreate {
	return &UserCreate{config: c.config}
}
